/**
 * The invented half of the revenue dashboard.
 *
 * GENERATED by scripts/build-bi.mjs — do not hand-edit.
 *
 * NONE OF THIS IS REAL. The complexes it refers to are (lib/bi.roster.data.ts
 * — real names, real districts, real completion years, estimated household
 * counts) but no contract, price, invoice, cancellation or salesperson below
 * corresponds to anything that happened. What an apartment management app
 * charges is commercial information with no public form, so a dashboard on
 * this subject either invents its revenue or does not exist; this one invents
 * it, from seed 'goldibug/bi/2026-09', and every page that draws from this file has to
 * say so where a reader will see it.
 *
 * WHAT IS REAL IS THE DENOMINATOR. Penetration is
 * 952 contracted complexes out of 36,040 filed with
 * 국토교통부 — 2.64% — and against the
 * 18,888 large enough to have a management office,
 * 4.66%. Those two
 * differ by a factor of about two and the dashboard shows both, because the
 * first understates the product and the second hides how much of the country
 * it cannot reach.
 *
 * TWO FINDINGS ARE DESIGNED IN. They are not discoveries and the page says
 * so; they are here because a dashboard that cannot be read wrong cannot
 * demonstrate reading it right.
 *
 *   1  PER-HOUSEHOLD PRICE RUNS BACKWARDS TO PRICE PER COMPLEX. Two ordinary
 *      terms do it — a marginal volume discount above 1,000 households, and a
 *      50,000원 monthly floor. Held to one fixed bundle and walked up a
 *      size ladder (BI_RATE_CARD), the cheapest bundle costs
 *      500원 per household at 100 households and
 *      129.5원 at 6000. A revenue-by-tier bar chart and a
 *      revenue-per-household bar chart are the same data and give opposite
 *      instructions to a sales manager.
 *
 *      THIS IS ARGUED FROM THE RATE CARD, NOT FROM THE REALISED AVERAGES, and
 *      an earlier version of this file got that wrong. Averaging per-household
 *      revenue over a tier mixes the price structure with which services those
 *      complexes happen to hold; the largest tier has about
 *      19 accounts, and on one seed its average came out
 *      cleanly monotone while on the next it did not. The pattern was real and
 *      the evidence was a coincidence. BI_TIER_ECONOMICS still publishes the
 *      realised numbers, with the account count beside each one, and is meant
 *      to be read against the ladder rather than in place of it.
 *
 *   2  MRR RISES EVERY MONTH WHILE COHORTS DECAY. Total subscription MRR goes
 *      from 81,994,678원 to 283,116,862원 across 36 months
 *      without a single down month, and cumulative churn over the same window
 *      is 86,046,633원. New business covers
 *      it. The headline line cannot show that; MOVEMENT and COHORTS can.
 *
 * MRR IS SUBSCRIPTION ONLY. Usage — votes held, SMS fallbacks sent — is
 * reported separately and is 3.0%
 * of total billings. Folding it into MRR would make the movement identity
 * below unreconcilable and the growth rate a function of the holiday
 * calendar.
 *
 * SUBSCRIPTION IS A STEP FUNCTION and usage is not. A per-household fee times
 * a household count that does not change is the same number every month until
 * the contract changes; `pnpm check:bi` asserts it never drifts. Usage
 * carries an AR(1) with phi 0.6 and named seasonality only — resident
 * council elections in November and December, 명절 visitor traffic, moving
 * season SMS. Nothing seasonal was added that a cause could not be given for.
 *
 * Per-complex monthly rows are not here: 21,182 of them are
 * 1,383 KB under public/data/bi/series/, one file per
 * month. Contracts (3,206) and the pipeline
 * (2,512) are beside them.
 */

export type BillingModel = 'perHH' | 'perComplex' | 'perEvent' | 'perUse'

export type Service = {
  readonly id: string
  readonly model: BillingModel
  /** KRW. Per household per month, per complex per month, or per unit. */
  readonly price: number
  /** Households below which the service has nothing to do. */
  readonly minHouseholds?: number
  /** Completion year from which the service applies. */
  readonly minYear?: number
  /** Service that must already be held. A hard dependency. */
  readonly needs?: string
  /** One-off installation, as a range. */
  readonly setup?: readonly [number, number]
}

/** The window every series below covers, inclusive. */
export const BI_WINDOW = { from: '202309', to: '202608', months: 36 } as const
export const BI_MONTHS: readonly string[] = ["202309","202310","202311","202312","202401","202402","202403","202404","202405","202406","202407","202408","202409","202410","202411","202412","202501","202502","202503","202504","202505","202506","202507","202508","202509","202510","202511","202512","202601","202602","202603","202604","202605","202606","202607","202608"]

/** The seed. Rerunning build-bi.mjs with it reproduces every number here. */
export const BI_SEED = 'goldibug/bi/2026-09'

export const BI_SERVICES: readonly Service[] = [
  { id: 'parking', model: 'perHH', price: 480, minHouseholds: 100, setup: [1500000, 6000000] },
  { id: 'visitor', model: 'perHH', price: 110, needs: 'parking' },
  { id: 'access', model: 'perHH', price: 250, minHouseholds: 200, setup: [1000000, 4000000] },
  { id: 'cctv', model: 'perHH', price: 160, minHouseholds: 150, setup: [800000, 3000000] },
  { id: 'billing', model: 'perHH', price: 320 },
  { id: 'notice', model: 'perHH', price: 150 },
  { id: 'community', model: 'perComplex', price: 90000, minHouseholds: 300 },
  { id: 'defect', model: 'perComplex', price: 80000, minYear: 2021 },
  { id: 'locker', model: 'perComplex', price: 50000, minHouseholds: 150, setup: [400000, 1200000] },
  { id: 'vote', model: 'perEvent', price: 180000 },
  { id: 'sms', model: 'perUse', price: 15, needs: 'notice' },
]

/**
 * The volume discount, on marginal bands. The first 1,000 households of a
 * 3,000-household complex pay full rate.
 */
export const BI_VOLUME_BANDS: readonly { readonly upTo: number; readonly rate: number }[] = [
  { upTo: 1000, rate: 1 },
  { upTo: 2000, rate: 0.9 },
  { upTo: Infinity, rate: 0.82 },
]

/** Monthly floor across a complex's per-household services, in KRW. */
export const BI_MIN_MONTHLY = 50000

export type MovementRow = {
  readonly month: string
  /** Subscription MRR at the start of the month, in KRW. */
  readonly start: number
  readonly new: number
  readonly winback: number
  readonly expansion: number
  readonly contraction: number
  readonly churn: number
  readonly end: number
  /** Complexes billing anything this month. */
  readonly complexes: number
  /** Usage billings this month. NOT part of MRR. */
  readonly usage: number
}

/**
 * The movement waterfall. `end === start + new + winback + expansion -
 * contraction - churn` holds in all 60 rows, and `pnpm check:bi`
 * recomputes both sides from public/data/bi/series/ to prove it. A revenue
 * table whose movements do not reconcile is a revenue table with a bug
 * somewhere upstream of the chart, and it is the commonest way a real BI
 * dashboard reports a wrong number confidently.
 */
export const BI_MOVEMENT: readonly MovementRow[] = [
  { month: '202309', start: 80815598, new: 2631018, winback: 0, expansion: 411070, contraction: 0, churn: 1863008, end: 81994678, complexes: 293, usage: 2526930 },
  { month: '202310', start: 81994678, new: 5342310, winback: 200800, expansion: 405480, contraction: 0, churn: 0, end: 87943268, complexes: 314, usage: 4490520 },
  { month: '202311', start: 87943268, new: 5468812, winback: 0, expansion: 893380, contraction: 0, churn: 841820, end: 93463640, complexes: 335, usage: 7221210 },
  { month: '202312', start: 93463640, new: 4300204, winback: 0, expansion: 1392288, contraction: 0, churn: 288580, end: 98867552, complexes: 350, usage: 6332430 },
  { month: '202401', start: 98867552, new: 3718680, winback: 99600, expansion: 868730, contraction: 0, churn: 1243900, end: 102310662, complexes: 364, usage: 2383005 },
  { month: '202402', start: 102310662, new: 2876180, winback: 0, expansion: 996470, contraction: 0, churn: 509160, end: 105674152, complexes: 381, usage: 1718685 },
  { month: '202403', start: 105674152, new: 4030112, winback: 0, expansion: 2212480, contraction: 0, churn: 1389080, end: 110527664, complexes: 388, usage: 1949295 },
  { month: '202404', start: 110527664, new: 3266552, winback: 0, expansion: 885280, contraction: 0, churn: 3187966, end: 111491530, complexes: 398, usage: 2092545 },
  { month: '202405', start: 111491530, new: 6139492, winback: 0, expansion: 377840, contraction: 0, churn: 2225740, end: 115783122, complexes: 418, usage: 1936035 },
  { month: '202406', start: 115783122, new: 4025558, winback: 163560, expansion: 1338866, contraction: 0, churn: 1290480, end: 120020626, complexes: 431, usage: 3218115 },
  { month: '202407', start: 120020626, new: 5259902, winback: 0, expansion: 1322660, contraction: 0, churn: 4813556, end: 121789632, complexes: 430, usage: 1965615 },
  { month: '202408', start: 121789632, new: 4944224, winback: 0, expansion: 1165920, contraction: 0, churn: 1525340, end: 126374436, complexes: 443, usage: 2389395 },
  { month: '202409', start: 126374436, new: 6271224, winback: 0, expansion: 707760, contraction: 0, churn: 2174860, end: 131178560, complexes: 459, usage: 4042845 },
  { month: '202410', start: 131178560, new: 11680942, winback: 0, expansion: 479720, contraction: 0, churn: 1324940, end: 142014282, complexes: 490, usage: 6687165 },
  { month: '202411', start: 142014282, new: 4941567, winback: 111360, expansion: 2060074, contraction: 0, churn: 1474680, end: 147652603, complexes: 506, usage: 10106640 },
  { month: '202412', start: 147652603, new: 8443520, winback: 0, expansion: 1313764, contraction: 0, churn: 2018448, end: 155391439, complexes: 521, usage: 12655905 },
  { month: '202501', start: 155391439, new: 5896508, winback: 798966, expansion: 280220, contraction: 0, churn: 3091522, end: 159275611, complexes: 540, usage: 2405805 },
  { month: '202502', start: 159275611, new: 11441616, winback: 0, expansion: 1062420, contraction: 0, churn: 3445360, end: 168334287, complexes: 556, usage: 4032240 },
  { month: '202503', start: 168334287, new: 6036780, winback: 0, expansion: 1078540, contraction: 0, churn: 907660, end: 174541947, complexes: 573, usage: 4546650 },
  { month: '202504', start: 174541947, new: 3860440, winback: 0, expansion: 2217660, contraction: 0, churn: 1697910, end: 178922137, complexes: 588, usage: 4117185 },
  { month: '202505', start: 178922137, new: 3074040, winback: 0, expansion: 1453112, contraction: 0, churn: 2099567, end: 181349722, complexes: 601, usage: 3085245 },
  { month: '202506', start: 181349722, new: 5858220, winback: 0, expansion: 3443012, contraction: 0, churn: 1218460, end: 189432494, complexes: 626, usage: 3471165 },
  { month: '202507', start: 189432494, new: 7975046, winback: 0, expansion: 1161900, contraction: 0, churn: 6190038, end: 192379402, complexes: 644, usage: 3264300 },
  { month: '202508', start: 192379402, new: 7766584, winback: 0, expansion: 1488288, contraction: 0, churn: 174400, end: 201459874, complexes: 667, usage: 3599295 },
  { month: '202509', start: 201459874, new: 12555237, winback: 0, expansion: 2230312, contraction: 0, churn: 5652852, end: 210592571, complexes: 702, usage: 4674765 },
  { month: '202510', start: 210592571, new: 5822476, winback: 50000, expansion: 1464180, contraction: 0, churn: 3872036, end: 214057191, complexes: 719, usage: 7128390 },
  { month: '202511', start: 214057191, new: 7831516, winback: 0, expansion: 663184, contraction: 0, churn: 2495844, end: 220056047, complexes: 740, usage: 17479095 },
  { month: '202512', start: 220056047, new: 6157767, winback: 0, expansion: 1382200, contraction: 0, churn: 1102914, end: 226493100, complexes: 769, usage: 16041600 },
  { month: '202601', start: 226493100, new: 7717170, winback: 0, expansion: 1614960, contraction: 0, churn: 7849359, end: 227975871, complexes: 775, usage: 4680780 },
  { month: '202602', start: 227975871, new: 8141839, winback: 236080, expansion: 1787146, contraction: 0, churn: 2517100, end: 235623836, complexes: 801, usage: 4858605 },
  { month: '202603', start: 235623836, new: 8966761, winback: 0, expansion: 1946352, contraction: 0, churn: 2823610, end: 243713339, complexes: 824, usage: 5582895 },
  { month: '202604', start: 243713339, new: 9098174, winback: 564800, expansion: 2547750, contraction: 0, churn: 3498120, end: 252425943, complexes: 856, usage: 7604205 },
  { month: '202605', start: 252425943, new: 13477474, winback: 0, expansion: 1188680, contraction: 0, churn: 2813240, end: 264278857, complexes: 883, usage: 5813925 },
  { month: '202606', start: 264278857, new: 7227400, winback: 0, expansion: 1693428, contraction: 0, churn: 1721420, end: 271478265, complexes: 913, usage: 4012335 },
  { month: '202607', start: 271478265, new: 8251196, winback: 0, expansion: 1841380, contraction: 0, churn: 3454860, end: 278115981, complexes: 932, usage: 6005430 },
  { month: '202608', start: 278115981, new: 6600380, winback: 0, expansion: 1649304, contraction: 0, churn: 3248803, end: 283116862, complexes: 952, usage: 7238100 },
]

export type AdoptionRow = {
  readonly month: string
  readonly complexes: number
  /** Of those, at or above the addressable household floor. */
  readonly addressable: number
  /** Households under contract. */
  readonly households: number
  readonly byTier: Readonly<Record<string, number>>
  readonly bySido: Readonly<Record<string, number>>
}

/**
 * Penetration over time. The numerators are invented; every denominator
 * below is counted from the filings.
 */
export const BI_ADOPTION: readonly AdoptionRow[] = [
  { month: '202309', complexes: 293, addressable: 273, households: 160124, byTier: {"sub":20,"small":107,"mid":120,"large":40,"xlarge":6}, bySido: {"부산광역시":19,"강원특별자치도":14,"충청북도":6,"경기도":78,"대구광역시":16,"울산광역시":10,"서울특별시":57,"경상북도":15,"경상남도":19,"전북특별자치도":10,"인천광역시":15,"충청남도":14,"대전광역시":15,"제주특별자치도":1,"세종특별자치시":4} },
  { month: '202310', complexes: 314, addressable: 291, households: 170126, byTier: {"sub":23,"small":114,"mid":129,"large":41,"xlarge":7}, bySido: {"부산광역시":19,"강원특별자치도":14,"충청북도":6,"경기도":88,"대구광역시":16,"울산광역시":10,"서울특별시":62,"경상북도":15,"경상남도":20,"대전광역시":17,"전북특별자치도":10,"인천광역시":17,"충청남도":15,"제주특별자치도":1,"세종특별자치시":4} },
  { month: '202311', complexes: 335, addressable: 311, households: 180666, byTier: {"sub":24,"small":122,"mid":137,"large":45,"xlarge":7}, bySido: {"부산광역시":19,"강원특별자치도":13,"충청북도":6,"경기도":98,"대구광역시":17,"울산광역시":11,"서울특별시":66,"경상북도":15,"경상남도":23,"대전광역시":19,"전북특별자치도":11,"인천광역시":17,"충청남도":15,"제주특별자치도":1,"세종특별자치시":4} },
  { month: '202312', complexes: 350, addressable: 325, households: 190398, byTier: {"sub":25,"small":126,"mid":143,"large":49,"xlarge":7}, bySido: {"부산광역시":19,"강원특별자치도":13,"충청북도":6,"경기도":102,"대구광역시":17,"울산광역시":12,"서울특별시":74,"경상북도":15,"경상남도":23,"대전광역시":19,"전북특별자치도":12,"인천광역시":17,"충청남도":16,"제주특별자치도":1,"세종특별자치시":4} },
  { month: '202401', complexes: 364, addressable: 338, households: 198072, byTier: {"sub":26,"small":133,"mid":145,"large":53,"xlarge":7}, bySido: {"부산광역시":21,"강원특별자치도":15,"충청북도":6,"경기도":106,"대구광역시":16,"울산광역시":12,"서울특별시":79,"경상북도":15,"경상남도":24,"대전광역시":18,"전북특별자치도":13,"인천광역시":18,"충청남도":16,"제주특별자치도":1,"세종특별자치시":4} },
  { month: '202402', complexes: 381, addressable: 352, households: 207694, byTier: {"sub":29,"small":136,"mid":154,"large":54,"xlarge":8}, bySido: {"부산광역시":21,"강원특별자치도":14,"충청북도":6,"서울특별시":83,"인천광역시":20,"경기도":114,"대구광역시":16,"울산광역시":12,"경상북도":17,"경상남도":24,"대전광역시":18,"전북특별자치도":14,"충청남도":16,"제주특별자치도":1,"세종특별자치시":5} },
  { month: '202403', complexes: 388, addressable: 357, households: 210676, byTier: {"sub":31,"small":138,"mid":156,"large":54,"xlarge":9}, bySido: {"경상남도":25,"부산광역시":20,"강원특별자치도":14,"충청북도":6,"서울특별시":86,"인천광역시":19,"경기도":117,"대구광역시":16,"울산광역시":14,"경상북도":17,"대전광역시":18,"전북특별자치도":13,"충청남도":16,"제주특별자치도":1,"세종특별자치시":6} },
  { month: '202404', complexes: 398, addressable: 365, households: 212462, byTier: {"sub":33,"small":143,"mid":160,"large":53,"xlarge":9}, bySido: {"경상남도":26,"부산광역시":21,"강원특별자치도":14,"충청북도":5,"서울특별시":87,"인천광역시":19,"경기도":117,"대구광역시":17,"울산광역시":14,"경상북도":19,"대전광역시":19,"전북특별자치도":16,"충청남도":16,"제주특별자치도":2,"세종특별자치시":6} },
  { month: '202405', complexes: 418, addressable: 384, households: 224120, byTier: {"sub":34,"small":151,"mid":169,"large":54,"xlarge":10}, bySido: {"경상남도":31,"부산광역시":22,"강원특별자치도":14,"충청북도":6,"서울특별시":86,"인천광역시":20,"경기도":123,"대구광역시":20,"울산광역시":14,"경상북도":20,"대전광역시":20,"전북특별자치도":18,"충청남도":16,"제주특별자치도":2,"세종특별자치시":6} },
  { month: '202406', complexes: 431, addressable: 397, households: 231456, byTier: {"sub":34,"small":159,"mid":172,"large":55,"xlarge":11}, bySido: {"경상남도":30,"부산광역시":24,"강원특별자치도":16,"충청북도":7,"서울특별시":90,"인천광역시":20,"경기도":125,"대구광역시":22,"울산광역시":14,"경상북도":22,"대전광역시":21,"전북특별자치도":18,"충청남도":15,"제주특별자치도":2,"세종특별자치시":5} },
  { month: '202407', complexes: 430, addressable: 394, households: 234776, byTier: {"sub":36,"small":153,"mid":177,"large":52,"xlarge":12}, bySido: {"경상남도":30,"부산광역시":24,"강원특별자치도":18,"충청북도":6,"서울특별시":85,"인천광역시":18,"경기도":130,"대구광역시":23,"울산광역시":14,"경상북도":19,"대전광역시":21,"전북특별자치도":19,"충청남도":14,"제주특별자치도":2,"세종특별자치시":7} },
  { month: '202408', complexes: 443, addressable: 406, households: 243598, byTier: {"sub":37,"small":158,"mid":180,"large":56,"xlarge":12}, bySido: {"경상남도":32,"부산광역시":24,"강원특별자치도":18,"충청북도":8,"서울특별시":86,"경기도":134,"인천광역시":18,"대구광역시":23,"울산광역시":14,"경상북도":20,"대전광역시":22,"전북특별자치도":19,"충청남도":15,"제주특별자치도":2,"세종특별자치시":8} },
  { month: '202409', complexes: 459, addressable: 421, households: 253448, byTier: {"sub":38,"small":162,"mid":187,"large":60,"xlarge":12}, bySido: {"경상남도":34,"부산광역시":26,"강원특별자치도":18,"서울특별시":86,"충청북도":8,"경기도":143,"인천광역시":18,"대구광역시":25,"울산광역시":14,"경상북도":18,"대전광역시":22,"전북특별자치도":21,"충청남도":16,"제주특별자치도":2,"세종특별자치시":8} },
  { month: '202410', complexes: 490, addressable: 451, households: 276886, byTier: {"sub":39,"small":173,"mid":196,"large":69,"xlarge":13}, bySido: {"경상남도":36,"부산광역시":31,"강원특별자치도":18,"서울특별시":98,"충청북도":8,"경기도":147,"인천광역시":18,"대구광역시":27,"울산광역시":16,"경상북도":20,"전북특별자치도":22,"충청남도":18,"대전광역시":21,"제주특별자치도":2,"세종특별자치시":8} },
  { month: '202411', complexes: 506, addressable: 464, households: 286628, byTier: {"sub":42,"small":180,"mid":198,"large":72,"xlarge":14}, bySido: {"경상남도":35,"부산광역시":31,"강원특별자치도":18,"서울특별시":104,"충청북도":8,"경기도":153,"인천광역시":20,"대구광역시":27,"경상북도":22,"울산광역시":17,"전북특별자치도":22,"충청남도":17,"대전광역시":22,"제주특별자치도":2,"세종특별자치시":8} },
  { month: '202412', complexes: 521, addressable: 478, households: 299576, byTier: {"sub":43,"small":188,"mid":197,"large":77,"xlarge":16}, bySido: {"경상남도":33,"경상북도":23,"부산광역시":35,"강원특별자치도":19,"서울특별시":111,"충청북도":9,"경기도":153,"인천광역시":22,"대구광역시":29,"울산광역시":17,"충청남도":17,"대전광역시":22,"전북특별자치도":21,"제주특별자치도":2,"세종특별자치시":8} },
  { month: '202501', complexes: 540, addressable: 494, households: 307002, byTier: {"sub":46,"small":198,"mid":201,"large":79,"xlarge":16}, bySido: {"경상남도":37,"경상북도":23,"부산광역시":36,"강원특별자치도":19,"서울특별시":113,"충청북도":10,"경기도":158,"인천광역시":22,"대구광역시":30,"울산광역시":21,"충청남도":19,"대전광역시":22,"전북특별자치도":19,"제주특별자치도":3,"세종특별자치시":8} },
  { month: '202502', complexes: 556, addressable: 509, households: 324366, byTier: {"sub":47,"small":200,"mid":207,"large":84,"xlarge":18}, bySido: {"경상남도":38,"경상북도":24,"부산광역시":36,"강원특별자치도":20,"서울특별시":116,"충청북도":10,"경기도":165,"인천광역시":22,"대구광역시":30,"울산광역시":20,"충청남도":20,"대전광역시":23,"전북특별자치도":20,"제주특별자치도":3,"세종특별자치시":9} },
  { month: '202503', complexes: 573, addressable: 524, households: 333554, byTier: {"sub":49,"small":206,"mid":212,"large":88,"xlarge":18}, bySido: {"경상남도":39,"경상북도":24,"부산광역시":37,"강원특별자치도":20,"서울특별시":119,"충청북도":13,"경기도":172,"인천광역시":25,"대구광역시":30,"울산광역시":20,"충청남도":20,"대전광역시":23,"전북특별자치도":20,"제주특별자치도":3,"세종특별자치시":8} },
  { month: '202504', complexes: 588, addressable: 537, households: 338364, byTier: {"sub":51,"small":213,"mid":217,"large":90,"xlarge":17}, bySido: {"경상남도":42,"경상북도":23,"부산광역시":37,"강원특별자치도":20,"서울특별시":126,"충청북도":13,"경기도":174,"인천광역시":25,"대구광역시":30,"울산광역시":21,"충청남도":21,"대전광역시":24,"전북특별자치도":21,"제주특별자치도":3,"세종특별자치시":8} },
  { month: '202505', complexes: 601, addressable: 548, households: 340902, byTier: {"sub":53,"small":219,"mid":222,"large":91,"xlarge":16}, bySido: {"경상남도":45,"경상북도":25,"부산광역시":38,"강원특별자치도":20,"서울특별시":130,"충청북도":13,"경기도":175,"인천광역시":25,"대구광역시":30,"울산광역시":20,"충청남도":22,"대전광역시":26,"전북특별자치도":21,"제주특별자치도":3,"세종특별자치시":8} },
  { month: '202506', complexes: 626, addressable: 569, households: 352504, byTier: {"sub":57,"small":226,"mid":234,"large":93,"xlarge":16}, bySido: {"경상남도":47,"경상북도":25,"부산광역시":39,"강원특별자치도":20,"서울특별시":134,"충청북도":12,"대전광역시":28,"경기도":187,"인천광역시":25,"대구광역시":30,"울산광역시":22,"충청남도":25,"전북특별자치도":21,"제주특별자치도":3,"세종특별자치시":8} },
  { month: '202507', complexes: 644, addressable: 587, households: 358060, byTier: {"sub":57,"small":238,"mid":240,"large":93,"xlarge":16}, bySido: {"경상남도":50,"경상북도":23,"부산광역시":45,"강원특별자치도":20,"충청북도":13,"서울특별시":135,"대전광역시":28,"인천광역시":25,"경기도":191,"대구광역시":33,"울산광역시":22,"충청남도":27,"전북특별자치도":21,"제주특별자치도":3,"세종특별자치시":8} },
  { month: '202508', complexes: 667, addressable: 610, households: 371542, byTier: {"sub":57,"small":245,"mid":252,"large":97,"xlarge":16}, bySido: {"경상남도":53,"경상북도":25,"부산광역시":44,"강원특별자치도":21,"충청북도":13,"서울특별시":143,"대전광역시":29,"인천광역시":27,"경기도":197,"대구광역시":34,"울산광역시":22,"충청남도":27,"전북특별자치도":21,"제주특별자치도":3,"세종특별자치시":8} },
  { month: '202509', complexes: 702, addressable: 640, households: 388416, byTier: {"sub":62,"small":255,"mid":267,"large":101,"xlarge":17}, bySido: {"경상남도":54,"경상북도":25,"부산광역시":46,"강원특별자치도":22,"충청북도":16,"서울특별시":149,"대전광역시":30,"인천광역시":29,"경기도":210,"대구광역시":36,"울산광역시":23,"충청남도":29,"전북특별자치도":21,"제주특별자치도":3,"세종특별자치시":9} },
  { month: '202510', complexes: 719, addressable: 654, households: 392102, byTier: {"sub":65,"small":260,"mid":275,"large":103,"xlarge":16}, bySido: {"경상남도":57,"경상북도":25,"부산광역시":48,"강원특별자치도":24,"충청북도":15,"서울특별시":151,"대전광역시":31,"인천광역시":30,"경기도":218,"대구광역시":36,"울산광역시":21,"충청남도":30,"전북특별자치도":21,"제주특별자치도":3,"세종특별자치시":9} },
  { month: '202511', complexes: 740, addressable: 673, households: 404090, byTier: {"sub":67,"small":265,"mid":286,"large":105,"xlarge":17}, bySido: {"경상남도":58,"경상북도":24,"부산광역시":49,"강원특별자치도":24,"충청북도":15,"서울특별시":156,"대전광역시":31,"인천광역시":30,"경기도":228,"대구광역시":39,"울산광역시":20,"충청남도":31,"전북특별자치도":23,"제주특별자치도":3,"세종특별자치시":9} },
  { month: '202512', complexes: 769, addressable: 702, households: 416622, byTier: {"sub":67,"small":278,"mid":300,"large":107,"xlarge":17}, bySido: {"경상남도":61,"경상북도":25,"부산광역시":50,"강원특별자치도":25,"충청북도":15,"서울특별시":158,"대전광역시":32,"인천광역시":32,"경기도":237,"대구광역시":42,"울산광역시":21,"충청남도":33,"전북특별자치도":24,"제주특별자치도":3,"세종특별자치시":11} },
  { month: '202601', complexes: 775, addressable: 707, households: 414468, byTier: {"sub":68,"small":286,"mid":300,"large":105,"xlarge":16}, bySido: {"경상남도":62,"경상북도":25,"부산광역시":47,"강원특별자치도":25,"충청북도":16,"서울특별시":157,"대전광역시":32,"인천광역시":34,"경기도":241,"대구광역시":45,"울산광역시":21,"충청남도":36,"전북특별자치도":23,"제주특별자치도":3,"세종특별자치시":8} },
  { month: '202602', complexes: 801, addressable: 732, households: 429796, byTier: {"sub":69,"small":304,"mid":302,"large":109,"xlarge":17}, bySido: {"경상남도":62,"경상북도":28,"부산광역시":51,"강원특별자치도":25,"충청북도":16,"서울특별시":161,"대전광역시":33,"제주특별자치도":4,"인천광역시":36,"경기도":244,"대구광역시":49,"울산광역시":21,"충청남도":37,"세종특별자치시":9,"전북특별자치도":25} },
  { month: '202603', complexes: 824, addressable: 756, households: 445418, byTier: {"sub":68,"small":312,"mid":314,"large":111,"xlarge":19}, bySido: {"경상남도":61,"경상북도":29,"부산광역시":54,"강원특별자치도":26,"충청북도":16,"서울특별시":171,"대전광역시":34,"제주특별자치도":4,"인천광역시":36,"경기도":251,"대구광역시":48,"울산광역시":21,"충청남도":38,"세종특별자치시":9,"전북특별자치도":26} },
  { month: '202604', complexes: 856, addressable: 788, households: 459908, byTier: {"sub":68,"small":329,"mid":326,"large":114,"xlarge":19}, bySido: {"경상남도":62,"경상북도":30,"부산광역시":58,"강원특별자치도":26,"충청북도":17,"서울특별시":176,"대전광역시":35,"제주특별자치도":5,"인천광역시":37,"경기도":261,"대구광역시":52,"울산광역시":22,"충청남도":37,"세종특별자치시":10,"전북특별자치도":28} },
  { month: '202605', complexes: 883, addressable: 813, households: 478932, byTier: {"sub":70,"small":339,"mid":332,"large":122,"xlarge":20}, bySido: {"경상남도":66,"경상북도":31,"부산광역시":64,"강원특별자치도":26,"충청북도":17,"서울특별시":181,"대전광역시":36,"제주특별자치도":5,"인천광역시":40,"경기도":268,"대구광역시":52,"울산광역시":24,"충청남도":35,"전북특별자치도":28,"세종특별자치시":10} },
  { month: '202606', complexes: 913, addressable: 842, households: 490764, byTier: {"sub":71,"small":356,"mid":343,"large":123,"xlarge":20}, bySido: {"경상남도":67,"경상북도":33,"부산광역시":69,"강원특별자치도":25,"충청북도":18,"서울특별시":189,"대전광역시":36,"제주특별자치도":7,"인천광역시":40,"경기도":279,"대구광역시":53,"울산광역시":23,"충청남도":36,"전북특별자치도":29,"세종특별자치시":9} },
  { month: '202607', complexes: 932, addressable: 860, households: 502632, byTier: {"sub":72,"small":357,"mid":358,"large":125,"xlarge":20}, bySido: {"경상남도":68,"서울특별시":197,"경상북도":31,"부산광역시":73,"강원특별자치도":26,"충청북도":19,"대전광역시":33,"인천광역시":40,"경기도":286,"울산광역시":23,"대구광역시":54,"충청남도":36,"전북특별자치도":31,"제주특별자치도":6,"세종특별자치시":9} },
  { month: '202608', complexes: 952, addressable: 880, households: 512518, byTier: {"sub":72,"small":363,"mid":369,"large":129,"xlarge":19}, bySido: {"경상남도":69,"서울특별시":201,"경상북도":32,"부산광역시":77,"강원특별자치도":26,"충청북도":19,"대전광역시":33,"인천광역시":39,"경기도":288,"울산광역시":22,"대구광역시":59,"충청남도":39,"전북특별자치도":33,"제주특별자치도":6,"세종특별자치시":9} },
]

/** The market, counted. Denominators for everything in BI_ADOPTION. */
export const BI_TAM = {
  complexes: 36040,
  addressable: 18888,
  byTier: {"sub":17152,"small":13782,"mid":4300,"large":744,"xlarge":62},
  bySido: {"서울특별시":8242,"부산광역시":3775,"대구광역시":1777,"인천광역시":1156,"대전광역시":958,"울산광역시":1319,"세종특별자치시":242,"경기도":7546,"충청북도":919,"충청남도":1396,"경상북도":2304,"경상남도":2960,"제주특별자치도":845,"강원특별자치도":1234,"전북특별자치도":1367},
} as const

/**
 * Active contracts per service per month — the attach rate's numerator.
 * Divided by BI_ADOPTION's `complexes`, not by BI_TAM: this measures what
 * customers buy, not what the market has adopted.
 */
export const BI_ATTACH: Readonly<Record<string, readonly number[]>> = {
  parking: [128,136,142,152,155,155,160,166,177,181,180,186,191,204,214,222,225,229,236,242,244,252,268,281,292,304,311,319,325,331,341,355,368,382,388,393],
  visitor: [12,12,11,12,12,12,13,13,15,16,19,21,21,21,23,23,26,27,28,30,32,34,35,38,38,43,43,43,41,43,43,47,47,51,52,53],
  access: [31,36,35,38,41,44,45,47,48,50,51,54,53,55,58,58,59,62,64,68,74,77,85,88,92,94,97,101,104,107,110,114,119,121,124,128],
  cctv: [37,40,45,47,47,49,50,55,59,64,65,65,66,67,70,73,76,80,81,84,88,95,102,106,114,114,115,121,119,124,131,137,143,151,160,167],
  billing: [136,147,161,163,169,174,181,187,191,200,202,208,214,228,236,243,257,267,278,286,289,302,305,319,342,352,362,377,384,401,411,423,441,452,461,470],
  notice: [159,168,185,191,199,211,219,221,230,239,240,247,260,275,281,293,308,317,326,340,349,364,375,389,405,417,431,445,448,464,473,491,500,521,534,552],
  community: [34,34,34,36,37,41,41,41,45,47,47,49,53,57,57,58,59,59,64,63,65,69,69,72,76,79,81,83,86,86,90,90,90,92,93,95],
  defect: [9,9,9,9,10,12,12,12,12,13,14,15,18,19,19,20,20,20,21,21,21,22,22,24,25,26,27,27,28,30,31,31,31,33,33,34],
  locker: [58,60,69,72,76,78,78,79,84,89,84,87,91,98,104,107,112,114,120,122,129,134,138,144,153,159,161,170,173,175,180,193,201,207,212,221],
  vote: [60,66,70,74,79,83,85,90,93,95,95,95,99,105,107,114,116,122,125,128,127,134,138,143,155,161,166,171,170,180,189,197,198,209,214,224],
  sms: [13,15,17,18,19,19,21,23,27,31,32,32,33,35,37,41,44,46,47,48,52,56,54,58,60,63,68,72,71,74,78,80,85,88,88,90],
}

export type TierEconomics = {
  readonly tier: string
  readonly complexes: number
  readonly households: number
  /** Subscription plus usage, final month, KRW. */
  readonly revenue: number
  readonly perComplex: number
  readonly perHousehold: number
  /** Accounts where the monthly floor topped the bill up. */
  readonly floored: number
}

/**
 * Realised economics per size tier, final month.
 *
 * NOT the evidence for finding 1 — BI_RATE_CARD is. This is what the tiers
 * actually billed, which is the price structure times whatever bundle those
 * particular complexes hold, and `complexes` is published beside every row
 * because the top tiers are thin enough that their averages move on one
 * account changing its mind. Read against the ladder: a tier sitting above it
 * is buying more than the reference bundle, below it is buying less.
 */
export const BI_TIER_ECONOMICS: readonly TierEconomics[] = [
  { tier: 'sub', complexes: 72, households: 6186, revenue: 5510050, perComplex: 76528, perHousehold: 890.7, floored: 52 },
  { tier: 'small', complexes: 363, households: 90428, revenue: 57070435, perComplex: 157219, perHousehold: 631.1, floored: 61 },
  { tier: 'mid', complexes: 369, households: 207558, revenue: 117688215, perComplex: 318938, perHousehold: 567, floored: 0 },
  { tier: 'large', complexes: 129, households: 156898, revenue: 83786336, perComplex: 649506, perHousehold: 534, floored: 0 },
  { tier: 'xlarge', complexes: 19, households: 51448, revenue: 26299926, perComplex: 1384207, perHousehold: 511.2, floored: 0 },
]

export type RateCardRow = {
  readonly households: number
  /** Monthly subscription for this bundle at this size, KRW. */
  readonly monthly: number
  readonly perHousehold: number
  /** True where the monthly floor, not the rate card, set the price. */
  readonly floored: boolean
}

export type RateCardBundle = {
  readonly id: string
  readonly services: readonly string[]
  /** Sum of list prices per household, before discount and before floor. */
  readonly list: number
  readonly rows: readonly RateCardRow[]
}

/**
 * Finding 1, as arithmetic rather than as an average.
 *
 * The bundle is held fixed and only household count varies, so nothing here
 * depends on which complexes happened to sign or what they happened to buy.
 * Both ladders fall monotonically and build-bi.mjs refuses to write this file
 * if either one rises.
 *
 * `entry` shows the monthly floor: below about 330 households the floor sets
 * the price, so the effective per-household rate is
 * 3.3x list at
 * 100 households and reaches list only past
 * 400.
 * `core` shows the volume bands: flat to 1,000 households, then falling to
 * 820.2원 at
 * 6000.
 *
 * BI_TIER_ECONOMICS is read against this, not instead of it. Where a tier's
 * realised average departs from the ladder the cause is bundle mix — a
 * different finding, and one that needs its own sample size before it is
 * worth stating.
 */
export const BI_RATE_CARD: readonly RateCardBundle[] = [
  {
    id: 'entry', services: ["notice"], list: 150,
    rows: [
      { households: 100, monthly: 50000, perHousehold: 500, floored: true },
      { households: 150, monthly: 50000, perHousehold: 333.3, floored: true },
      { households: 300, monthly: 50000, perHousehold: 166.7, floored: true },
      { households: 400, monthly: 60000, perHousehold: 150, floored: false },
      { households: 600, monthly: 90000, perHousehold: 150, floored: false },
      { households: 900, monthly: 135000, perHousehold: 150, floored: false },
      { households: 1200, monthly: 177000, perHousehold: 147.5, floored: false },
      { households: 2000, monthly: 285000, perHousehold: 142.5, floored: false },
      { households: 4000, monthly: 531000, perHousehold: 132.8, floored: false },
      { households: 6000, monthly: 777000, perHousehold: 129.5, floored: false },
    ],
  },
  {
    id: 'core', services: ["notice","billing","parking"], list: 950,
    rows: [
      { households: 100, monthly: 95000, perHousehold: 950, floored: false },
      { households: 150, monthly: 142500, perHousehold: 950, floored: false },
      { households: 300, monthly: 285000, perHousehold: 950, floored: false },
      { households: 400, monthly: 380000, perHousehold: 950, floored: false },
      { households: 600, monthly: 570000, perHousehold: 950, floored: false },
      { households: 900, monthly: 855000, perHousehold: 950, floored: false },
      { households: 1200, monthly: 1121000, perHousehold: 934.2, floored: false },
      { households: 2000, monthly: 1805000, perHousehold: 902.5, floored: false },
      { households: 4000, monthly: 3363000, perHousehold: 840.8, floored: false },
      { households: 6000, monthly: 4921000, perHousehold: 820.2, floored: false },
    ],
  },
]

export type DistrictPenetration = {
  readonly code: string
  /** Complexes billing in the final month. */
  readonly signed: number
}

/**
 * Per-district contracted complexes, final month. The map's numerator.
 *
 * Only districts with at least one are listed; the rest are absent and the
 * map reads them as zero rather than as missing — a district with an
 * addressable market and no customers is a fact about the sales coverage, and
 * the hexagon has to show it. Districts with no addressable complexes at all
 * are a different class and get the neutral fill.
 *
 * The denominator is in lib/bi.roster.data.ts, counted from the filings.
 */
export const BI_DISTRICT_PENETRATION: readonly DistrictPenetration[] = [
  { code: '11110', signed: 3 },
  { code: '11140', signed: 3 },
  { code: '11170', signed: 4 },
  { code: '11200', signed: 7 },
  { code: '11215', signed: 4 },
  { code: '11230', signed: 8 },
  { code: '11260', signed: 12 },
  { code: '11290', signed: 5 },
  { code: '11305', signed: 2 },
  { code: '11320', signed: 6 },
  { code: '11350', signed: 13 },
  { code: '11380', signed: 2 },
  { code: '11410', signed: 8 },
  { code: '11440', signed: 8 },
  { code: '11470', signed: 7 },
  { code: '11500', signed: 9 },
  { code: '11530', signed: 9 },
  { code: '11545', signed: 4 },
  { code: '11560', signed: 15 },
  { code: '11590', signed: 9 },
  { code: '11620', signed: 7 },
  { code: '11650', signed: 14 },
  { code: '11680', signed: 17 },
  { code: '11710', signed: 12 },
  { code: '11740', signed: 13 },
  { code: '26110', signed: 1 },
  { code: '26140', signed: 1 },
  { code: '26200', signed: 1 },
  { code: '26230', signed: 12 },
  { code: '26260', signed: 9 },
  { code: '26290', signed: 7 },
  { code: '26320', signed: 1 },
  { code: '26350', signed: 10 },
  { code: '26380', signed: 5 },
  { code: '26410', signed: 5 },
  { code: '26440', signed: 5 },
  { code: '26470', signed: 8 },
  { code: '26500', signed: 4 },
  { code: '26530', signed: 3 },
  { code: '26710', signed: 5 },
  { code: '27110', signed: 3 },
  { code: '27140', signed: 9 },
  { code: '27170', signed: 4 },
  { code: '27200', signed: 4 },
  { code: '27230', signed: 12 },
  { code: '27260', signed: 9 },
  { code: '27290', signed: 14 },
  { code: '27710', signed: 4 },
  { code: '28185', signed: 12 },
  { code: '28200', signed: 8 },
  { code: '28237', signed: 11 },
  { code: '28245', signed: 8 },
  { code: '30110', signed: 3 },
  { code: '30140', signed: 6 },
  { code: '30170', signed: 11 },
  { code: '30200', signed: 10 },
  { code: '30230', signed: 3 },
  { code: '31110', signed: 4 },
  { code: '31140', signed: 6 },
  { code: '31170', signed: 1 },
  { code: '31200', signed: 8 },
  { code: '31710', signed: 3 },
  { code: '36110', signed: 9 },
  { code: '41111', signed: 5 },
  { code: '41113', signed: 6 },
  { code: '41115', signed: 2 },
  { code: '41117', signed: 10 },
  { code: '41131', signed: 3 },
  { code: '41133', signed: 2 },
  { code: '41135', signed: 19 },
  { code: '41150', signed: 8 },
  { code: '41171', signed: 4 },
  { code: '41173', signed: 11 },
  { code: '41192', signed: 11 },
  { code: '41194', signed: 4 },
  { code: '41196', signed: 2 },
  { code: '41210', signed: 6 },
  { code: '41220', signed: 22 },
  { code: '41271', signed: 5 },
  { code: '41273', signed: 2 },
  { code: '41281', signed: 7 },
  { code: '41285', signed: 5 },
  { code: '41287', signed: 9 },
  { code: '41290', signed: 3 },
  { code: '41310', signed: 1 },
  { code: '41360', signed: 22 },
  { code: '41370', signed: 8 },
  { code: '41390', signed: 8 },
  { code: '41410', signed: 8 },
  { code: '41430', signed: 2 },
  { code: '41450', signed: 14 },
  { code: '41461', signed: 6 },
  { code: '41463', signed: 12 },
  { code: '41465', signed: 15 },
  { code: '41480', signed: 12 },
  { code: '41500', signed: 5 },
  { code: '41550', signed: 4 },
  { code: '41570', signed: 8 },
  { code: '41610', signed: 5 },
  { code: '41630', signed: 5 },
  { code: '41650', signed: 1 },
  { code: '41670', signed: 3 },
  { code: '41820', signed: 2 },
  { code: '41830', signed: 1 },
  { code: '43111', signed: 3 },
  { code: '43113', signed: 6 },
  { code: '43130', signed: 3 },
  { code: '43745', signed: 1 },
  { code: '43750', signed: 2 },
  { code: '43770', signed: 4 },
  { code: '44131', signed: 8 },
  { code: '44133', signed: 10 },
  { code: '44150', signed: 1 },
  { code: '44180', signed: 1 },
  { code: '44200', signed: 4 },
  { code: '44210', signed: 7 },
  { code: '44250', signed: 1 },
  { code: '44270', signed: 3 },
  { code: '44800', signed: 4 },
  { code: '47111', signed: 1 },
  { code: '47113', signed: 6 },
  { code: '47130', signed: 5 },
  { code: '47150', signed: 2 },
  { code: '47170', signed: 1 },
  { code: '47190', signed: 8 },
  { code: '47210', signed: 1 },
  { code: '47280', signed: 1 },
  { code: '47290', signed: 4 },
  { code: '47770', signed: 1 },
  { code: '47900', signed: 2 },
  { code: '48121', signed: 1 },
  { code: '48123', signed: 4 },
  { code: '48125', signed: 6 },
  { code: '48127', signed: 4 },
  { code: '48129', signed: 5 },
  { code: '48170', signed: 7 },
  { code: '48220', signed: 5 },
  { code: '48240', signed: 2 },
  { code: '48250', signed: 11 },
  { code: '48270', signed: 1 },
  { code: '48310', signed: 7 },
  { code: '48330', signed: 12 },
  { code: '48730', signed: 1 },
  { code: '48870', signed: 1 },
  { code: '48880', signed: 1 },
  { code: '48890', signed: 1 },
  { code: '50110', signed: 5 },
  { code: '50130', signed: 1 },
  { code: '51110', signed: 4 },
  { code: '51130', signed: 5 },
  { code: '51150', signed: 3 },
  { code: '51170', signed: 4 },
  { code: '51210', signed: 5 },
  { code: '51230', signed: 1 },
  { code: '51770', signed: 2 },
  { code: '51810', signed: 1 },
  { code: '51830', signed: 1 },
  { code: '52111', signed: 7 },
  { code: '52113', signed: 7 },
  { code: '52130', signed: 3 },
  { code: '52140', signed: 10 },
  { code: '52180', signed: 1 },
  { code: '52190', signed: 1 },
  { code: '52210', signed: 2 },
  { code: '52710', signed: 2 },
]

export type Cohort = {
  /** Onboarding quarter, e.g. 2024Q2. */
  readonly period: string
  /** Its index in the window's quarters, 0 first. */
  readonly index: number
  readonly size: number
  /** Share still billing at the end of each following quarter. */
  readonly kept: readonly number[]
  /** Subscription revenue against the cohort's own first quarter. */
  readonly value: readonly number[]
}

/**
 * Finding 2's other half. `value` can exceed 100 while `kept` falls —
 * that is expansion inside the survivors paying for the ones who left, and
 * it is the number a single MRR line cannot show.
 *
 * Quarterly, not monthly. Thirty-six monthly cohorts of about twenty-five
 * accounts each gave curves that stepped four points whenever one complex
 * left — a staircase read as a trend — and two grids of them came to 1,433
 * marks, which put this route at 264% of its markup budget. Twelve quarters
 * of about seventy-five fix both.
 *
 * Cohorts smaller than 8 complexes are still not published.
 */
export const BI_COHORTS: readonly Cohort[] = [
  { period: '2023Q3', index: 0, size: 60, kept: [100,95,88.3,85,83.3,81.7,80,78.3,78.3,78.3,76.7,70], value: [100,97.2,94.8,94.6,100.3,99.3,99.5,101.8,110.3,110.3,105.6,101.4] },
  { period: '2023Q4', index: 1, size: 55, kept: [100,94.5,85.5,80,74.5,72.7,70.9,67.3,65.5,65.5,63.6], value: [100,89.4,76,74.1,66.4,67.9,70.9,67.3,62.7,66.6,68] },
  { period: '2024Q1', index: 2, size: 57, kept: [98.2,86,84.2,84.2,84.2,82.5,80.7,73.7,71.9,68.4], value: [100,89.1,87.2,90.9,92.2,97.2,95.5,81.5,83.1,83.1] },
  { period: '2024Q2', index: 3, size: 54, kept: [94.4,87,83.3,77.8,77.8,74.1,74.1,74.1,70.4], value: [100,93.3,90.8,90.1,109.6,87.9,88.1,94.7,91.5] },
  { period: '2024Q3', index: 4, size: 83, kept: [98.8,91.6,89.2,86.7,80.7,79.5,77.1,73.5], value: [100,91.6,92.7,92.3,88.8,90.9,90.7,91.2] },
  { period: '2024Q4', index: 5, size: 74, kept: [100,94.6,86.5,82.4,78.4,75.7,71.6], value: [100,94.3,85.8,69,67.7,66.8,66.5] },
  { period: '2025Q1', index: 6, size: 61, kept: [98.4,95.1,90.2,83.6,80.3,75.4], value: [100,96.5,94.1,91.9,94.8,94.7] },
  { period: '2025Q2', index: 7, size: 90, kept: [97.8,93.3,92.2,90,86.7], value: [100,94.7,96.8,96.2,96.5] },
  { period: '2025Q3', index: 8, size: 97, kept: [97.9,86.6,83.5,81.4], value: [100,89.8,89.2,89.1] },
  { period: '2025Q4', index: 9, size: 99, kept: [98,90.9,85.9], value: [100,93.1,82.5] },
  { period: '2026Q1', index: 10, size: 115, kept: [96.5,89.6], value: [100,97.1] },
  { period: '2026Q2', index: 11, size: 110, kept: [98.2], value: [100] },
]

export type Rep = {
  readonly id: string
  readonly team: string
  readonly region: string
  readonly rank: string
  /** Monthly new-and-expansion MRR target, KRW. */
  readonly quota: number
  /** Complexes billing in the final month. */
  readonly accounts: number
  /** New and expansion MRR closed across the window. */
  readonly closed: number
  /** The same, last twelve months. */
  readonly recent: number
  /** `recent` against twelve months of quota, as a percentage. */
  readonly attainment: number
}

/** 19 people, 7 teams, 4 regions. Ordinary shape, invented. */
export const BI_REPS: readonly Rep[] = [
  { id: 'capital-1-1', team: 'capital-1', region: 'capital', rank: 'lead', quota: 7600000, accounts: 60, closed: 19393724, recent: 6616962, attainment: 7.3 },
  { id: 'capital-1-2', team: 'capital-1', region: 'capital', rank: 'junior', quota: 3100000, accounts: 54, closed: 20164548, recent: 9399762, attainment: 25.3 },
  { id: 'capital-1-3', team: 'capital-1', region: 'capital', rank: 'senior', quota: 6200000, accounts: 73, closed: 21520744, recent: 9367430, attainment: 12.6 },
  { id: 'capital-2-1', team: 'capital-2', region: 'capital', rank: 'lead', quota: 7600000, accounts: 51, closed: 18414066, recent: 7132251, attainment: 7.8 },
  { id: 'capital-2-2', team: 'capital-2', region: 'capital', rank: 'junior', quota: 3100000, accounts: 82, closed: 25388934, recent: 10671676, attainment: 28.7 },
  { id: 'capital-2-3', team: 'capital-2', region: 'capital', rank: 'junior', quota: 3100000, accounts: 78, closed: 21902763, recent: 8663248, attainment: 23.3 },
  { id: 'capital-3-1', team: 'capital-3', region: 'capital', rank: 'lead', quota: 7600000, accounts: 70, closed: 25607487, recent: 9648886, attainment: 10.6 },
  { id: 'capital-3-2', team: 'capital-3', region: 'capital', rank: 'mid', quota: 4800000, accounts: 60, closed: 27338208, recent: 10519992, attainment: 18.3 },
  { id: 'yeongnam-1-1', team: 'yeongnam-1', region: 'yeongnam', rank: 'lead', quota: 7600000, accounts: 57, closed: 13102036, recent: 7754704, attainment: 8.5 },
  { id: 'yeongnam-1-2', team: 'yeongnam-1', region: 'yeongnam', rank: 'junior', quota: 3100000, accounts: 54, closed: 14644288, recent: 5691894, attainment: 15.3 },
  { id: 'yeongnam-2-1', team: 'yeongnam-2', region: 'yeongnam', rank: 'lead', quota: 7600000, accounts: 45, closed: 9695722, recent: 4828582, attainment: 5.3 },
  { id: 'yeongnam-2-2', team: 'yeongnam-2', region: 'yeongnam', rank: 'senior', quota: 6200000, accounts: 49, closed: 15767360, recent: 4883796, attainment: 6.6 },
  { id: 'yeongnam-2-3', team: 'yeongnam-2', region: 'yeongnam', rank: 'junior', quota: 3100000, accounts: 54, closed: 11759758, recent: 7227816, attainment: 19.4 },
  { id: 'chungho-1-1', team: 'chungho-1', region: 'chungho', rank: 'lead', quota: 7600000, accounts: 29, closed: 5300088, recent: 1580720, attainment: 1.7 },
  { id: 'chungho-1-2', team: 'chungho-1', region: 'chungho', rank: 'senior', quota: 6200000, accounts: 58, closed: 14739783, recent: 5101819, attainment: 6.9 },
  { id: 'chungho-1-3', team: 'chungho-1', region: 'chungho', rank: 'mid', quota: 4800000, accounts: 46, closed: 15181300, recent: 9174884, attainment: 15.9 },
  { id: 'gangje-1-1', team: 'gangje-1', region: 'gangje', rank: 'lead', quota: 7600000, accounts: 10, closed: 3163184, recent: 673360, attainment: 0.7 },
  { id: 'gangje-1-2', team: 'gangje-1', region: 'gangje', rank: 'mid', quota: 4800000, accounts: 12, closed: 2252500, recent: 1266860, attainment: 2.2 },
  { id: 'gangje-1-3', team: 'gangje-1', region: 'gangje', rank: 'mid', quota: 4800000, accounts: 10, closed: 3011404, recent: 2502504, attainment: 4.3 },
]

export const BI_REGIONS: readonly { readonly id: string; readonly sido: readonly string[] }[] = [
  { id: 'capital', sido: ["서울특별시","인천광역시","경기도"] },
  { id: 'yeongnam', sido: ["부산광역시","대구광역시","울산광역시","경상북도","경상남도"] },
  { id: 'chungho', sido: ["대전광역시","세종특별자치시","충청북도","충청남도","전북특별자치도","전남광주통합특별시"] },
  { id: 'gangje', sido: ["강원특별자치도","제주특별자치도"] },
]

/** What was generated, and how big it is on disk. */
export const BI_INTAKE = {
  customers: 1285,
  /** Of those, signed during the burn-in — their start date is off-window. */
  preWindow: 330,
  /** Window-born complexes in cohorts too small to publish a curve for. */
  cohortsDropped: 0,
  /** Quarters in the window. Cohorts are quarterly. */
  quarters: 12,
  /** Leads decided entirely inside the burn-in. */
  pipelineDropped: 1150,
  contracts: 3206,
  seriesRows: 21182,
  pipeline: 2512,
  reps: 19,
  teams: 7,
  seriesBytes: 1416452,
  contractsBytes: 261097,
  pipelineBytes: 185159,
  customersBytes: 53442,
} as const

/** Churn and seasonality parameters, published so the shape can be argued. */
export const BI_DYNAMICS = {
  churnBase: 0.009,
  churnSelfMultiplier: 2,
  churnSeason: {"01":2.2,"07":1.8},
  winbackRate: 0.08,
  arPhi: 0.6,
  arSigma: 0.18,
  season: {"vote":{"10":1.1,"11":2.6,"12":2.2,"01":0.7,"02":0.6,"03":0.6,"04":0.6,"05":0.6,"06":0.6,"07":0.6,"08":0.6,"09":0.7},"visitor":{"02":1.4,"09":1.4,"01":1.1,"08":1.1},"sms":{"02":1.25,"03":1.25,"08":1.2,"09":1.2}},
  cohortFloor: 8,
} as const
