/**
 * The invented half of the revenue dashboard.
 *
 * GENERATED by scripts/build-bi.mjs — do not hand-edit.
 *
 * NONE OF THIS IS REAL. The complexes it refers to are (lib/bi.roster.data.ts
 * — real names, real districts, real completion years, estimated household
 * counts) but no contract, price, invoice, cancellation or salesperson below
 * corresponds to anything that happened. What an apartment management app
 * charges is commercial information with no public form, so a dashboard on
 * this subject either invents its revenue or does not exist; this one invents
 * it, from seed 'goldibug/bi/2026-09', and every page that draws from this file has to
 * say so where a reader will see it.
 *
 * WHAT IS REAL IS THE DENOMINATOR. Penetration is
 * 988 contracted complexes out of 36,040 filed with
 * 국토교통부 — 2.74% — and against the
 * 18,888 large enough to have a management office,
 * 4.79%. Those two
 * differ by a factor of about two and the dashboard shows both, because the
 * first understates the product and the second hides how much of the country
 * it cannot reach.
 *
 * TWO FINDINGS ARE DESIGNED IN. They are not discoveries and the page says
 * so; they are here because a dashboard that cannot be read wrong cannot
 * demonstrate reading it right.
 *
 *   1  PER-HOUSEHOLD PRICE RUNS BACKWARDS TO PRICE PER COMPLEX. Two ordinary
 *      terms do it — a marginal volume discount above 1,000 households, and a
 *      50,000원 monthly floor. Held to one fixed bundle and walked up a
 *      size ladder (BI_RATE_CARD), the cheapest bundle costs
 *      500원 per household at 100 households and
 *      129.5원 at 6000. A revenue-by-tier bar chart and a
 *      revenue-per-household bar chart are the same data and give opposite
 *      instructions to a sales manager.
 *
 *      THIS IS ARGUED FROM THE RATE CARD, NOT FROM THE REALISED AVERAGES, and
 *      an earlier version of this file got that wrong. Averaging per-household
 *      revenue over a tier mixes the price structure with which services those
 *      complexes happen to hold; the largest tier has about
 *      20 accounts, and on one seed its average came out
 *      cleanly monotone while on the next it did not. The pattern was real and
 *      the evidence was a coincidence. BI_TIER_ECONOMICS still publishes the
 *      realised numbers, with the account count beside each one, and is meant
 *      to be read against the ladder rather than in place of it.
 *
 *   2  MRR RISES EVERY MONTH WHILE COHORTS DECAY. Total subscription MRR goes
 *      from 87,106,298원 to 319,689,358원 across 36 months
 *      without a single down month, and cumulative churn over the same window
 *      is 85,297,363원. New business covers
 *      it. The headline line cannot show that; MOVEMENT and COHORTS can.
 *
 * MRR IS SUBSCRIPTION ONLY. Usage — votes held, SMS fallbacks sent — is
 * reported separately and is 2.5%
 * of total billings. Folding it into MRR would make the movement identity
 * below unreconcilable and the growth rate a function of the holiday
 * calendar.
 *
 * SUBSCRIPTION IS A STEP FUNCTION and usage is not. A per-household fee times
 * a household count that does not change is the same number every month until
 * the contract changes; `pnpm check:bi` asserts it never drifts. Usage
 * carries an AR(1) with phi 0.6 and named seasonality only — resident
 * council elections in November and December, 명절 visitor traffic, moving
 * season SMS. Nothing seasonal was added that a cause could not be given for.
 *
 * Per-complex monthly rows are not here: 21,961 of them are
 * 1,429 KB under public/data/bi/series/, one file per
 * month. Contracts (3,219) and the pipeline
 * (2,512) are beside them.
 */

export type BillingModel = 'perHH' | 'perComplex' | 'perEvent' | 'perUse'

export type Service = {
  readonly id: string
  readonly model: BillingModel
  /** KRW. Per household per month, per complex per month, or per unit. */
  readonly price: number
  /** Households below which the service has nothing to do. */
  readonly minHouseholds?: number
  /** Completion year from which the service applies. */
  readonly minYear?: number
  /** Service that must already be held. A hard dependency. */
  readonly needs?: string
  /** One-off installation, as a range. */
  readonly setup?: readonly [number, number]
}

/** The window every series below covers, inclusive. */
export const BI_WINDOW = { from: '202309', to: '202608', months: 36 } as const
export const BI_MONTHS: readonly string[] = ["202309","202310","202311","202312","202401","202402","202403","202404","202405","202406","202407","202408","202409","202410","202411","202412","202501","202502","202503","202504","202505","202506","202507","202508","202509","202510","202511","202512","202601","202602","202603","202604","202605","202606","202607","202608"]

/** The seed. Rerunning build-bi.mjs with it reproduces every number here. */
export const BI_SEED = 'goldibug/bi/2026-09'

export const BI_SERVICES: readonly Service[] = [
  { id: 'parking', model: 'perHH', price: 480, minHouseholds: 100, setup: [1500000, 6000000] },
  { id: 'visitor', model: 'perHH', price: 110, needs: 'parking' },
  { id: 'access', model: 'perHH', price: 250, minHouseholds: 200, setup: [1000000, 4000000] },
  { id: 'cctv', model: 'perHH', price: 160, minHouseholds: 150, setup: [800000, 3000000] },
  { id: 'billing', model: 'perHH', price: 320 },
  { id: 'notice', model: 'perHH', price: 150 },
  { id: 'community', model: 'perComplex', price: 90000, minHouseholds: 300 },
  { id: 'defect', model: 'perComplex', price: 80000, minYear: 2021 },
  { id: 'locker', model: 'perComplex', price: 50000, minHouseholds: 150, setup: [400000, 1200000] },
  { id: 'vote', model: 'perEvent', price: 180000 },
  { id: 'sms', model: 'perUse', price: 15, needs: 'notice' },
]

/**
 * The volume discount, on marginal bands. The first 1,000 households of a
 * 3,000-household complex pay full rate.
 */
export const BI_VOLUME_BANDS: readonly { readonly upTo: number; readonly rate: number }[] = [
  { upTo: 1000, rate: 1 },
  { upTo: 2000, rate: 0.9 },
  { upTo: Infinity, rate: 0.82 },
]

/** Monthly floor across a complex's per-household services, in KRW. */
export const BI_MIN_MONTHLY = 50000

export type MovementRow = {
  readonly month: string
  /** Subscription MRR at the start of the month, in KRW. */
  readonly start: number
  readonly new: number
  readonly winback: number
  readonly expansion: number
  readonly contraction: number
  readonly churn: number
  readonly end: number
  /** Complexes billing anything this month. */
  readonly complexes: number
  /** Usage billings this month. NOT part of MRR. */
  readonly usage: number
}

/**
 * The movement waterfall. `end === start + new + winback + expansion -
 * contraction - churn` holds in all 60 rows, and `pnpm check:bi`
 * recomputes both sides from public/data/bi/series/ to prove it. A revenue
 * table whose movements do not reconcile is a revenue table with a bug
 * somewhere upstream of the chart, and it is the commonest way a real BI
 * dashboard reports a wrong number confidently.
 */
export const BI_MOVEMENT: readonly MovementRow[] = [
  { month: '202309', start: 86693938, new: 2282838, winback: 0, expansion: 461070, contraction: 0, churn: 2331548, end: 87106298, complexes: 299, usage: 2702040 },
  { month: '202310', start: 87106298, new: 3924990, winback: 200800, expansion: 669860, contraction: 0, churn: 50000, end: 91851948, complexes: 313, usage: 3938265 },
  { month: '202311', start: 91851948, new: 6900032, winback: 0, expansion: 942080, contraction: 0, churn: 771220, end: 98922840, complexes: 333, usage: 5598900 },
  { month: '202312', start: 98922840, new: 4413684, winback: 0, expansion: 1302288, contraction: 0, churn: 420940, end: 104217872, complexes: 352, usage: 5987220 },
  { month: '202401', start: 104217872, new: 2841500, winback: 99600, expansion: 1102330, contraction: 0, churn: 1657080, end: 106604222, complexes: 363, usage: 2399490 },
  { month: '202402', start: 106604222, new: 4844520, winback: 0, expansion: 1025130, contraction: 0, churn: 610160, end: 111863712, complexes: 377, usage: 840450 },
  { month: '202403', start: 111863712, new: 4964912, winback: 0, expansion: 2416420, contraction: 0, churn: 1074480, end: 118170564, complexes: 386, usage: 1072995 },
  { month: '202404', start: 118170564, new: 4602612, winback: 0, expansion: 687560, contraction: 0, churn: 3096766, end: 120363970, complexes: 405, usage: 2302395 },
  { month: '202405', start: 120363970, new: 7090192, winback: 216720, expansion: 1016760, contraction: 0, churn: 1151120, end: 127536522, complexes: 426, usage: 1965435 },
  { month: '202406', start: 127536522, new: 4968638, winback: 163560, expansion: 1583346, contraction: 0, churn: 1550100, end: 132701966, complexes: 438, usage: 3064680 },
  { month: '202407', start: 132701966, new: 6158260, winback: 0, expansion: 1353940, contraction: 0, churn: 4010896, end: 136203270, complexes: 453, usage: 1623780 },
  { month: '202408', start: 136203270, new: 4676812, winback: 0, expansion: 817680, contraction: 0, churn: 666560, end: 141031202, complexes: 466, usage: 2059500 },
  { month: '202409', start: 141031202, new: 7420904, winback: 0, expansion: 616560, contraction: 0, churn: 2528280, end: 146540386, complexes: 483, usage: 3169830 },
  { month: '202410', start: 146540386, new: 12676022, winback: 0, expansion: 630980, contraction: 0, churn: 888660, end: 158958728, complexes: 520, usage: 5453910 },
  { month: '202411', start: 158958728, new: 5473367, winback: 0, expansion: 2071954, contraction: 0, churn: 2255100, end: 164248949, complexes: 534, usage: 10490460 },
  { month: '202412', start: 164248949, new: 8726090, winback: 0, expansion: 1641864, contraction: 0, churn: 1882708, end: 172734195, complexes: 546, usage: 10502625 },
  { month: '202501', start: 172734195, new: 6867694, winback: 798966, expansion: 1244980, contraction: 0, churn: 2541322, end: 179104513, complexes: 560, usage: 1868070 },
  { month: '202502', start: 179104513, new: 11854376, winback: 0, expansion: 746620, contraction: 0, churn: 4040940, end: 187664569, complexes: 577, usage: 4051530 },
  { month: '202503', start: 187664569, new: 6908310, winback: 0, expansion: 1255040, contraction: 0, churn: 907660, end: 194920259, complexes: 597, usage: 3338565 },
  { month: '202504', start: 194920259, new: 5831350, winback: 675840, expansion: 2575924, contraction: 0, churn: 1709570, end: 202293803, complexes: 618, usage: 4148850 },
  { month: '202505', start: 202293803, new: 5217640, winback: 0, expansion: 1342012, contraction: 0, churn: 3398773, end: 205454682, complexes: 638, usage: 3454830 },
  { month: '202506', start: 205454682, new: 6110380, winback: 50000, expansion: 2658598, contraction: 0, churn: 1319040, end: 212954620, complexes: 662, usage: 3638520 },
  { month: '202507', start: 212954620, new: 9090066, winback: 0, expansion: 1129680, contraction: 0, churn: 8048138, end: 215126228, complexes: 682, usage: 3263730 },
  { month: '202508', start: 215126228, new: 7484768, winback: 0, expansion: 1109028, contraction: 0, churn: 380800, end: 223339224, complexes: 704, usage: 3610200 },
  { month: '202509', start: 223339224, new: 11762857, winback: 0, expansion: 1665152, contraction: 0, churn: 6330592, end: 230436641, complexes: 726, usage: 4302360 },
  { month: '202510', start: 230436641, new: 7096596, winback: 50000, expansion: 1462240, contraction: 0, churn: 1136340, end: 237909137, complexes: 747, usage: 6391665 },
  { month: '202511', start: 237909137, new: 8240436, winback: 0, expansion: 632304, contraction: 0, churn: 2545444, end: 244236433, complexes: 772, usage: 16563015 },
  { month: '202512', start: 244236433, new: 7041007, winback: 0, expansion: 2435696, contraction: 0, churn: 1019394, end: 252693742, complexes: 799, usage: 12404070 },
  { month: '202601', start: 252693742, new: 7335514, winback: 0, expansion: 1880888, contraction: 0, churn: 6484879, end: 255425265, complexes: 808, usage: 4129905 },
  { month: '202602', start: 255425265, new: 8294439, winback: 236080, expansion: 2060846, contraction: 0, churn: 2059200, end: 263957430, complexes: 836, usage: 4290135 },
  { month: '202603', start: 263957430, new: 9704941, winback: 0, expansion: 2878232, contraction: 0, churn: 3061330, end: 273479273, complexes: 856, usage: 5755740 },
  { month: '202604', start: 273479273, new: 8714514, winback: 564800, expansion: 3123090, contraction: 0, churn: 3369320, end: 282512357, complexes: 883, usage: 7248195 },
  { month: '202605', start: 282512357, new: 16329626, winback: 0, expansion: 1804200, contraction: 0, churn: 2831460, end: 297814723, complexes: 915, usage: 6012570 },
  { month: '202606', start: 297814723, new: 7719440, winback: 0, expansion: 2505768, contraction: 0, churn: 1967440, end: 306072491, complexes: 939, usage: 4921695 },
  { month: '202607', start: 306072491, new: 9089976, winback: 92160, expansion: 2521970, contraction: 0, churn: 4221380, end: 313555217, complexes: 960, usage: 4971375 },
  { month: '202608', start: 313555217, new: 7218360, winback: 0, expansion: 1894504, contraction: 0, churn: 2978723, end: 319689358, complexes: 988, usage: 6753855 },
]

export type AdoptionRow = {
  readonly month: string
  readonly complexes: number
  /** Of those, at or above the addressable household floor. */
  readonly addressable: number
  /** Households under contract. */
  readonly households: number
  readonly byTier: Readonly<Record<string, number>>
  readonly bySido: Readonly<Record<string, number>>
}

/**
 * Penetration over time. The numerators are invented; every denominator
 * below is counted from the filings.
 */
export const BI_ADOPTION: readonly AdoptionRow[] = [
  { month: '202309', complexes: 299, addressable: 278, households: 170752, byTier: {"sub":21,"small":111,"mid":125,"large":36,"xlarge":6}, bySido: {"인천광역시":14,"충청북도":8,"경상남도":17,"서울특별시":53,"경기도":94,"충청남도":14,"부산광역시":26,"울산광역시":9,"전북특별자치도":8,"대구광역시":16,"대전광역시":15,"경상북도":12,"강원특별자치도":7,"세종특별자치시":6} },
  { month: '202310', complexes: 313, addressable: 290, households: 178528, byTier: {"sub":23,"small":114,"mid":133,"large":36,"xlarge":7}, bySido: {"인천광역시":15,"경기도":100,"충청북도":8,"경상남도":19,"부산광역시":27,"서울특별시":55,"충청남도":14,"울산광역시":9,"전북특별자치도":8,"대구광역시":16,"대전광역시":16,"경상북도":13,"강원특별자치도":7,"세종특별자치시":6} },
  { month: '202311', complexes: 333, addressable: 309, households: 191374, byTier: {"sub":24,"small":119,"mid":142,"large":41,"xlarge":7}, bySido: {"인천광역시":15,"경기도":107,"충청북도":8,"경상남도":22,"부산광역시":30,"서울특별시":60,"충청남도":14,"대구광역시":18,"울산광역시":10,"전북특별자치도":8,"대전광역시":16,"경상북도":12,"강원특별자치도":7,"세종특별자치시":6} },
  { month: '202312', complexes: 352, addressable: 326, households: 202614, byTier: {"sub":26,"small":126,"mid":149,"large":44,"xlarge":7}, bySido: {"인천광역시":15,"경기도":112,"충청북도":8,"경상남도":23,"서울특별시":68,"부산광역시":31,"충청남도":15,"제주특별자치도":1,"대구광역시":19,"울산광역시":11,"전북특별자치도":8,"대전광역시":16,"경상북도":12,"강원특별자치도":7,"세종특별자치시":6} },
  { month: '202401', complexes: 363, addressable: 335, households: 208916, byTier: {"sub":28,"small":130,"mid":151,"large":47,"xlarge":7}, bySido: {"인천광역시":15,"경기도":115,"충청북도":8,"경상남도":23,"서울특별시":71,"부산광역시":33,"경상북도":12,"충청남도":15,"제주특별자치도":1,"대구광역시":19,"울산광역시":12,"전북특별자치도":8,"강원특별자치도":9,"대전광역시":16,"세종특별자치시":6} },
  { month: '202402', complexes: 377, addressable: 348, households: 219810, byTier: {"sub":29,"small":134,"mid":157,"large":49,"xlarge":8}, bySido: {"인천광역시":17,"경기도":121,"충청북도":8,"경상남도":24,"서울특별시":73,"부산광역시":34,"경상북도":13,"충청남도":16,"제주특별자치도":1,"대구광역시":19,"울산광역시":11,"전북특별자치도":8,"강원특별자치도":9,"대전광역시":16,"세종특별자치시":7} },
  { month: '202403', complexes: 386, addressable: 356, households: 224636, byTier: {"sub":30,"small":137,"mid":161,"large":49,"xlarge":9}, bySido: {"인천광역시":19,"경기도":125,"충청북도":8,"경상남도":25,"서울특별시":75,"부산광역시":32,"경상북도":13,"충청남도":17,"제주특별자치도":1,"대구광역시":19,"울산광역시":12,"전북특별자치도":7,"강원특별자치도":9,"대전광역시":16,"세종특별자치시":8} },
  { month: '202404', complexes: 405, addressable: 369, households: 229514, byTier: {"sub":36,"small":146,"mid":166,"large":48,"xlarge":9}, bySido: {"인천광역시":21,"경기도":131,"충청북도":8,"전북특별자치도":9,"경상남도":27,"서울특별시":75,"부산광역시":33,"제주특별자치도":3,"경상북도":15,"충청남도":17,"대구광역시":20,"울산광역시":12,"강원특별자치도":9,"대전광역시":17,"세종특별자치시":8} },
  { month: '202405', complexes: 426, addressable: 389, households: 244394, byTier: {"sub":37,"small":150,"mid":178,"large":51,"xlarge":10}, bySido: {"경상남도":32,"인천광역시":22,"경기도":138,"충청북도":9,"전북특별자치도":10,"서울특별시":76,"부산광역시":34,"제주특별자치도":3,"경상북도":16,"충청남도":16,"대구광역시":22,"울산광역시":13,"강원특별자치도":9,"대전광역시":18,"세종특별자치시":8} },
  { month: '202406', complexes: 438, addressable: 401, households: 252704, byTier: {"sub":37,"small":155,"mid":183,"large":52,"xlarge":11}, bySido: {"경상남도":31,"인천광역시":22,"경기도":140,"충청북도":9,"전북특별자치도":12,"서울특별시":79,"부산광역시":36,"제주특별자치도":3,"경상북도":18,"충청남도":15,"대구광역시":23,"울산광역시":13,"강원특별자치도":11,"대전광역시":19,"세종특별자치시":7} },
  { month: '202407', complexes: 453, addressable: 415, households: 258898, byTier: {"sub":38,"small":162,"mid":193,"large":49,"xlarge":11}, bySido: {"경상남도":33,"인천광역시":20,"경기도":150,"충청북도":9,"전북특별자치도":12,"서울특별시":78,"부산광역시":36,"제주특별자치도":3,"경상북도":17,"충청남도":16,"대구광역시":24,"울산광역시":15,"강원특별자치도":13,"대전광역시":19,"세종특별자치시":8} },
  { month: '202408', complexes: 466, addressable: 428, households: 269030, byTier: {"sub":38,"small":168,"mid":195,"large":54,"xlarge":11}, bySido: {"경상남도":34,"인천광역시":21,"경기도":153,"충청북도":10,"전북특별자치도":13,"서울특별시":79,"부산광역시":39,"제주특별자치도":3,"경상북도":17,"충청남도":16,"대구광역시":25,"울산광역시":15,"강원특별자치도":13,"대전광역시":20,"세종특별자치시":8} },
  { month: '202409', complexes: 483, addressable: 443, households: 279738, byTier: {"sub":40,"small":173,"mid":201,"large":58,"xlarge":11}, bySido: {"경상남도":33,"인천광역시":22,"경기도":165,"충청북도":10,"전북특별자치도":15,"서울특별시":78,"부산광역시":41,"제주특별자치도":3,"경상북도":16,"충청남도":17,"대구광역시":27,"울산광역시":15,"강원특별자치도":13,"대전광역시":20,"세종특별자치시":8} },
  { month: '202410', complexes: 520, addressable: 477, households: 305528, byTier: {"sub":43,"small":188,"mid":210,"large":67,"xlarge":12}, bySido: {"경상남도":34,"인천광역시":22,"경기도":170,"충청북도":11,"전북특별자치도":16,"서울특별시":90,"부산광역시":46,"제주특별자치도":3,"경상북도":19,"충청남도":20,"대구광역시":30,"울산광역시":16,"강원특별자치도":13,"대전광역시":22,"세종특별자치시":8} },
  { month: '202411', complexes: 534, addressable: 488, households: 314554, byTier: {"sub":46,"small":194,"mid":211,"large":70,"xlarge":13}, bySido: {"서울특별시":96,"경상남도":35,"인천광역시":22,"경기도":176,"충청북도":11,"전북특별자치도":15,"부산광역시":46,"제주특별자치도":3,"경상북도":20,"충청남도":20,"대구광역시":30,"울산광역시":17,"강원특별자치도":13,"대전광역시":22,"세종특별자치시":8} },
  { month: '202412', complexes: 546, addressable: 501, households: 329724, byTier: {"sub":45,"small":199,"mid":211,"large":76,"xlarge":15}, bySido: {"서울특별시":100,"경상남도":35,"인천광역시":24,"경기도":176,"충청북도":10,"전북특별자치도":15,"부산광역시":50,"제주특별자치도":3,"경상북도":20,"충청남도":20,"대구광역시":33,"울산광역시":17,"강원특별자치도":13,"대전광역시":22,"세종특별자치시":8} },
  { month: '202501', complexes: 560, addressable: 513, households: 339254, byTier: {"sub":47,"small":201,"mid":217,"large":80,"xlarge":15}, bySido: {"서울특별시":103,"경상남도":37,"인천광역시":24,"경기도":179,"충청북도":10,"전북특별자치도":14,"부산광역시":53,"울산광역시":21,"제주특별자치도":3,"경상북도":20,"충청남도":22,"대구광역시":32,"강원특별자치도":13,"대전광역시":21,"세종특별자치시":8} },
  { month: '202502', complexes: 577, addressable: 529, households: 356500, byTier: {"sub":48,"small":208,"mid":219,"large":85,"xlarge":17}, bySido: {"서울특별시":105,"경상남도":38,"인천광역시":25,"경기도":187,"충청북도":10,"전북특별자치도":15,"부산광역시":54,"울산광역시":21,"제주특별자치도":3,"경상북도":21,"충청남도":21,"대구광역시":33,"강원특별자치도":13,"대전광역시":22,"세종특별자치시":9} },
  { month: '202503', complexes: 597, addressable: 548, households: 367982, byTier: {"sub":49,"small":218,"mid":224,"large":89,"xlarge":17}, bySido: {"서울특별시":109,"경상남도":39,"인천광역시":26,"경기도":196,"충청북도":12,"전북특별자치도":15,"부산광역시":56,"울산광역시":22,"제주특별자치도":3,"경상북도":21,"충청남도":21,"대구광역시":33,"강원특별자치도":14,"대전광역시":22,"세종특별자치시":8} },
  { month: '202504', complexes: 618, addressable: 569, households: 378710, byTier: {"sub":49,"small":227,"mid":234,"large":92,"xlarge":16}, bySido: {"서울특별시":115,"경상남도":43,"인천광역시":26,"경기도":198,"충청북도":12,"전북특별자치도":14,"부산광역시":58,"울산광역시":22,"제주특별자치도":3,"경상북도":23,"충청남도":22,"대구광역시":34,"강원특별자치도":15,"대전광역시":25,"세종특별자치시":8} },
  { month: '202505', complexes: 638, addressable: 587, households: 385708, byTier: {"sub":51,"small":238,"mid":241,"large":92,"xlarge":16}, bySido: {"서울특별시":121,"경상남도":44,"인천광역시":26,"경기도":204,"충청북도":12,"전북특별자치도":15,"부산광역시":59,"울산광역시":21,"제주특별자치도":3,"경상북도":23,"충청남도":23,"대구광역시":37,"강원특별자치도":15,"대전광역시":27,"세종특별자치시":8} },
  { month: '202506', complexes: 662, addressable: 610, households: 398260, byTier: {"sub":52,"small":248,"mid":252,"large":94,"xlarge":16}, bySido: {"서울특별시":125,"대전광역시":29,"경상남도":45,"인천광역시":26,"경기도":216,"충청북도":11,"전북특별자치도":15,"부산광역시":61,"울산광역시":21,"제주특별자치도":3,"경상북도":24,"충청남도":26,"대구광역시":37,"강원특별자치도":15,"세종특별자치시":8} },
  { month: '202507', complexes: 682, addressable: 625, households: 404006, byTier: {"sub":57,"small":258,"mid":257,"large":94,"xlarge":16}, bySido: {"인천광역시":26,"서울특별시":126,"대전광역시":29,"경상남도":50,"경기도":218,"충청북도":13,"전북특별자치도":16,"부산광역시":66,"울산광역시":21,"제주특별자치도":3,"강원특별자치도":16,"경상북도":23,"충청남도":27,"대구광역시":40,"세종특별자치시":8} },
  { month: '202508', complexes: 704, addressable: 647, households: 418172, byTier: {"sub":57,"small":264,"mid":270,"large":97,"xlarge":16}, bySido: {"인천광역시":28,"서울특별시":132,"대전광역시":29,"경상남도":53,"경기도":227,"충청북도":14,"전북특별자치도":16,"부산광역시":65,"울산광역시":21,"제주특별자치도":3,"강원특별자치도":17,"경상북도":25,"충청남도":26,"대구광역시":40,"세종특별자치시":8} },
  { month: '202509', complexes: 726, addressable: 670, households: 432846, byTier: {"sub":56,"small":268,"mid":284,"large":101,"xlarge":17}, bySido: {"인천광역시":31,"서울특별시":133,"대전광역시":30,"경상남도":54,"경기도":237,"충청북도":17,"전북특별자치도":16,"부산광역시":66,"울산광역시":22,"제주특별자치도":3,"강원특별자치도":17,"경상북도":24,"충청남도":25,"대구광역시":42,"세종특별자치시":9} },
  { month: '202510', complexes: 747, addressable: 687, households: 444166, byTier: {"sub":60,"small":271,"mid":296,"large":103,"xlarge":17}, bySido: {"인천광역시":32,"서울특별시":138,"대전광역시":31,"경상남도":54,"경기도":248,"충청북도":16,"전북특별자치도":16,"부산광역시":68,"울산광역시":21,"제주특별자치도":3,"강원특별자치도":19,"대구광역시":43,"경상북도":24,"충청남도":25,"세종특별자치시":9} },
  { month: '202511', complexes: 772, addressable: 709, households: 456218, byTier: {"sub":63,"small":285,"mid":301,"large":105,"xlarge":18}, bySido: {"인천광역시":33,"서울특별시":143,"대전광역시":31,"경상남도":56,"경기도":259,"충청북도":16,"전북특별자치도":16,"부산광역시":71,"울산광역시":19,"제주특별자치도":4,"강원특별자치도":19,"대구광역시":45,"경상북도":25,"충청남도":26,"세종특별자치시":9} },
  { month: '202512', complexes: 799, addressable: 735, households: 469078, byTier: {"sub":64,"small":296,"mid":315,"large":106,"xlarge":18}, bySido: {"인천광역시":36,"서울특별시":144,"대전광역시":32,"경상남도":58,"경기도":267,"충청북도":19,"전북특별자치도":16,"부산광역시":73,"울산광역시":19,"제주특별자치도":5,"강원특별자치도":21,"대구광역시":46,"경상북도":26,"충청남도":27,"세종특별자치시":10} },
  { month: '202601', complexes: 808, addressable: 739, households: 469432, byTier: {"sub":69,"small":302,"mid":314,"large":106,"xlarge":17}, bySido: {"인천광역시":38,"서울특별시":145,"대전광역시":33,"경상남도":58,"경기도":272,"충청북도":18,"전북특별자치도":16,"부산광역시":73,"울산광역시":19,"제주특별자치도":5,"강원특별자치도":21,"대구광역시":48,"경상북도":26,"충청남도":28,"세종특별자치시":8} },
  { month: '202602', complexes: 836, addressable: 766, households: 487428, byTier: {"sub":70,"small":320,"mid":318,"large":110,"xlarge":18}, bySido: {"인천광역시":40,"서울특별시":151,"대전광역시":34,"경상남도":59,"경기도":279,"충청북도":18,"전북특별자치도":18,"부산광역시":78,"울산광역시":20,"제주특별자치도":5,"강원특별자치도":22,"대구광역시":48,"경상북도":27,"충청남도":28,"세종특별자치시":9} },
  { month: '202603', complexes: 856, addressable: 785, households: 502466, byTier: {"sub":71,"small":326,"mid":327,"large":112,"xlarge":20}, bySido: {"인천광역시":40,"서울특별시":158,"대전광역시":34,"경상남도":59,"경기도":290,"충청북도":18,"전북특별자치도":19,"부산광역시":79,"울산광역시":20,"제주특별자치도":5,"강원특별자치도":23,"대구광역시":48,"경상북도":27,"충청남도":27,"세종특별자치시":9} },
  { month: '202604', complexes: 883, addressable: 810, households: 516112, byTier: {"sub":73,"small":337,"mid":338,"large":115,"xlarge":20}, bySido: {"인천광역시":41,"서울특별시":164,"대전광역시":35,"경상남도":60,"경기도":295,"충청북도":19,"전북특별자치도":22,"부산광역시":82,"울산광역시":21,"제주특별자치도":5,"강원특별자치도":24,"대구광역시":48,"경상북도":28,"충청남도":29,"세종특별자치시":10} },
  { month: '202605', complexes: 915, addressable: 840, households: 539848, byTier: {"sub":75,"small":347,"mid":348,"large":124,"xlarge":21}, bySido: {"인천광역시":44,"서울특별시":169,"대전광역시":36,"경상남도":64,"경기도":305,"충청북도":19,"전북특별자치도":24,"부산광역시":83,"울산광역시":23,"제주특별자치도":5,"강원특별자치도":24,"대구광역시":49,"경상북도":31,"충청남도":30,"세종특별자치시":9} },
  { month: '202606', complexes: 939, addressable: 863, households: 551384, byTier: {"sub":76,"small":361,"mid":356,"large":125,"xlarge":21}, bySido: {"인천광역시":44,"서울특별시":176,"대전광역시":36,"경상남도":65,"경기도":314,"충청북도":21,"전북특별자치도":25,"부산광역시":85,"제주특별자치도":6,"강원특별자치도":23,"대구광역시":49,"울산광역시":22,"경상북도":34,"충청남도":31,"세종특별자치시":8} },
  { month: '202607', complexes: 960, addressable: 879, households: 562902, byTier: {"sub":81,"small":361,"mid":370,"large":127,"xlarge":21}, bySido: {"인천광역시":44,"서울특별시":184,"대전광역시":33,"경상남도":66,"경기도":320,"충청북도":21,"전북특별자치도":27,"부산광역시":87,"제주특별자치도":6,"강원특별자치도":24,"충청남도":32,"대구광역시":51,"울산광역시":22,"경상북도":35,"세종특별자치시":8} },
  { month: '202608', complexes: 988, addressable: 905, households: 577346, byTier: {"sub":83,"small":371,"mid":382,"large":132,"xlarge":20}, bySido: {"인천광역시":43,"서울특별시":189,"대전광역시":34,"경상남도":67,"경기도":326,"부산광역시":92,"충청북도":21,"전북특별자치도":30,"제주특별자치도":6,"강원특별자치도":24,"충청남도":35,"대구광역시":55,"울산광역시":22,"경상북도":36,"세종특별자치시":8} },
]

/** The market, counted. Denominators for everything in BI_ADOPTION. */
export const BI_TAM = {
  complexes: 36040,
  addressable: 18888,
  byTier: {"sub":17152,"small":13782,"mid":4300,"large":744,"xlarge":62},
  bySido: {"서울특별시":8242,"부산광역시":3775,"대구광역시":1777,"인천광역시":1156,"대전광역시":958,"울산광역시":1319,"세종특별자치시":242,"경기도":7546,"충청북도":919,"충청남도":1396,"경상북도":2304,"경상남도":2960,"제주특별자치도":845,"강원특별자치도":1234,"전북특별자치도":1367},
} as const

/**
 * Active contracts per service per month — the attach rate's numerator.
 * Divided by BI_ADOPTION's `complexes`, not by BI_TAM: this measures what
 * customers buy, not what the market has adopted.
 */
export const BI_ATTACH: Readonly<Record<string, readonly number[]>> = {
  parking: [134,139,143,153,152,157,166,178,188,193,198,204,211,226,236,243,246,248,257,266,269,279,291,298,306,322,330,340,346,355,368,381,396,416,425,433],
  visitor: [10,10,9,10,10,11,12,12,13,14,17,18,18,19,21,21,24,23,27,29,31,33,33,35,35,39,39,40,42,42,44,47,48,52,54,54],
  access: [40,45,49,50,54,58,60,63,66,70,72,73,70,73,78,78,81,84,87,96,101,105,115,119,122,123,127,131,134,139,141,145,154,160,159,165],
  cctv: [39,42,46,50,50,52,53,56,58,61,65,71,73,75,75,78,83,88,89,92,94,100,102,108,113,114,116,123,123,129,135,135,140,146,155,162],
  billing: [127,136,146,154,156,160,168,175,187,195,202,208,214,232,238,243,250,257,267,277,286,298,295,306,315,326,338,356,362,374,385,397,417,426,440,452],
  notice: [166,170,186,195,205,216,222,230,238,244,254,261,273,291,296,305,317,327,339,349,357,370,384,400,413,422,439,452,460,477,483,502,513,524,543,561],
  community: [40,40,40,42,44,45,46,47,52,53,57,59,64,68,67,70,71,70,75,76,79,82,83,87,91,97,99,103,105,107,110,112,115,117,117,121],
  defect: [11,11,11,12,12,14,14,14,14,16,17,18,21,23,23,24,25,25,25,26,26,27,27,29,29,29,31,30,31,34,35,37,37,38,39,40],
  locker: [55,56,64,65,70,73,73,75,81,86,85,87,92,100,108,114,116,118,127,130,139,144,149,157,164,167,168,178,175,179,186,196,205,214,218,227],
  vote: [54,56,60,67,72,73,77,82,85,86,88,89,92,99,101,103,107,112,113,115,115,119,124,130,136,140,147,154,153,161,169,179,182,191,193,202],
  sms: [10,12,15,16,16,17,19,22,24,27,27,28,28,31,32,34,35,38,40,41,41,42,42,45,46,48,50,52,55,57,60,61,67,72,76,78],
}

export type TierEconomics = {
  readonly tier: string
  readonly complexes: number
  readonly households: number
  /** Subscription plus usage, final month, KRW. */
  readonly revenue: number
  readonly perComplex: number
  readonly perHousehold: number
  /** Accounts where the monthly floor topped the bill up. */
  readonly floored: number
}

/**
 * Realised economics per size tier, final month.
 *
 * NOT the evidence for finding 1 — BI_RATE_CARD is. This is what the tiers
 * actually billed, which is the price structure times whatever bundle those
 * particular complexes hold, and `complexes` is published beside every row
 * because the top tiers are thin enough that their averages move on one
 * account changing its mind. Read against the ladder: a tier sitting above it
 * is buying more than the reference bundle, below it is buying less.
 */
export const BI_TIER_ECONOMICS: readonly TierEconomics[] = [
  { tier: 'sub', complexes: 83, households: 11064, revenue: 7454165, perComplex: 89809, perHousehold: 673.7, floored: 23 },
  { tier: 'small', complexes: 371, households: 116652, revenue: 69351980, perComplex: 186933, perHousehold: 594.5, floored: 36 },
  { tier: 'mid', complexes: 382, households: 231216, revenue: 134349105, perComplex: 351699, perHousehold: 581.1, floored: 0 },
  { tier: 'large', complexes: 132, households: 164716, revenue: 86988287, perComplex: 659002, perHousehold: 528.1, floored: 0 },
  { tier: 'xlarge', complexes: 20, households: 53698, revenue: 28299676, perComplex: 1414984, perHousehold: 527, floored: 0 },
]

export type RateCardRow = {
  readonly households: number
  /** Monthly subscription for this bundle at this size, KRW. */
  readonly monthly: number
  readonly perHousehold: number
  /** True where the monthly floor, not the rate card, set the price. */
  readonly floored: boolean
}

export type RateCardBundle = {
  readonly id: string
  readonly services: readonly string[]
  /** Sum of list prices per household, before discount and before floor. */
  readonly list: number
  readonly rows: readonly RateCardRow[]
}

/**
 * Finding 1, as arithmetic rather than as an average.
 *
 * The bundle is held fixed and only household count varies, so nothing here
 * depends on which complexes happened to sign or what they happened to buy.
 * Both ladders fall monotonically and build-bi.mjs refuses to write this file
 * if either one rises.
 *
 * `entry` shows the monthly floor: below about 330 households the floor sets
 * the price, so the effective per-household rate is
 * 3.3x list at
 * 100 households and reaches list only past
 * 400.
 * `core` shows the volume bands: flat to 1,000 households, then falling to
 * 820.2원 at
 * 6000.
 *
 * BI_TIER_ECONOMICS is read against this, not instead of it. Where a tier's
 * realised average departs from the ladder the cause is bundle mix — a
 * different finding, and one that needs its own sample size before it is
 * worth stating.
 */
export const BI_RATE_CARD: readonly RateCardBundle[] = [
  {
    id: 'entry', services: ["notice"], list: 150,
    rows: [
      { households: 100, monthly: 50000, perHousehold: 500, floored: true },
      { households: 150, monthly: 50000, perHousehold: 333.3, floored: true },
      { households: 300, monthly: 50000, perHousehold: 166.7, floored: true },
      { households: 400, monthly: 60000, perHousehold: 150, floored: false },
      { households: 600, monthly: 90000, perHousehold: 150, floored: false },
      { households: 900, monthly: 135000, perHousehold: 150, floored: false },
      { households: 1200, monthly: 177000, perHousehold: 147.5, floored: false },
      { households: 2000, monthly: 285000, perHousehold: 142.5, floored: false },
      { households: 4000, monthly: 531000, perHousehold: 132.8, floored: false },
      { households: 6000, monthly: 777000, perHousehold: 129.5, floored: false },
    ],
  },
  {
    id: 'core', services: ["notice","billing","parking"], list: 950,
    rows: [
      { households: 100, monthly: 95000, perHousehold: 950, floored: false },
      { households: 150, monthly: 142500, perHousehold: 950, floored: false },
      { households: 300, monthly: 285000, perHousehold: 950, floored: false },
      { households: 400, monthly: 380000, perHousehold: 950, floored: false },
      { households: 600, monthly: 570000, perHousehold: 950, floored: false },
      { households: 900, monthly: 855000, perHousehold: 950, floored: false },
      { households: 1200, monthly: 1121000, perHousehold: 934.2, floored: false },
      { households: 2000, monthly: 1805000, perHousehold: 902.5, floored: false },
      { households: 4000, monthly: 3363000, perHousehold: 840.8, floored: false },
      { households: 6000, monthly: 4921000, perHousehold: 820.2, floored: false },
    ],
  },
]

export type DistrictPenetration = {
  readonly code: string
  /** Complexes billing in the final month. */
  readonly signed: number
}

/**
 * Per-district contracted complexes, final month. The map's numerator.
 *
 * Only districts with at least one are listed; the rest are absent and the
 * map reads them as zero rather than as missing — a district with an
 * addressable market and no customers is a fact about the sales coverage, and
 * the hexagon has to show it. Districts with no addressable complexes at all
 * are a different class and get the neutral fill.
 *
 * The denominator is in lib/bi.roster.data.ts, counted from the filings.
 */
export const BI_DISTRICT_PENETRATION: readonly DistrictPenetration[] = [
  { code: '11110', signed: 2 },
  { code: '11140', signed: 3 },
  { code: '11170', signed: 4 },
  { code: '11200', signed: 8 },
  { code: '11215', signed: 6 },
  { code: '11230', signed: 3 },
  { code: '11260', signed: 9 },
  { code: '11290', signed: 8 },
  { code: '11305', signed: 2 },
  { code: '11320', signed: 5 },
  { code: '11350', signed: 13 },
  { code: '11380', signed: 5 },
  { code: '11410', signed: 6 },
  { code: '11440', signed: 7 },
  { code: '11470', signed: 4 },
  { code: '11500', signed: 5 },
  { code: '11530', signed: 8 },
  { code: '11545', signed: 3 },
  { code: '11560', signed: 17 },
  { code: '11590', signed: 8 },
  { code: '11620', signed: 5 },
  { code: '11650', signed: 16 },
  { code: '11680', signed: 20 },
  { code: '11710', signed: 10 },
  { code: '11740', signed: 12 },
  { code: '26140', signed: 4 },
  { code: '26170', signed: 1 },
  { code: '26200', signed: 1 },
  { code: '26230', signed: 10 },
  { code: '26260', signed: 10 },
  { code: '26290', signed: 7 },
  { code: '26320', signed: 7 },
  { code: '26350', signed: 13 },
  { code: '26380', signed: 6 },
  { code: '26410', signed: 4 },
  { code: '26440', signed: 6 },
  { code: '26470', signed: 8 },
  { code: '26500', signed: 5 },
  { code: '26530', signed: 5 },
  { code: '26710', signed: 5 },
  { code: '27110', signed: 2 },
  { code: '27140', signed: 10 },
  { code: '27170', signed: 4 },
  { code: '27200', signed: 5 },
  { code: '27230', signed: 9 },
  { code: '27260', signed: 8 },
  { code: '27290', signed: 11 },
  { code: '27710', signed: 6 },
  { code: '28185', signed: 13 },
  { code: '28200', signed: 10 },
  { code: '28237', signed: 10 },
  { code: '28245', signed: 10 },
  { code: '30110', signed: 5 },
  { code: '30140', signed: 6 },
  { code: '30170', signed: 10 },
  { code: '30200', signed: 10 },
  { code: '30230', signed: 3 },
  { code: '31110', signed: 3 },
  { code: '31140', signed: 6 },
  { code: '31200', signed: 9 },
  { code: '31710', signed: 4 },
  { code: '36110', signed: 8 },
  { code: '41111', signed: 3 },
  { code: '41113', signed: 7 },
  { code: '41115', signed: 2 },
  { code: '41117', signed: 8 },
  { code: '41131', signed: 6 },
  { code: '41133', signed: 4 },
  { code: '41135', signed: 15 },
  { code: '41150', signed: 10 },
  { code: '41171', signed: 5 },
  { code: '41173', signed: 15 },
  { code: '41192', signed: 7 },
  { code: '41194', signed: 5 },
  { code: '41196', signed: 1 },
  { code: '41210', signed: 10 },
  { code: '41220', signed: 25 },
  { code: '41250', signed: 1 },
  { code: '41271', signed: 5 },
  { code: '41273', signed: 1 },
  { code: '41281', signed: 11 },
  { code: '41285', signed: 4 },
  { code: '41287', signed: 14 },
  { code: '41290', signed: 4 },
  { code: '41310', signed: 2 },
  { code: '41360', signed: 26 },
  { code: '41370', signed: 9 },
  { code: '41390', signed: 10 },
  { code: '41410', signed: 7 },
  { code: '41430', signed: 3 },
  { code: '41450', signed: 14 },
  { code: '41461', signed: 4 },
  { code: '41463', signed: 12 },
  { code: '41465', signed: 19 },
  { code: '41480', signed: 16 },
  { code: '41500', signed: 8 },
  { code: '41550', signed: 4 },
  { code: '41570', signed: 10 },
  { code: '41610', signed: 5 },
  { code: '41630', signed: 8 },
  { code: '41670', signed: 3 },
  { code: '41820', signed: 3 },
  { code: '43111', signed: 3 },
  { code: '43113', signed: 5 },
  { code: '43130', signed: 3 },
  { code: '43750', signed: 5 },
  { code: '43770', signed: 5 },
  { code: '44131', signed: 6 },
  { code: '44133', signed: 9 },
  { code: '44150', signed: 1 },
  { code: '44200', signed: 7 },
  { code: '44210', signed: 4 },
  { code: '44250', signed: 1 },
  { code: '44270', signed: 4 },
  { code: '44800', signed: 3 },
  { code: '47111', signed: 1 },
  { code: '47113', signed: 6 },
  { code: '47130', signed: 9 },
  { code: '47150', signed: 2 },
  { code: '47170', signed: 2 },
  { code: '47190', signed: 8 },
  { code: '47210', signed: 1 },
  { code: '47290', signed: 5 },
  { code: '47900', signed: 2 },
  { code: '48121', signed: 1 },
  { code: '48123', signed: 4 },
  { code: '48125', signed: 6 },
  { code: '48127', signed: 3 },
  { code: '48129', signed: 4 },
  { code: '48170', signed: 4 },
  { code: '48220', signed: 3 },
  { code: '48240', signed: 4 },
  { code: '48250', signed: 14 },
  { code: '48270', signed: 2 },
  { code: '48310', signed: 7 },
  { code: '48330', signed: 14 },
  { code: '48870', signed: 1 },
  { code: '50110', signed: 6 },
  { code: '51110', signed: 6 },
  { code: '51130', signed: 5 },
  { code: '51150', signed: 2 },
  { code: '51170', signed: 4 },
  { code: '51210', signed: 3 },
  { code: '51230', signed: 1 },
  { code: '51770', signed: 1 },
  { code: '51820', signed: 1 },
  { code: '51830', signed: 1 },
  { code: '52111', signed: 7 },
  { code: '52113', signed: 9 },
  { code: '52130', signed: 4 },
  { code: '52140', signed: 7 },
  { code: '52210', signed: 2 },
  { code: '52710', signed: 1 },
]

export type Cohort = {
  /** Onboarding quarter, e.g. 2024Q2. */
  readonly period: string
  /** Its index in the window's quarters, 0 first. */
  readonly index: number
  readonly size: number
  /** Share still billing at the end of each following quarter. */
  readonly kept: readonly number[]
  /** Subscription revenue against the cohort's own first quarter. */
  readonly value: readonly number[]
}

/**
 * Finding 2's other half. `value` can exceed 100 while `kept` falls —
 * that is expansion inside the survivors paying for the ones who left, and
 * it is the number a single MRR line cannot show.
 *
 * Quarterly, not monthly. Thirty-six monthly cohorts of about twenty-five
 * accounts each gave curves that stepped four points whenever one complex
 * left — a staircase read as a trend — and two grids of them came to 1,433
 * marks, which put this route at 264% of its markup budget. Twelve quarters
 * of about seventy-five fix both.
 *
 * Cohorts smaller than 8 complexes are still not published.
 */
export const BI_COHORTS: readonly Cohort[] = [
  { period: '2023Q3', index: 0, size: 49, kept: [100,91.8,89.8,87.8,83.7,81.6,79.6,81.6,79.6,79.6,75.5,73.5], value: [100,95.4,101.2,103.8,108,107.4,105.9,111.6,118.4,119.7,114.9,114.5] },
  { period: '2023Q4', index: 1, size: 54, kept: [100,94.4,87,87,79.6,77.8,75.9,72.2,70.4,68.5,68.5], value: [100,93.3,84,85.1,80.3,79.9,83.8,80.2,81,83.6,86] },
  { period: '2024Q1', index: 2, size: 61, kept: [100,90.2,85.2,83.6,83.6,82,78.7,73.8,73.8,72.1], value: [100,91.8,89.1,91.9,92.5,94.5,92.3,81.7,83.4,84.3] },
  { period: '2024Q2', index: 3, size: 63, kept: [98.4,92.1,88.9,84.1,84.1,82.5,81,81,79.4], value: [100,93.3,91.6,91.7,100.5,98.1,100.5,107.5,107.2] },
  { period: '2024Q3', index: 4, size: 87, kept: [98.9,90.8,89.7,86.2,81.6,81.6,80.5,77], value: [100,92.3,96,91.6,88,90.5,90.5,91.7] },
  { period: '2024Q4', index: 5, size: 69, kept: [98.6,94.2,89.9,84.1,81.2,78.3,72.5], value: [100,91.4,85.6,69,69.8,68.8,68] },
  { period: '2025Q1', index: 6, size: 76, kept: [98.7,90.8,86.8,82.9,78.9,78.9], value: [100,91.3,89.3,89,96.1,100] },
  { period: '2025Q2', index: 7, size: 90, kept: [100,96.7,95.6,92.2,90], value: [100,95.2,98,99.2,101.5] },
  { period: '2025Q3', index: 8, size: 93, kept: [98.9,89.2,89.2,88.2], value: [100,90.9,92.3,93.2] },
  { period: '2025Q4', index: 9, size: 92, kept: [97.8,90.2,84.8], value: [100,93,81.6] },
  { period: '2026Q1', index: 10, size: 111, kept: [97.3,90.1], value: [100,97.5] },
  { period: '2026Q2', index: 11, size: 105, kept: [100], value: [100] },
]

export type Rep = {
  readonly id: string
  readonly team: string
  readonly region: string
  readonly rank: string
  /** Monthly new-and-expansion MRR target, KRW. */
  readonly quota: number
  /** Complexes billing in the final month. */
  readonly accounts: number
  /** New and expansion MRR closed across the window. */
  readonly closed: number
  /** The same, last twelve months. */
  readonly recent: number
  /** `recent` against twelve months of quota, as a percentage. */
  readonly attainment: number
}

/** 19 people, 7 teams, 4 regions. Ordinary shape, invented. */
export const BI_REPS: readonly Rep[] = [
  { id: 'capital-1-1', team: 'capital-1', region: 'capital', rank: 'lead', quota: 7600000, accounts: 55, closed: 19970268, recent: 6985082, attainment: 7.7 },
  { id: 'capital-1-2', team: 'capital-1', region: 'capital', rank: 'junior', quota: 3100000, accounts: 54, closed: 21863528, recent: 10553202, attainment: 28.4 },
  { id: 'capital-1-3', team: 'capital-1', region: 'capital', rank: 'senior', quota: 6200000, accounts: 84, closed: 23442044, recent: 10493550, attainment: 14.1 },
  { id: 'capital-2-1', team: 'capital-2', region: 'capital', rank: 'lead', quota: 7600000, accounts: 61, closed: 22071214, recent: 8668835, attainment: 9.5 },
  { id: 'capital-2-2', team: 'capital-2', region: 'capital', rank: 'junior', quota: 3100000, accounts: 81, closed: 27339744, recent: 12940046, attainment: 34.8 },
  { id: 'capital-2-3', team: 'capital-2', region: 'capital', rank: 'junior', quota: 3100000, accounts: 85, closed: 22755213, recent: 8632928, attainment: 23.2 },
  { id: 'capital-3-1', team: 'capital-3', region: 'capital', rank: 'lead', quota: 7600000, accounts: 71, closed: 25007215, recent: 9807866, attainment: 10.8 },
  { id: 'capital-3-2', team: 'capital-3', region: 'capital', rank: 'mid', quota: 4800000, accounts: 67, closed: 28622092, recent: 12183692, attainment: 21.2 },
  { id: 'yeongnam-1-1', team: 'yeongnam-1', region: 'yeongnam', rank: 'lead', quota: 7600000, accounts: 55, closed: 15268696, recent: 8088844, attainment: 8.9 },
  { id: 'yeongnam-1-2', team: 'yeongnam-1', region: 'yeongnam', rank: 'junior', quota: 3100000, accounts: 57, closed: 17398514, recent: 7358750, attainment: 19.8 },
  { id: 'yeongnam-2-1', team: 'yeongnam-2', region: 'yeongnam', rank: 'lead', quota: 7600000, accounts: 53, closed: 15078496, recent: 5172450, attainment: 5.7 },
  { id: 'yeongnam-2-2', team: 'yeongnam-2', region: 'yeongnam', rank: 'senior', quota: 6200000, accounts: 52, closed: 17580590, recent: 4556496, attainment: 6.1 },
  { id: 'yeongnam-2-3', team: 'yeongnam-2', region: 'yeongnam', rank: 'junior', quota: 3100000, accounts: 55, closed: 14960938, recent: 7327376, attainment: 19.7 },
  { id: 'chungho-1-1', team: 'chungho-1', region: 'chungho', rank: 'lead', quota: 7600000, accounts: 28, closed: 7426708, recent: 1682180, attainment: 1.8 },
  { id: 'chungho-1-2', team: 'chungho-1', region: 'chungho', rank: 'senior', quota: 6200000, accounts: 55, closed: 15643595, recent: 6993691, attainment: 9.4 },
  { id: 'chungho-1-3', team: 'chungho-1', region: 'chungho', rank: 'mid', quota: 4800000, accounts: 45, closed: 14940580, recent: 8579724, attainment: 14.9 },
  { id: 'gangje-1-1', team: 'gangje-1', region: 'gangje', rank: 'lead', quota: 7600000, accounts: 12, closed: 3298544, recent: 1247000, attainment: 1.4 },
  { id: 'gangje-1-2', team: 'gangje-1', region: 'gangje', rank: 'mid', quota: 4800000, accounts: 7, closed: 2263300, recent: 1063320, attainment: 1.8 },
  { id: 'gangje-1-3', team: 'gangje-1', region: 'gangje', rank: 'mid', quota: 4800000, accounts: 11, closed: 3361504, recent: 2020604, attainment: 3.5 },
]

export const BI_REGIONS: readonly { readonly id: string; readonly sido: readonly string[] }[] = [
  { id: 'capital', sido: ["서울특별시","인천광역시","경기도"] },
  { id: 'yeongnam', sido: ["부산광역시","대구광역시","울산광역시","경상북도","경상남도"] },
  { id: 'chungho', sido: ["대전광역시","세종특별자치시","충청북도","충청남도","전북특별자치도","전남광주통합특별시"] },
  { id: 'gangje', sido: ["강원특별자치도","제주특별자치도"] },
]

/** What was generated, and how big it is on disk. */
export const BI_INTAKE = {
  customers: 1285,
  /** Of those, signed during the burn-in — their start date is off-window. */
  preWindow: 335,
  /** Window-born complexes in cohorts too small to publish a curve for. */
  cohortsDropped: 0,
  /** Quarters in the window. Cohorts are quarterly. */
  quarters: 12,
  /** Leads decided entirely inside the burn-in. */
  pipelineDropped: 1150,
  contracts: 3219,
  seriesRows: 21961,
  pipeline: 2512,
  reps: 19,
  teams: 7,
  seriesBytes: 1462995,
  contractsBytes: 262507,
  pipelineBytes: 185133,
} as const

/** Churn and seasonality parameters, published so the shape can be argued. */
export const BI_DYNAMICS = {
  churnBase: 0.009,
  churnSelfMultiplier: 2,
  churnSeason: {"01":2.2,"07":1.8},
  winbackRate: 0.08,
  arPhi: 0.6,
  arSigma: 0.18,
  season: {"vote":{"10":1.1,"11":2.6,"12":2.2,"01":0.7,"02":0.6,"03":0.6,"04":0.6,"05":0.6,"06":0.6,"07":0.6,"08":0.6,"09":0.7},"visitor":{"02":1.4,"09":1.4,"01":1.1,"08":1.1},"sms":{"02":1.25,"03":1.25,"08":1.2,"09":1.2}},
  cohortFloor: 8,
} as const
