/**
 * The market this dashboard sells into. Real, and the only real layer.
 *
 * GENERATED by scripts/build-roster.mjs — do not hand-edit.
 *
 * 36,040 apartment complexes filed with 국토교통부, across 217 of
 * 245 districts and 3,181 법정동. Name, province, district,
 * 법정동 and completion year are as filed. Everything the revenue dashboard
 * puts on top of them — contracts, unit prices, revenue, churn and the sales
 * organisation — is generated by scripts/build-bi.mjs and is NOT real. This
 * file exists so that the one figure a synthetic dataset cannot fake has a
 * true denominator: penetration is contracted complexes over 36,040,
 * and that 36,040 was counted, not chosen.
 *
 * HOUSEHOLD COUNT IS NOT FILED and is therefore estimated in two halves that
 * are labelled differently because they claim different things.
 *
 * THE ORDER IS OBSERVED. Corrected top floor, filing volume and distinct
 * area bands combine into one score, whose weights are fitted by least
 * squares against the building counts that ARE filed — 13,027
 * complexes, R^2 0.508, Spearman 0.704. Spearman is the number
 * that matters and R^2 is published beside it on purpose: only the RANKING
 * reaches this file, so how much variance the fit explains is less
 * interesting than whether it puts the complexes in the right order. At
 * 0.704 it mostly does, and it does not pretend to more.
 *
 * THE SCALE IS PINNED, not shaped. Households are exp(a + b * score) with
 * the two parameters solved from two anchors rather than assumed: the total
 * comes to 42.0% of the registered residents of the covered
 * districts at 2.3 people per household, and the largest complex has
 * 6,000. Registered population is measured, not guessed — it is
 * lib/cartogram.districts.data.ts, 행정안전부 주민등록인구 2026-07-31, the same
 * 45,215,626 people the brokerage map divides by.
 *
 * AN EARLIER DRAFT ASSUMED A LOG-NORMAL and got this wrong by a factor of
 * four: median 640 with sigma 0.889 implied 33.8 million households, which is
 * 164% of the population of the districts holding them. It is recorded here
 * because the failure is instructive — the estimator was internally
 * consistent and nothing inside it could have noticed. Only a number from
 * outside could, which is why one is now load-bearing and why
 * `pnpm check:bi` asserts the realised share every build.
 *
 * 13,027 complexes carry `basis: 'checked'` — their building count was
 * filed often enough to validate the score against. The other
 * 23,013 are `'scored'`. Both are ranked by the same formula,
 * so the two are comparable; the flag records which ones the formula was
 * answerable to.
 *
 * 18,888 of 36,040 are ADDRESSABLE — at least 150
 * estimated households, the size below which a complex has no management
 * office to sell to. Penetration is reported against both, because a
 * denominator including complexes nobody could ever sign makes the sales
 * team look worse than it is, and one excluding them hides how much of the
 * country the product cannot reach.
 *
 * Per-complex rows are not here. 36,040 of them are 3,210 KB
 * of JSON under public/data/bi/roster/, one file per district, fetched when a
 * district is opened — the same arrangement public/data/umd uses and for the
 * same reason.
 */

export type RosterDistrict = {
  /** 법정동코드 5자리, the key the roster files are named by. */
  readonly code: string
  readonly sido: string
  readonly sgg: string
  /** 행정안전부 주민등록인구. Measured, and what the scale is pinned against. */
  readonly pop: number
  /** Complexes filed in this district. The market's denominator. */
  readonly complexes: number
  /** Of those, at or above ROSTER_ADDRESSABLE households. */
  readonly addressable: number
  /** Sum of estimated households. Estimated — see the note above. */
  readonly households: number
}

/** Household tiers, in households. The dashboard's size axis. */
export const ROSTER_TIERS = [
  { id: 'sub', to: 150 },
  { id: 'small', to: 400 },
  { id: 'mid', to: 900 },
  { id: 'large', to: 2000 },
  { id: 'xlarge', to: Infinity },
] as const

export type RosterTier = (typeof ROSTER_TIERS)[number]['id']

/** Households below which a complex has no management office to sell to. */
export const ROSTER_ADDRESSABLE = 150

/**
 * The declared half of the household estimate, published so it can be
 * rejected. `share` and `persons` pin the total against measured
 * population; `max` pins the ceiling. Nothing here was fitted — the filings
 * carry no household counts to fit against.
 */
export const ROSTER_SCALE = {
  /** Target share of covered registered residents. A decision. */
  share: 0.42,
  /** Persons per apartment household. A decision. */
  persons: 2.3,
  /** Households in the largest complex. A decision. */
  max: 6000,
  /** Floor, below which the estimate is not published as a count. */
  min: 24,
  /** What the solve actually produced, after clamping and rounding. */
  realisedShare: 0.4202,
  /** Registered residents of the 217 covered districts. Measured. */
  coveredPop: 45215626,
} as const

/** The observed half: how well three universal signals track filed buildings. */
export const ROSTER_FIT = {
  /** Complexes with enough filed building numbers to fit against. */
  holdout: 13027,
  r2: 0.508,
  spearman: 0.704,
} as const

/** What was read, and what was set aside doing it. */
export const ROSTER_INTAKE = {
  files: 5879,
  rows: 1421942,
  complexes: 36040,
  addressable: 18888,
  umd: 3181,
  districts: 245,
  covered: 217,
  /** Filings whose 법정동코드 is not one of the 245. */
  offGrid: 0,
  /** Filings with no complex name or no 법정동. */
  blank: 0,
  /** Complexes whose score was validated against filed building counts. */
  checked: 13027,
  bytes: 3287007,
} as const

/** Estimated households across the roster, at five points. */
export const ROSTER_HOUSEHOLDS = {
  total: 8259940,
  p10: 52,
  median: 158,
  p90: 478,
  max: 6000,
} as const

/** Completion years, as filed. */
export const ROSTER_YEARS = {
  known: 36040,
  min: 1961,
  median: 2003,
  max: 2026,
} as const

/** Complexes per tier. */
export const ROSTER_TIER_COUNTS: Readonly<Record<RosterTier, number>> = {
  sub: 17152,
  small: 13782,
  mid: 4300,
  large: 744,
  xlarge: 62,
} as const

/** One row per hexagon. Districts with no filed complexes keep their zero. */
export const ROSTER_DISTRICTS: readonly RosterDistrict[] = [
  { code: '51800', sido: '강원특별자치도', sgg: '양구군', pop: 20372, complexes: 8, addressable: 5, households: 1068 },
  { code: '41480', sido: '경기도', sgg: '파주시', pop: 534503, complexes: 228, addressable: 185, households: 86432 },
  { code: '41800', sido: '경기도', sgg: '연천군', pop: 43107, complexes: 30, addressable: 9, households: 4192 },
  { code: '41250', sido: '경기도', sgg: '동두천시', pop: 86186, complexes: 82, addressable: 48, households: 15670 },
  { code: '41650', sido: '경기도', sgg: '포천시', pop: 140454, complexes: 61, addressable: 41, households: 13530 },
  { code: '51780', sido: '강원특별자치도', sgg: '철원군', pop: 39665, complexes: 24, addressable: 8, households: 3584 },
  { code: '51820', sido: '강원특별자치도', sgg: '고성군', pop: 27190, complexes: 15, addressable: 9, households: 3252 },
  { code: '41281', sido: '경기도', sgg: '고양시덕양구', pop: 482849, complexes: 269, addressable: 193, households: 83046 },
  { code: '41630', sido: '경기도', sgg: '양주시', pop: 297352, complexes: 159, addressable: 136, households: 58556 },
  { code: '11320', sido: '서울특별시', sgg: '도봉구', pop: 298067, complexes: 191, addressable: 111, households: 40640 },
  { code: '41150', sido: '경기도', sgg: '의정부시', pop: 461879, complexes: 322, addressable: 269, households: 95766 },
  { code: '41820', sido: '경기도', sgg: '가평군', pop: 62048, complexes: 49, addressable: 17, households: 7568 },
  { code: '51790', sido: '강원특별자치도', sgg: '화천군', pop: 22773, complexes: 8, addressable: 1, households: 820 },
  { code: '51810', sido: '강원특별자치도', sgg: '인제군', pop: 30778, complexes: 19, addressable: 4, households: 1936 },
  { code: '28720', sido: '인천광역시', sgg: '옹진군', pop: 19327, complexes: 0, addressable: 0, households: 0 },
  { code: '41287', sido: '경기도', sgg: '고양시일산서구', pop: 276159, complexes: 165, addressable: 150, households: 58656 },
  { code: '41285', sido: '경기도', sgg: '고양시일산동구', pop: 298158, complexes: 114, addressable: 112, households: 45250 },
  { code: '11380', sido: '서울특별시', sgg: '은평구', pop: 453056, complexes: 470, addressable: 188, households: 81830 },
  { code: '11110', sido: '서울특별시', sgg: '종로구', pop: 136139, complexes: 134, addressable: 54, households: 20748 },
  { code: '11305', sido: '서울특별시', sgg: '강북구', pop: 277695, complexes: 142, addressable: 69, households: 27338 },
  { code: '11350', sido: '서울특별시', sgg: '노원구', pop: 480549, complexes: 328, addressable: 235, households: 96090 },
  { code: '41360', sido: '경기도', sgg: '남양주시', pop: 727373, complexes: 401, addressable: 338, households: 156224 },
  { code: '51110', sido: '강원특별자치도', sgg: '춘천시', pop: 284853, complexes: 161, addressable: 129, households: 43590 },
  { code: '51210', sido: '강원특별자치도', sgg: '속초시', pop: 78976, complexes: 92, addressable: 65, households: 22614 },
  { code: '28710', sido: '인천광역시', sgg: '강화군', pop: 69556, complexes: 18, addressable: 7, households: 2940 },
  { code: '41570', sido: '경기도', sgg: '김포시', pop: 483964, complexes: 208, addressable: 189, households: 80334 },
  { code: '11500', sido: '서울특별시', sgg: '강서구', pop: 548268, complexes: 631, addressable: 247, households: 107050 },
  { code: '11440', sido: '서울특별시', sgg: '마포구', pop: 356154, complexes: 335, addressable: 179, households: 78712 },
  { code: '11410', sido: '서울특별시', sgg: '서대문구', pop: 299531, complexes: 276, addressable: 115, households: 55362 },
  { code: '11290', sido: '서울특별시', sgg: '성북구', pop: 421289, complexes: 198, addressable: 136, households: 63384 },
  { code: '11230', sido: '서울특별시', sgg: '동대문구', pop: 353070, complexes: 330, addressable: 165, households: 77548 },
  { code: '11260', sido: '서울특별시', sgg: '중랑구', pop: 376282, complexes: 281, addressable: 150, households: 64524 },
  { code: '41310', sido: '경기도', sgg: '구리시', pop: 188040, complexes: 191, addressable: 92, households: 46126 },
  { code: '51720', sido: '강원특별자치도', sgg: '홍천군', pop: 65810, complexes: 41, addressable: 14, households: 5520 },
  { code: '51830', sido: '강원특별자치도', sgg: '양양군', pop: 27310, complexes: 27, addressable: 15, households: 4358 },
  { code: '28245', sido: '인천광역시', sgg: '계양구', pop: 276125, complexes: 218, addressable: 126, households: 46008 },
  { code: '11470', sido: '서울특별시', sgg: '양천구', pop: 420595, complexes: 443, addressable: 176, households: 80706 },
  { code: '11560', sido: '서울특별시', sgg: '영등포구', pop: 371691, complexes: 282, addressable: 226, households: 82018 },
  { code: '11140', sido: '서울특별시', sgg: '중구', pop: 117493, complexes: 131, addressable: 64, households: 27798 },
  { code: '11200', sido: '서울특별시', sgg: '성동구', pop: 274346, complexes: 184, addressable: 125, households: 59388 },
  { code: '11215', sido: '서울특별시', sgg: '광진구', pop: 330802, complexes: 233, addressable: 110, households: 46060 },
  { code: '11740', sido: '서울특별시', sgg: '강동구', pop: 498701, complexes: 502, addressable: 204, households: 106882 },
  { code: '41450', sido: '경기도', sgg: '하남시', pop: 327423, complexes: 136, addressable: 124, households: 66136 },
  { code: '51730', sido: '강원특별자치도', sgg: '횡성군', pop: 45521, complexes: 27, addressable: 12, households: 4142 },
  { code: '51150', sido: '강원특별자치도', sgg: '강릉시', pop: 205593, complexes: 231, addressable: 112, households: 39198 },
  { code: '51170', sido: '강원특별자치도', sgg: '동해시', pop: 85577, complexes: 115, addressable: 55, households: 20464 },
  { code: '47940', sido: '경상북도', sgg: '울릉군', pop: 8780, complexes: 1, addressable: 0, households: 68 },
  { code: '28237', sido: '인천광역시', sgg: '부평구', pop: 487661, complexes: 393, addressable: 176, households: 87326 },
  { code: '41196', sido: '경기도', sgg: '부천시오정구', pop: 148710, complexes: 248, addressable: 29, households: 25772 },
  { code: '11530', sido: '서울특별시', sgg: '구로구', pop: 382531, complexes: 500, addressable: 206, households: 89590 },
  { code: '11590', sido: '서울특별시', sgg: '동작구', pop: 371543, complexes: 228, addressable: 145, households: 59546 },
  { code: '11170', sido: '서울특별시', sgg: '용산구', pop: 199575, complexes: 227, addressable: 106, households: 49482 },
  { code: '11680', sido: '서울특별시', sgg: '강남구', pop: 552631, complexes: 666, addressable: 282, households: 141640 },
  { code: '11710', sido: '서울특별시', sgg: '송파구', pop: 649715, complexes: 426, addressable: 204, households: 109890 },
  { code: '41610', sido: '경기도', sgg: '광주시', pop: 400323, complexes: 146, addressable: 145, households: 47044 },
  { code: '41830', sido: '경기도', sgg: '양평군', pop: 126995, complexes: 57, addressable: 31, households: 11752 },
  { code: '51760', sido: '강원특별자치도', sgg: '평창군', pop: 39865, complexes: 46, addressable: 14, households: 5590 },
  { code: '51770', sido: '강원특별자치도', sgg: '정선군', pop: 35144, complexes: 33, addressable: 6, households: 3906 },
  { code: '41192', sido: '경기도', sgg: '부천시원미구', pop: 382134, complexes: 342, addressable: 152, households: 75466 },
  { code: '41210', sido: '경기도', sgg: '광명시', pop: 303726, complexes: 119, addressable: 89, households: 53438 },
  { code: '11545', sido: '서울특별시', sgg: '금천구', pop: 222421, complexes: 146, addressable: 61, households: 27636 },
  { code: '11620', sido: '서울특별시', sgg: '관악구', pop: 477503, complexes: 293, addressable: 123, households: 52680 },
  { code: '11650', sido: '서울특별시', sgg: '서초구', pop: 414616, complexes: 665, addressable: 233, households: 117250 },
  { code: '41131', sido: '경기도', sgg: '성남시수정구', pop: 234987, complexes: 109, addressable: 63, households: 31118 },
  { code: '41133', sido: '경기도', sgg: '성남시중원구', pop: 199084, complexes: 107, addressable: 52, households: 24984 },
  { code: '41670', sido: '경기도', sgg: '여주시', pop: 113383, complexes: 49, addressable: 40, households: 12658 },
  { code: '51130', sido: '강원특별자치도', sgg: '원주시', pop: 365218, complexes: 257, addressable: 221, households: 77148 },
  { code: '51750', sido: '강원특별자치도', sgg: '영월군', pop: 35685, complexes: 19, addressable: 10, households: 2750 },
  { code: '51230', sido: '강원특별자치도', sgg: '삼척시', pop: 60139, complexes: 63, addressable: 20, households: 8964 },
  { code: '41194', sido: '경기도', sgg: '부천시소사구', pop: 224007, complexes: 241, addressable: 79, households: 42400 },
  { code: '41171', sido: '경기도', sgg: '안양시만안구', pop: 234045, complexes: 205, addressable: 96, households: 42244 },
  { code: '41173', sido: '경기도', sgg: '안양시동안구', pop: 328098, complexes: 224, addressable: 149, households: 78316 },
  { code: '41290', sido: '경기도', sgg: '과천시', pop: 81008, complexes: 25, addressable: 21, households: 13236 },
  { code: '41465', sido: '경기도', sgg: '용인시수지구', pop: 368881, complexes: 273, addressable: 215, households: 88140 },
  { code: '41135', sido: '경기도', sgg: '성남시분당구', pop: 467039, complexes: 207, addressable: 201, households: 95966 },
  { code: '41500', sido: '경기도', sgg: '이천시', pop: 225911, complexes: 177, addressable: 115, households: 38518 },
  { code: '43130', sido: '충청북도', sgg: '충주시', pop: 205872, complexes: 146, addressable: 89, households: 32132 },
  { code: '43800', sido: '충청북도', sgg: '단양군', pop: 26552, complexes: 13, addressable: 6, households: 2118 },
  { code: '47920', sido: '경상북도', sgg: '봉화군', pop: 28076, complexes: 25, addressable: 0, households: 1680 },
  { code: '51190', sido: '강원특별자치도', sgg: '태백시', pop: 36755, complexes: 48, addressable: 20, households: 8744 },
  { code: '28185', sido: '인천광역시', sgg: '연수구', pop: 410280, complexes: 201, addressable: 179, households: 100190 },
  { code: '28200', sido: '인천광역시', sgg: '남동구', pop: 478762, complexes: 326, addressable: 155, households: 77496 },
  { code: '41390', sido: '경기도', sgg: '시흥시', pop: 514996, complexes: 340, addressable: 250, households: 99912 },
  { code: '41410', sido: '경기도', sgg: '군포시', pop: 249253, complexes: 221, addressable: 93, households: 52682 },
  { code: '41430', sido: '경기도', sgg: '의왕시', pop: 165701, complexes: 111, addressable: 88, households: 35302 },
  { code: '41111', sido: '경기도', sgg: '수원시장안구', pop: 269791, complexes: 163, addressable: 93, households: 44704 },
  { code: '41463', sido: '경기도', sgg: '용인시기흥구', pop: 434408, complexes: 260, addressable: 229, households: 93778 },
  { code: '41461', sido: '경기도', sgg: '용인시처인구', pop: 287270, complexes: 194, addressable: 90, households: 45392 },
  { code: '43770', sido: '충청북도', sgg: '음성군', pop: 96036, complexes: 98, addressable: 48, households: 18282 },
  { code: '43760', sido: '충청북도', sgg: '괴산군', pop: 37267, complexes: 10, addressable: 2, households: 1200 },
  { code: '43150', sido: '충청북도', sgg: '제천시', pop: 128043, complexes: 84, addressable: 58, households: 17314 },
  { code: '47210', sido: '경상북도', sgg: '영주시', pop: 96345, complexes: 83, addressable: 23, households: 10964 },
  { code: '47760', sido: '경상북도', sgg: '영양군', pop: 15973, complexes: 7, addressable: 0, households: 416 },
  { code: '47930', sido: '경상북도', sgg: '울진군', pop: 46216, complexes: 67, addressable: 3, households: 5090 },
  { code: '44825', sido: '충청남도', sgg: '태안군', pop: 59005, complexes: 29, addressable: 14, households: 4216 },
  { code: '41273', sido: '경기도', sgg: '안산시단원구', pop: 288378, complexes: 84, addressable: 77, households: 38788 },
  { code: '41271', sido: '경기도', sgg: '안산시상록구', pop: 320505, complexes: 83, addressable: 52, households: 25770 },
  { code: '41113', sido: '경기도', sgg: '수원시권선구', pop: 360118, complexes: 201, addressable: 148, households: 58952 },
  { code: '41115', sido: '경기도', sgg: '수원시팔달구', pop: 193325, complexes: 128, addressable: 76, households: 33682 },
  { code: '41117', sido: '경기도', sgg: '수원시영통구', pop: 362098, complexes: 161, addressable: 146, households: 72808 },
  { code: '41550', sido: '경기도', sgg: '안성시', pop: 199314, complexes: 100, addressable: 83, households: 39314 },
  { code: '43750', sido: '충청북도', sgg: '진천군', pop: 85590, complexes: 90, addressable: 50, households: 18652 },
  { code: '43745', sido: '충청북도', sgg: '증평군', pop: 36758, complexes: 40, addressable: 19, households: 6756 },
  { code: '47280', sido: '경상북도', sgg: '문경시', pop: 64662, complexes: 70, addressable: 11, households: 6868 },
  { code: '47900', sido: '경상북도', sgg: '예천군', pop: 53340, complexes: 40, addressable: 12, households: 5908 },
  { code: '47170', sido: '경상북도', sgg: '안동시', pop: 151584, complexes: 119, addressable: 62, households: 19184 },
  { code: '47770', sido: '경상북도', sgg: '영덕군', pop: 32536, complexes: 26, addressable: 2, households: 2102 },
  { code: '44270', sido: '충청남도', sgg: '당진시', pop: 172472, complexes: 110, addressable: 70, households: 29440 },
  { code: '41220', sido: '경기도', sgg: '평택시', pop: 620754, complexes: 408, addressable: 305, households: 137110 },
  { code: '41370', sido: '경기도', sgg: '오산시', pop: 254747, complexes: 148, addressable: 113, households: 47682 },
  { code: '44133', sido: '충청남도', sgg: '천안시서북구', pop: 402701, complexes: 321, addressable: 225, households: 89152 },
  { code: '43113', sido: '충청북도', sgg: '청주시흥덕구', pop: 293157, complexes: 200, addressable: 147, households: 59184 },
  { code: '43111', sido: '충청북도', sgg: '청주시상당구', pop: 192850, complexes: 133, addressable: 84, households: 32732 },
  { code: '43720', sido: '충청북도', sgg: '보은군', pop: 31480, complexes: 29, addressable: 2, households: 2682 },
  { code: '47250', sido: '경상북도', sgg: '상주시', pop: 89070, complexes: 70, addressable: 25, households: 8414 },
  { code: '47730', sido: '경상북도', sgg: '의성군', pop: 47920, complexes: 16, addressable: 2, households: 1420 },
  { code: '27720', sido: '대구광역시', sgg: '군위군', pop: 22552, complexes: 8, addressable: 0, households: 592 },
  { code: '47750', sido: '경상북도', sgg: '청송군', pop: 24437, complexes: 16, addressable: 0, households: 1310 },
  { code: '47113', sido: '경상북도', sgg: '포항시북구', pop: 275509, complexes: 308, addressable: 130, households: 59384 },
  { code: '44210', sido: '충청남도', sgg: '서산시', pop: 171093, complexes: 114, addressable: 70, households: 27388 },
  { code: '44810', sido: '충청남도', sgg: '예산군', pop: 78168, complexes: 51, addressable: 27, households: 8892 },
  { code: '44200', sido: '충청남도', sgg: '아산시', pop: 364270, complexes: 221, addressable: 187, households: 81508 },
  { code: '44131', sido: '충청남도', sgg: '천안시동남구', pop: 263741, complexes: 174, addressable: 114, households: 46896 },
  { code: '36110', sido: '세종특별자치시', sgg: '세종시', pop: 390972, complexes: 242, addressable: 214, households: 106286 },
  { code: '30230', sido: '대전광역시', sgg: '대덕구', pop: 163823, complexes: 133, addressable: 56, households: 25962 },
  { code: '43730', sido: '충청북도', sgg: '옥천군', pop: 50660, complexes: 32, addressable: 15, households: 4664 },
  { code: '47190', sido: '경상북도', sgg: '구미시', pop: 402691, complexes: 407, addressable: 173, households: 74158 },
  { code: '47850', sido: '경상북도', sgg: '칠곡군', pop: 103539, complexes: 75, addressable: 37, households: 12200 },
  { code: '27230', sido: '대구광역시', sgg: '북구', pop: 406587, complexes: 291, addressable: 200, households: 71606 },
  { code: '47230', sido: '경상북도', sgg: '영천시', pop: 93847, complexes: 70, addressable: 30, households: 11136 },
  { code: '47111', sido: '경상북도', sgg: '포항시남구', pop: 211509, complexes: 295, addressable: 65, households: 36814 },
  { code: '44800', sido: '충청남도', sgg: '홍성군', pop: 101743, complexes: 60, addressable: 35, households: 14916 },
  { code: '44790', sido: '충청남도', sgg: '청양군', pop: 30032, complexes: 16, addressable: 1, households: 1592 },
  { code: '44150', sido: '충청남도', sgg: '공주시', pop: 99619, complexes: 60, addressable: 39, households: 11258 },
  { code: '30200', sido: '대전광역시', sgg: '유성구', pop: 371855, complexes: 257, addressable: 195, households: 79826 },
  { code: '30110', sido: '대전광역시', sgg: '동구', pop: 218050, complexes: 132, addressable: 75, households: 30978 },
  { code: '43740', sido: '충청북도', sgg: '영동군', pop: 43029, complexes: 44, addressable: 4, households: 4204 },
  { code: '47150', sido: '경상북도', sgg: '김천시', pop: 132550, complexes: 115, addressable: 49, households: 20002 },
  { code: '27170', sido: '대구광역시', sgg: '서구', pop: 163456, complexes: 101, addressable: 21, households: 21000 },
  { code: '27110', sido: '대구광역시', sgg: '중구', pop: 101815, complexes: 85, addressable: 59, households: 32710 },
  { code: '27140', sido: '대구광역시', sgg: '동구', pop: 338544, complexes: 335, addressable: 154, households: 63618 },
  { code: '47130', sido: '경상북도', sgg: '경주시', pop: 242880, complexes: 247, addressable: 84, households: 38704 },
  { code: '44180', sido: '충청남도', sgg: '보령시', pop: 91144, complexes: 64, addressable: 35, households: 10838 },
  { code: '44760', sido: '충청남도', sgg: '부여군', pop: 57687, complexes: 19, addressable: 7, households: 2386 },
  { code: '44250', sido: '충청남도', sgg: '계룡시', pop: 45983, complexes: 22, addressable: 21, households: 7544 },
  { code: '30170', sido: '대전광역시', sgg: '서구', pop: 464428, complexes: 267, addressable: 197, households: 73654 },
  { code: '30140', sido: '대전광역시', sgg: '중구', pop: 224034, complexes: 169, addressable: 89, households: 37660 },
  { code: '47840', sido: '경상북도', sgg: '성주군', pop: 40374, complexes: 12, addressable: 5, households: 1570 },
  { code: '27290', sido: '대구광역시', sgg: '달서구', pop: 512963, complexes: 364, addressable: 234, households: 90026 },
  { code: '27200', sido: '대구광역시', sgg: '남구', pop: 141659, complexes: 101, addressable: 44, households: 18974 },
  { code: '27260', sido: '대구광역시', sgg: '수성구', pop: 407820, complexes: 344, addressable: 248, households: 88126 },
  { code: '47290', sido: '경상북도', sgg: '경산시', pop: 263171, complexes: 184, addressable: 122, households: 44376 },
  { code: '31110', sido: '울산광역시', sgg: '중구', pop: 202823, complexes: 341, addressable: 79, households: 43460 },
  { code: '31200', sido: '울산광역시', sgg: '북구', pop: 213512, complexes: 140, addressable: 112, households: 39482 },
  { code: '44770', sido: '충청남도', sgg: '서천군', pop: 46635, complexes: 34, addressable: 11, households: 3958 },
  { code: '52140', sido: '전북특별자치도', sgg: '익산시', pop: 266707, complexes: 234, addressable: 150, households: 50588 },
  { code: '44230', sido: '충청남도', sgg: '논산시', pop: 105815, complexes: 67, addressable: 35, households: 10808 },
  { code: '52710', sido: '전북특별자치도', sgg: '완주군', pop: 100378, complexes: 59, addressable: 47, households: 14518 },
  { code: '44710', sido: '충청남도', sgg: '금산군', pop: 48847, complexes: 34, addressable: 8, households: 4182 },
  { code: '52730', sido: '전북특별자치도', sgg: '무주군', pop: 23412, complexes: 18, addressable: 3, households: 1988 },
  { code: '47830', sido: '경상북도', sgg: '고령군', pop: 29472, complexes: 21, addressable: 5, households: 2326 },
  { code: '27710', sido: '대구광역시', sgg: '달성군', pop: 251993, complexes: 148, addressable: 120, households: 45718 },
  { code: '47820', sido: '경상북도', sgg: '청도군', pop: 39989, complexes: 30, addressable: 4, households: 2648 },
  { code: '48330', sido: '경상남도', sgg: '양산시', pop: 361264, complexes: 274, addressable: 189, households: 76532 },
  { code: '31710', sido: '울산광역시', sgg: '울주군', pop: 218370, complexes: 185, addressable: 95, households: 35894 },
  { code: '31170', sido: '울산광역시', sgg: '동구', pop: 147633, complexes: 224, addressable: 58, households: 32332 },
  { code: '52130', sido: '전북특별자치도', sgg: '군산시', pop: 255537, complexes: 242, addressable: 129, households: 53228 },
  { code: '52210', sido: '전북특별자치도', sgg: '김제시', pop: 81665, complexes: 62, addressable: 26, households: 10964 },
  { code: '52113', sido: '전북특별자치도', sgg: '전주시덕진구', pop: 306845, complexes: 252, addressable: 151, households: 58170 },
  { code: '52111', sido: '전북특별자치도', sgg: '전주시완산구', pop: 313004, complexes: 275, addressable: 172, households: 57538 },
  { code: '52720', sido: '전북특별자치도', sgg: '진안군', pop: 24855, complexes: 8, addressable: 1, households: 772 },
  { code: '48880', sido: '경상남도', sgg: '거창군', pop: 58760, complexes: 83, addressable: 15, households: 8496 },
  { code: '48890', sido: '경상남도', sgg: '합천군', pop: 38812, complexes: 32, addressable: 1, households: 2224 },
  { code: '48740', sido: '경상남도', sgg: '창녕군', pop: 54321, complexes: 60, addressable: 6, households: 5318 },
  { code: '48270', sido: '경상남도', sgg: '밀양시', pop: 98498, complexes: 112, addressable: 36, households: 14654 },
  { code: '26320', sido: '부산광역시', sgg: '북구', pop: 260432, complexes: 191, addressable: 104, households: 46794 },
  { code: '26410', sido: '부산광역시', sgg: '금정구', pop: 205483, complexes: 339, addressable: 94, households: 46550 },
  { code: '31140', sido: '울산광역시', sgg: '남구', pop: 304418, complexes: 429, addressable: 187, households: 75660 },
  { code: '52800', sido: '전북특별자치도', sgg: '부안군', pop: 46926, complexes: 27, addressable: 9, households: 3552 },
  { code: '52180', sido: '전북특별자치도', sgg: '정읍시', pop: 100632, complexes: 72, addressable: 36, households: 11658 },
  { code: '52750', sido: '전북특별자치도', sgg: '임실군', pop: 25308, complexes: 19, addressable: 4, households: 1884 },
  { code: '52740', sido: '전북특별자치도', sgg: '장수군', pop: 21180, complexes: 8, addressable: 0, households: 712 },
  { code: '48870', sido: '경상남도', sgg: '함양군', pop: 35121, complexes: 39, addressable: 4, households: 3004 },
  { code: '48720', sido: '경상남도', sgg: '의령군', pop: 24516, complexes: 14, addressable: 3, households: 1464 },
  { code: '48121', sido: '경상남도', sgg: '창원시의창구', pop: 209814, complexes: 214, addressable: 59, households: 34392 },
  { code: '48250', sido: '경상남도', sgg: '김해시', pop: 532758, complexes: 411, addressable: 237, households: 95550 },
  { code: '26230', sido: '부산광역시', sgg: '부산진구', pop: 364481, complexes: 470, addressable: 233, households: 102960 },
  { code: '26260', sido: '부산광역시', sgg: '동래구', pop: 270741, complexes: 342, addressable: 130, households: 67772 },
  { code: '26350', sido: '부산광역시', sgg: '해운대구', pop: 370275, complexes: 334, addressable: 189, households: 94432 },
  { code: '26710', sido: '부산광역시', sgg: '기장군', pop: 175402, complexes: 178, addressable: 79, households: 36014 },
  { code: '52790', sido: '전북특별자치도', sgg: '고창군', pop: 50006, complexes: 27, addressable: 5, households: 2792 },
  { code: '46880', sido: '전남광주통합특별시', sgg: '장성군', pop: 43130, complexes: 0, addressable: 0, households: 0 },
  { code: '46710', sido: '전남광주통합특별시', sgg: '담양군', pop: 43972, complexes: 0, addressable: 0, households: 0 },
  { code: '52770', sido: '전북특별자치도', sgg: '순창군', pop: 27642, complexes: 13, addressable: 5, households: 1928 },
  { code: '52190', sido: '전북특별자치도', sgg: '남원시', pop: 73744, complexes: 51, addressable: 24, households: 9228 },
  { code: '48860', sido: '경상남도', sgg: '산청군', pop: 32634, complexes: 19, addressable: 3, households: 1820 },
  { code: '48170', sido: '경상남도', sgg: '진주시', pop: 334360, complexes: 255, addressable: 128, households: 55974 },
  { code: '48730', sido: '경상남도', sgg: '함안군', pop: 56737, complexes: 48, addressable: 14, households: 5780 },
  { code: '48123', sido: '경상남도', sgg: '창원시성산구', pop: 245097, complexes: 121, addressable: 84, households: 40522 },
  { code: '26530', sido: '부산광역시', sgg: '사상구', pop: 192275, complexes: 170, addressable: 91, households: 34414 },
  { code: '26170', sido: '부산광역시', sgg: '동구', pop: 83146, complexes: 107, addressable: 34, households: 19048 },
  { code: '26470', sido: '부산광역시', sgg: '연제구', pop: 211580, complexes: 275, addressable: 129, households: 57114 },
  { code: '26500', sido: '부산광역시', sgg: '수영구', pop: 168955, complexes: 283, addressable: 95, households: 46848 },
  { code: '46870', sido: '전남광주통합특별시', sgg: '영광군', pop: 53752, complexes: 0, addressable: 0, households: 0 },
  { code: '29200', sido: '전남광주통합특별시', sgg: '광산구', pop: 382841, complexes: 0, addressable: 0, households: 0 },
  { code: '29140', sido: '전남광주통합특별시', sgg: '서구', pop: 274408, complexes: 0, addressable: 0, households: 0 },
  { code: '29170', sido: '전남광주통합특별시', sgg: '북구', pop: 416780, complexes: 0, addressable: 0, households: 0 },
  { code: '46720', sido: '전남광주통합특별시', sgg: '곡성군', pop: 27663, complexes: 0, addressable: 0, households: 0 },
  { code: '46730', sido: '전남광주통합특별시', sgg: '구례군', pop: 24576, complexes: 0, addressable: 0, households: 0 },
  { code: '48850', sido: '경상남도', sgg: '하동군', pop: 39539, complexes: 22, addressable: 4, households: 2020 },
  { code: '48125', sido: '경상남도', sgg: '창원시마산합포구', pop: 174360, complexes: 201, addressable: 86, households: 36806 },
  { code: '48127', sido: '경상남도', sgg: '창원시마산회원구', pop: 173916, complexes: 192, addressable: 61, households: 31274 },
  { code: '26440', sido: '부산광역시', sgg: '강서구', pop: 154119, complexes: 55, addressable: 49, households: 26268 },
  { code: '26140', sido: '부산광역시', sgg: '서구', pop: 101028, complexes: 178, addressable: 47, households: 26566 },
  { code: '26110', sido: '부산광역시', sgg: '중구', pop: 36203, complexes: 63, addressable: 10, households: 6486 },
  { code: '26290', sido: '부산광역시', sgg: '남구', pop: 254774, complexes: 277, addressable: 112, households: 59422 },
  { code: '46860', sido: '전남광주통합특별시', sgg: '함평군', pop: 29651, complexes: 0, addressable: 0, households: 0 },
  { code: '29155', sido: '전남광주통합특별시', sgg: '남구', pop: 205428, complexes: 0, addressable: 0, households: 0 },
  { code: '29110', sido: '전남광주통합특별시', sgg: '동구', pop: 105344, complexes: 0, addressable: 0, households: 0 },
  { code: '46790', sido: '전남광주통합특별시', sgg: '화순군', pop: 59820, complexes: 0, addressable: 0, households: 0 },
  { code: '46150', sido: '전남광주통합특별시', sgg: '순천시', pop: 273733, complexes: 0, addressable: 0, households: 0 },
  { code: '46230', sido: '전남광주통합특별시', sgg: '광양시', pop: 155979, complexes: 0, addressable: 0, households: 0 },
  { code: '48240', sido: '경상남도', sgg: '사천시', pop: 107838, complexes: 162, addressable: 42, households: 21882 },
  { code: '48820', sido: '경상남도', sgg: '고성군', pop: 46771, complexes: 47, addressable: 9, households: 4490 },
  { code: '48129', sido: '경상남도', sgg: '창원시진해구', pop: 182750, complexes: 174, addressable: 64, households: 33588 },
  { code: '26200', sido: '부산광역시', sgg: '영도구', pop: 100423, complexes: 137, addressable: 48, households: 20996 },
  { code: '46910', sido: '전남광주통합특별시', sgg: '신안군', pop: 42387, complexes: 0, addressable: 0, households: 0 },
  { code: '46840', sido: '전남광주통합특별시', sgg: '무안군', pop: 95598, complexes: 0, addressable: 0, households: 0 },
  { code: '46170', sido: '전남광주통합특별시', sgg: '나주시', pop: 116699, complexes: 0, addressable: 0, households: 0 },
  { code: '46780', sido: '전남광주통합특별시', sgg: '보성군', pop: 38101, complexes: 0, addressable: 0, households: 0 },
  { code: '46130', sido: '전남광주통합특별시', sgg: '여수시', pop: 260190, complexes: 0, addressable: 0, households: 0 },
  { code: '48840', sido: '경상남도', sgg: '남해군', pop: 41116, complexes: 24, addressable: 2, households: 2002 },
  { code: '48220', sido: '경상남도', sgg: '통영시', pop: 115867, complexes: 165, addressable: 52, households: 21270 },
  { code: '26380', sido: '부산광역시', sgg: '사하구', pop: 281665, complexes: 376, addressable: 133, households: 60054 },
  { code: '48310', sido: '경상남도', sgg: '거제시', pop: 228893, complexes: 291, addressable: 128, households: 50976 },
  { code: '46110', sido: '전남광주통합특별시', sgg: '목포시', pop: 199230, complexes: 0, addressable: 0, households: 0 },
  { code: '46830', sido: '전남광주통합특별시', sgg: '영암군', pop: 50027, complexes: 0, addressable: 0, households: 0 },
  { code: '46800', sido: '전남광주통합특별시', sgg: '장흥군', pop: 33906, complexes: 0, addressable: 0, households: 0 },
  { code: '46770', sido: '전남광주통합특별시', sgg: '고흥군', pop: 58991, complexes: 0, addressable: 0, households: 0 },
  { code: '46900', sido: '전남광주통합특별시', sgg: '진도군', pop: 27841, complexes: 0, addressable: 0, households: 0 },
  { code: '46820', sido: '전남광주통합특별시', sgg: '해남군', pop: 61992, complexes: 0, addressable: 0, households: 0 },
  { code: '46810', sido: '전남광주통합특별시', sgg: '강진군', pop: 31644, complexes: 0, addressable: 0, households: 0 },
  { code: '46890', sido: '전남광주통합특별시', sgg: '완도군', pop: 44094, complexes: 0, addressable: 0, households: 0 },
  { code: '50110', sido: '제주특별자치도', sgg: '제주시', pop: 484111, complexes: 648, addressable: 91, households: 63722 },
  { code: '50130', sido: '제주특별자치도', sgg: '서귀포시', pop: 178569, complexes: 197, addressable: 27, households: 19908 },
]
