/**
 * 직거래 비율, 그리고 그것을 설명한다고 주장하는 두 변수.
 *
 * GENERATED by scripts/build-direct.mjs — do not hand-edit.
 *
 * The page's argument is three correlations. Broker density predicts the
 * direct-deal rate at -0.586; population predicts it better at -0.638;
 * and the two predictors correlate with each other at 0.545. A page that
 * published only the first would have been true and misleading.
 *
 * All three are on LOGS. Both the rate (1.72% to
 * 84.58%) and the population span more than
 * an order of magnitude, and a Pearson on the raw values would have been a
 * statement about the largest outlier rather than about the country.
 *
 * Districts with fewer than 200 sales in the window are not plotted:
 * 41 of them, whose rates move by whole points on one transaction.
 */

export type DirectPoint = {
  readonly sido: string
  readonly sgg: string
  /** Apartment sales filed in the window. */
  readonly deals: number
  /** Share of them filed as 직거래, in percent. */
  readonly rate: number
  /** Brokerage offices per 10,000 residents. */
  readonly density: number
  readonly pop: number
}

export const DIRECT_WINDOW = { from: '2025-09', to: '2026-08' } as const

/** Sales below which a district is counted but not plotted. */
export const DIRECT_FLOOR = 200

export const DIRECT_INTAKE = {
  rows: 481366,
  deals: 481366,
  direct: 34963,
  districts: 217,
  /** Responses on disk, and the number a complete window would have. */
  responses: 2921,
  expected: 2940,
  plotted: 176,
  belowFloor: 41,
  /** Rows filed under a code the district map does not carry. */
  offGrid: 0,
} as const

/**
 * The observed range. Exported so the prose can cite it through a
 * placeholder instead of hardcoding it: this page is regenerated whenever
 * another month lands, and a sentence that quotes 84.6% is wrong the moment
 * a district passes it.
 */
export const DIRECT_RATE_RANGE = { min: 1.72, max: 84.58 } as const

/** National share, and the median district. They are not the same number. */
export const DIRECT_NATIONAL = 7.26
export const DIRECT_MEDIAN = 7.8

/** Pearson r on natural logs. */
export const DIRECT_R = {
  density: -0.586,
  pop: -0.638,
  both: 0.545,
} as const

export const DIRECT_POINTS: readonly DirectPoint[] = [
  { sido: '강원특별자치도', sgg: '정선군', deals: 240, rate: 84.58, density: 4, pop: 35144 },
  { sido: '강원특별자치도', sgg: '태백시', deals: 440, rate: 48.41, density: 2.4, pop: 36755 },
  { sido: '강원특별자치도', sgg: '평창군', deals: 403, rate: 44.42, density: 11.3, pop: 39865 },
  { sido: '경상남도', sgg: '창녕군', deals: 249, rate: 30.92, density: 11.6, pop: 54321 },
  { sido: '강원특별자치도', sgg: '삼척시', deals: 624, rate: 30.77, density: 5.7, pop: 60139 },
  { sido: '충청북도', sgg: '음성군', deals: 1100, rate: 30.55, density: 14.5, pop: 96036 },
  { sido: '제주특별자치도', sgg: '서귀포시', deals: 656, rate: 29.42, density: 16.2, pop: 178569 },
  { sido: '경상남도', sgg: '사천시', deals: 1360, rate: 28.53, density: 12.4, pop: 107838 },
  { sido: '경상북도', sgg: '영천시', deals: 848, rate: 27.48, density: 12, pop: 93847 },
  { sido: '전북특별자치도', sgg: '김제시', deals: 404, rate: 25.99, density: 6.9, pop: 81665 },
  { sido: '충청남도', sgg: '예산군', deals: 626, rate: 25.24, density: 10.5, pop: 78168 },
  { sido: '전북특별자치도', sgg: '남원시', deals: 386, rate: 24.09, density: 5.8, pop: 73744 },
  { sido: '경상남도', sgg: '거창군', deals: 408, rate: 24.02, density: 6.8, pop: 58760 },
  { sido: '부산광역시', sgg: '영도구', deals: 824, rate: 22.82, density: 10.4, pop: 100423 },
  { sido: '강원특별자치도', sgg: '양양군', deals: 220, rate: 22.73, density: 10.3, pop: 27310 },
  { sido: '경상북도', sgg: '경주시', deals: 2322, rate: 22.35, density: 10.5, pop: 242880 },
  { sido: '경상북도', sgg: '안동시', deals: 1505, rate: 22.26, density: 7.2, pop: 151584 },
  { sido: '충청북도', sgg: '옥천군', deals: 255, rate: 21.18, density: 3.2, pop: 50660 },
  { sido: '경기도', sgg: '부천시오정구', deals: 682, rate: 20.82, density: 18.3, pop: 148710 },
  { sido: '경상북도', sgg: '영주시', deals: 728, rate: 20.33, density: 8.9, pop: 96345 },
  { sido: '전북특별자치도', sgg: '정읍시', deals: 895, rate: 19.44, density: 6.1, pop: 100632 },
  { sido: '부산광역시', sgg: '서구', deals: 960, rate: 18.96, density: 10.3, pop: 101028 },
  { sido: '전북특별자치도', sgg: '익산시', deals: 3098, rate: 18.95, density: 10.9, pop: 266707 },
  { sido: '경상북도', sgg: '포항시남구', deals: 1802, rate: 18.92, density: 11.3, pop: 211509 },
  { sido: '강원특별자치도', sgg: '횡성군', deals: 251, rate: 18.73, density: 14.5, pop: 45521 },
  { sido: '충청남도', sgg: '금산군', deals: 220, rate: 17.73, density: 10.4, pop: 48847 },
  { sido: '충청남도', sgg: '태안군', deals: 292, rate: 17.12, density: 11.9, pop: 59005 },
  { sido: '제주특별자치도', sgg: '제주시', deals: 1653, rate: 17.06, density: 22.7, pop: 484111 },
  { sido: '경기도', sgg: '가평군', deals: 280, rate: 16.43, density: 15, pop: 62048 },
  { sido: '경상북도', sgg: '문경시', deals: 259, rate: 16.22, density: 10.8, pop: 64662 },
  { sido: '경상북도', sgg: '상주시', deals: 421, rate: 16.15, density: 8.4, pop: 89070 },
  { sido: '충청남도', sgg: '서산시', deals: 2200, rate: 15.64, density: 13.8, pop: 171093 },
  { sido: '경상남도', sgg: '밀양시', deals: 743, rate: 15.61, density: 14.7, pop: 98498 },
  { sido: '서울특별시', sgg: '중랑구', deals: 2762, rate: 15.46, density: 14.9, pop: 376282 },
  { sido: '충청남도', sgg: '보령시', deals: 707, rate: 15.13, density: 8.1, pop: 91144 },
  { sido: '충청남도', sgg: '논산시', deals: 770, rate: 14.94, density: 8.5, pop: 105815 },
  { sido: '서울특별시', sgg: '광진구', deals: 1114, rate: 14.72, density: 20.9, pop: 330802 },
  { sido: '충청남도', sgg: '홍성군', deals: 880, rate: 14.32, density: 8.9, pop: 101743 },
  { sido: '대구광역시', sgg: '남구', deals: 917, rate: 13.85, density: 14.1, pop: 141659 },
  { sido: '강원특별자치도', sgg: '강릉시', deals: 2202, rate: 13.76, density: 12.3, pop: 205593 },
  { sido: '충청남도', sgg: '아산시', deals: 5468, rate: 13.59, density: 17.3, pop: 364270 },
  { sido: '경기도', sgg: '성남시수정구', deals: 1808, rate: 13.55, density: 20.1, pop: 234987 },
  { sido: '충청북도', sgg: '증평군', deals: 402, rate: 13.18, density: 10.6, pop: 36758 },
  { sido: '경상북도', sgg: '포항시북구', deals: 3163, rate: 13.12, density: 15.2, pop: 275509 },
  { sido: '강원특별자치도', sgg: '동해시', deals: 1047, rate: 12.89, density: 5, pop: 85577 },
  { sido: '충청북도', sgg: '진천군', deals: 909, rate: 12.87, density: 11, pop: 85590 },
  { sido: '충청북도', sgg: '충주시', deals: 2658, rate: 12.64, density: 13.7, pop: 205872 },
  { sido: '충청남도', sgg: '공주시', deals: 702, rate: 12.25, density: 13.9, pop: 99619 },
  { sido: '충청남도', sgg: '당진시', deals: 2129, rate: 12.12, density: 15.6, pop: 172472 },
  { sido: '경상북도', sgg: '예천군', deals: 488, rate: 12.09, density: 7.7, pop: 53340 },
  { sido: '경상남도', sgg: '통영시', deals: 922, rate: 12.04, density: 9.1, pop: 115867 },
  { sido: '경상북도', sgg: '칠곡군', deals: 1003, rate: 11.76, density: 15.1, pop: 103539 },
  { sido: '경상남도', sgg: '함안군', deals: 404, rate: 11.63, density: 16.9, pop: 56737 },
  { sido: '경상남도', sgg: '거제시', deals: 2477, rate: 11.59, density: 10, pop: 228893 },
  { sido: '강원특별자치도', sgg: '속초시', deals: 1063, rate: 11.57, density: 18, pop: 78976 },
  { sido: '대구광역시', sgg: '서구', deals: 1188, rate: 11.36, density: 12.1, pop: 163456 },
  { sido: '부산광역시', sgg: '동구', deals: 669, rate: 11.21, density: 13.7, pop: 83146 },
  { sido: '전북특별자치도', sgg: '완주군', deals: 1306, rate: 11.18, density: 11.9, pop: 100378 },
  { sido: '경상북도', sgg: '김천시', deals: 1326, rate: 10.94, density: 11, pop: 132550 },
  { sido: '경기도', sgg: '여주시', deals: 832, rate: 10.7, density: 15.5, pop: 113383 },
  { sido: '경기도', sgg: '이천시', deals: 1777, rate: 10.64, density: 15.8, pop: 225911 },
  { sido: '부산광역시', sgg: '사하구', deals: 2844, rate: 10.48, density: 12.2, pop: 281665 },
  { sido: '경기도', sgg: '안성시', deals: 2174, rate: 10.44, density: 17.4, pop: 199314 },
  { sido: '경상남도', sgg: '창원시마산합포구', deals: 2032, rate: 10.38, density: 13.8, pop: 174360 },
  { sido: '경상북도', sgg: '구미시', deals: 5379, rate: 10.34, density: 14.4, pop: 402691 },
  { sido: '부산광역시', sgg: '수영구', deals: 2167, rate: 9.83, density: 22.1, pop: 168955 },
  { sido: '전북특별자치도', sgg: '전주시완산구', deals: 5372, rate: 9.83, density: 20.5, pop: 313004 },
  { sido: '대구광역시', sgg: '달서구', deals: 5944, rate: 9.61, density: 14.3, pop: 512963 },
  { sido: '전북특별자치도', sgg: '군산시', deals: 3476, rate: 9.55, density: 17.4, pop: 255537 },
  { sido: '충청남도', sgg: '천안시동남구', deals: 3526, rate: 9.42, density: 14.8, pop: 263741 },
  { sido: '경상남도', sgg: '창원시의창구', deals: 2030, rate: 9.26, density: 16.2, pop: 209814 },
  { sido: '경기도', sgg: '평택시', deals: 7916, rate: 9.25, density: 21.7, pop: 620754 },
  { sido: '부산광역시', sgg: '사상구', deals: 1666, rate: 8.88, density: 12.5, pop: 192275 },
  { sido: '울산광역시', sgg: '북구', deals: 3509, rate: 8.83, density: 10.7, pop: 213512 },
  { sido: '부산광역시', sgg: '금정구', deals: 1902, rate: 8.78, density: 16.9, pop: 205483 },
  { sido: '울산광역시', sgg: '동구', deals: 1937, rate: 8.78, density: 7.7, pop: 147633 },
  { sido: '경상북도', sgg: '경산시', deals: 2946, rate: 8.76, density: 16.8, pop: 263171 },
  { sido: '경기도', sgg: '양평군', deals: 625, rate: 8.64, density: 21.4, pop: 126995 },
  { sido: '경기도', sgg: '동두천시', deals: 943, rate: 8.59, density: 13.3, pop: 86186 },
  { sido: '대구광역시', sgg: '달성군', deals: 3016, rate: 8.42, density: 14.7, pop: 251993 },
  { sido: '울산광역시', sgg: '울주군', deals: 2696, rate: 8.42, density: 15, pop: 218370 },
  { sido: '대전광역시', sgg: '대덕구', deals: 1596, rate: 8.4, density: 12.6, pop: 163823 },
  { sido: '울산광역시', sgg: '중구', deals: 2386, rate: 8.34, density: 11.7, pop: 202823 },
  { sido: '경상남도', sgg: '창원시진해구', deals: 1619, rate: 8.34, density: 12.4, pop: 182750 },
  { sido: '부산광역시', sgg: '부산진구', deals: 4809, rate: 8.3, density: 16.3, pop: 364481 },
  { sido: '강원특별자치도', sgg: '원주시', deals: 5386, rate: 8.08, density: 14.8, pop: 365218 },
  { sido: '서울특별시', sgg: '성동구', deals: 1757, rate: 7.97, density: 22.7, pop: 274346 },
  { sido: '서울특별시', sgg: '종로구', deals: 577, rate: 7.8, density: 30.5, pop: 136139 },
  { sido: '경상남도', sgg: '김해시', deals: 6849, rate: 7.72, density: 17.1, pop: 532758 },
  { sido: '서울특별시', sgg: '구로구', deals: 3863, rate: 7.56, density: 15.9, pop: 382531 },
  { sido: '경기도', sgg: '부천시소사구', deals: 2469, rate: 7.53, density: 14.1, pop: 224007 },
  { sido: '강원특별자치도', sgg: '춘천시', deals: 3427, rate: 7.47, density: 12.5, pop: 284853 },
  { sido: '경상남도', sgg: '양산시', deals: 5167, rate: 7.45, density: 16.7, pop: 361264 },
  { sido: '대전광역시', sgg: '중구', deals: 2170, rate: 7.33, density: 13.5, pop: 224034 },
  { sido: '충청북도', sgg: '청주시상당구', deals: 2567, rate: 7.28, density: 12.1, pop: 192850 },
  { sido: '경기도', sgg: '포천시', deals: 760, rate: 7.24, density: 18.1, pop: 140454 },
  { sido: '대구광역시', sgg: '북구', deals: 4751, rate: 7.2, density: 13.4, pop: 406587 },
  { sido: '전북특별자치도', sgg: '전주시덕진구', deals: 5074, rate: 7.06, density: 20.9, pop: 306845 },
  { sido: '충청남도', sgg: '천안시서북구', deals: 6095, rate: 6.66, density: 20.6, pop: 402701 },
  { sido: '대구광역시', sgg: '동구', deals: 3679, rate: 6.52, density: 14.7, pop: 338544 },
  { sido: '경상남도', sgg: '진주시', deals: 4695, rate: 6.45, density: 19, pop: 334360 },
  { sido: '인천광역시', sgg: '계양구', deals: 2863, rate: 6.25, density: 13, pop: 276125 },
  { sido: '대구광역시', sgg: '수성구', deals: 4969, rate: 6.12, density: 19.7, pop: 407820 },
  { sido: '경기도', sgg: '안산시상록구', deals: 1829, rate: 6.12, density: 12.4, pop: 320505 },
  { sido: '충청북도', sgg: '청주시흥덕구', deals: 4842, rate: 6.09, density: 18.5, pop: 293157 },
  { sido: '경상남도', sgg: '창원시마산회원구', deals: 1945, rate: 6.02, density: 12.2, pop: 173916 },
  { sido: '부산광역시', sgg: '동래구', deals: 3691, rate: 5.96, density: 18.3, pop: 270741 },
  { sido: '서울특별시', sgg: '동대문구', deals: 3092, rate: 5.92, density: 19.4, pop: 353070 },
  { sido: '세종특별자치시', sgg: '세종시', deals: 5183, rate: 5.83, density: 21.5, pop: 390972 },
  { sido: '경기도', sgg: '고양시일산서구', deals: 3083, rate: 5.77, density: 15.4, pop: 276159 },
  { sido: '서울특별시', sgg: '동작구', deals: 2883, rate: 5.65, density: 17.1, pop: 371543 },
  { sido: '대전광역시', sgg: '동구', deals: 2082, rate: 5.62, density: 14.1, pop: 218050 },
  { sido: '충청북도', sgg: '제천시', deals: 1455, rate: 5.5, density: 9.9, pop: 128043 },
  { sido: '충청남도', sgg: '계룡시', deals: 675, rate: 5.48, density: 10, pop: 45983 },
  { sido: '서울특별시', sgg: '서초구', deals: 2290, rate: 5.46, density: 31.3, pop: 414616 },
  { sido: '대구광역시', sgg: '중구', deals: 2128, rate: 5.45, density: 24.1, pop: 101815 },
  { sido: '부산광역시', sgg: '북구', deals: 3316, rate: 5.4, density: 10.6, pop: 260432 },
  { sido: '인천광역시', sgg: '남동구', deals: 4174, rate: 5.22, density: 13.2, pop: 478762 },
  { sido: '부산광역시', sgg: '기장군', deals: 1755, rate: 5.13, density: 16.4, pop: 175402 },
  { sido: '부산광역시', sgg: '남구', deals: 3202, rate: 5.09, density: 15.2, pop: 254774 },
  { sido: '경기도', sgg: '양주시', deals: 3105, rate: 5.02, density: 13.3, pop: 297352 },
  { sido: '부산광역시', sgg: '연제구', deals: 3171, rate: 4.98, density: 17.9, pop: 211580 },
  { sido: '강원특별자치도', sgg: '홍천군', deals: 324, rate: 4.94, density: 11.7, pop: 65810 },
  { sido: '인천광역시', sgg: '부평구', deals: 5235, rate: 4.93, density: 14.4, pop: 487661 },
  { sido: '서울특별시', sgg: '강서구', deals: 4431, rate: 4.9, density: 17.5, pop: 548268 },
  { sido: '대전광역시', sgg: '서구', deals: 6299, rate: 4.87, density: 16.9, pop: 464428 },
  { sido: '서울특별시', sgg: '관악구', deals: 2663, rate: 4.84, density: 14.2, pop: 477503 },
  { sido: '경기도', sgg: '부천시원미구', deals: 4810, rate: 4.62, density: 18.6, pop: 382134 },
  { sido: '부산광역시', sgg: '해운대구', deals: 4875, rate: 4.59, density: 18.4, pop: 370275 },
  { sido: '경기도', sgg: '고양시일산동구', deals: 2330, rate: 4.59, density: 17.9, pop: 298158 },
  { sido: '서울특별시', sgg: '은평구', deals: 3197, rate: 4.54, density: 17.7, pop: 453056 },
  { sido: '울산광역시', sgg: '남구', deals: 4963, rate: 4.53, density: 21.3, pop: 304418 },
  { sido: '경기도', sgg: '광주시', deals: 3478, rate: 4.4, density: 15.4, pop: 400323 },
  { sido: '대전광역시', sgg: '유성구', deals: 4906, rate: 4.34, density: 19, pop: 371855 },
  { sido: '인천광역시', sgg: '연수구', deals: 5979, rate: 4.32, density: 15.7, pop: 410280 },
  { sido: '경기도', sgg: '용인시처인구', deals: 2733, rate: 4.21, density: 18.9, pop: 287270 },
  { sido: '경상남도', sgg: '창원시성산구', deals: 5001, rate: 3.88, density: 19, pop: 245097 },
  { sido: '경기도', sgg: '김포시', deals: 4929, rate: 3.83, density: 17.4, pop: 483964 },
  { sido: '경기도', sgg: '오산시', deals: 3231, rate: 3.74, density: 11.4, pop: 254747 },
  { sido: '경기도', sgg: '용인시기흥구', deals: 8330, rate: 3.72, density: 12.8, pop: 434408 },
  { sido: '서울특별시', sgg: '도봉구', deals: 2506, rate: 3.71, density: 12.8, pop: 298067 },
  { sido: '경기도', sgg: '시흥시', deals: 6183, rate: 3.69, density: 19.3, pop: 514996 },
  { sido: '서울특별시', sgg: '노원구', deals: 7184, rate: 3.59, density: 11.8, pop: 480549 },
  { sido: '서울특별시', sgg: '금천구', deals: 1204, rate: 3.57, density: 20.2, pop: 222421 },
  { sido: '서울특별시', sgg: '강남구', deals: 2922, rate: 3.56, density: 37, pop: 552631 },
  { sido: '경기도', sgg: '성남시중원구', deals: 1924, rate: 3.43, density: 22, pop: 199084 },
  { sido: '경기도', sgg: '의정부시', deals: 5587, rate: 3.4, density: 12.6, pop: 461879 },
  { sido: '경기도', sgg: '파주시', deals: 4512, rate: 3.39, density: 13.6, pop: 534503 },
  { sido: '부산광역시', sgg: '강서구', deals: 1542, rate: 3.37, density: 28.4, pop: 154119 },
  { sido: '서울특별시', sgg: '강북구', deals: 1439, rate: 3.34, density: 16.1, pop: 277695 },
  { sido: '경기도', sgg: '과천시', deals: 360, rate: 3.33, density: 20.2, pop: 81008 },
  { sido: '경기도', sgg: '남양주시', deals: 9873, rate: 3.32, density: 14, pop: 727373 },
  { sido: '서울특별시', sgg: '양천구', deals: 2664, rate: 3.3, density: 17.5, pop: 420595 },
  { sido: '경기도', sgg: '군포시', deals: 4562, rate: 3.24, density: 15.2, pop: 249253 },
  { sido: '경기도', sgg: '고양시덕양구', deals: 5391, rate: 3.13, density: 14.9, pop: 482849 },
  { sido: '경기도', sgg: '안산시단원구', deals: 2989, rate: 3.11, density: 18.1, pop: 288378 },
  { sido: '서울특별시', sgg: '송파구', deals: 4675, rate: 2.97, density: 20.1, pop: 649715 },
  { sido: '경기도', sgg: '수원시권선구', deals: 5700, rate: 2.93, density: 14.6, pop: 360118 },
  { sido: '서울특별시', sgg: '서대문구', deals: 2729, rate: 2.89, density: 17.6, pop: 299531 },
  { sido: '경기도', sgg: '안양시만안구', deals: 3341, rate: 2.84, density: 16.1, pop: 234045 },
  { sido: '경기도', sgg: '수원시팔달구', deals: 2689, rate: 2.79, density: 21.3, pop: 193325 },
  { sido: '경기도', sgg: '성남시분당구', deals: 5129, rate: 2.71, density: 19, pop: 467039 },
  { sido: '서울특별시', sgg: '마포구', deals: 2041, rate: 2.6, density: 25.7, pop: 356154 },
  { sido: '서울특별시', sgg: '강동구', deals: 4158, rate: 2.57, density: 19, pop: 498701 },
  { sido: '경기도', sgg: '수원시장안구', deals: 2896, rate: 2.52, density: 14.8, pop: 269791 },
  { sido: '서울특별시', sgg: '영등포구', deals: 3008, rate: 2.46, density: 22.3, pop: 371691 },
  { sido: '경기도', sgg: '안양시동안구', deals: 6125, rate: 2.37, density: 19.5, pop: 328098 },
  { sido: '서울특별시', sgg: '중구', deals: 931, rate: 2.36, density: 39.8, pop: 117493 },
  { sido: '경기도', sgg: '의왕시', deals: 2268, rate: 2.34, density: 14.1, pop: 165701 },
  { sido: '서울특별시', sgg: '용산구', deals: 1035, rate: 2.32, density: 34, pop: 199575 },
  { sido: '경기도', sgg: '하남시', deals: 4063, rate: 2.26, density: 19.1, pop: 327423 },
  { sido: '경기도', sgg: '광명시', deals: 4193, rate: 2.12, density: 17.3, pop: 303726 },
  { sido: '경기도', sgg: '용인시수지구', deals: 7314, rate: 2.01, density: 13.3, pop: 368881 },
  { sido: '서울특별시', sgg: '성북구', deals: 3947, rate: 1.98, density: 15.4, pop: 421289 },
  { sido: '경기도', sgg: '수원시영통구', deals: 6728, rate: 1.8, density: 16.7, pop: 362098 },
  { sido: '경기도', sgg: '구리시', deals: 4119, rate: 1.72, density: 18, pop: 188040 },
]
