/**
 * 시군구별 아파트 가격변동, 같은 단지끼리 짝지어 잰 것.
 *
 * GENERATED by scripts/build-prices.mjs — do not hand-edit.
 *
 * NOT a comparison of medians. A district's median sale price moves when the
 * mix of what sold moves, so the unit here is a (district, complex, 10 m2
 * band) that traded in both ends of the window — 22,718 of
 * them. Each contributes one percentage change of its median price per unit
 * area and the district is the median of its pairs, which holds the
 * building, the size class and the neighbourhood fixed.
 *
 * THE SCALE DIVERGES because the data does: 42 districts fell and 118
 * rose, from -7.4% to 21.3%. Zero is a real
 * midpoint rather than a convenience, and that is why the class edges are
 * chosen round numbers instead of quantiles or natural breaks — a diverging
 * scale cannot put its midpoint wherever the data would prefer.
 *
 * 167 of 245 districts are measured. The rest did not
 * have the same complexes trading at both ends.
 */

export type PriceChange = {
  readonly sido: string
  readonly sgg: string
  /** Median percentage change across this district's matched pairs. */
  readonly change: number
  /** How many pairs it rests on. */
  readonly pairs: number
}

/** The two ends compared, three months each. */
export const PRICE_WINDOW = {
  early: '202509',
  earlyEnd: '202511',
  late: '202606',
  lateEnd: '202608',
} as const

/** Pairs below which a district is left unmeasured. */
export const PRICE_FLOOR = 20

/**
 * Class edges. There are `PRICE_EDGES.length + 1` classes: class 0 is
 * everything below the first edge, the last is everything above the last.
 */
export const PRICE_EDGES: readonly number[] = [-5, -2, 0, 2, 5, 10, 15]

/** Districts per class, in the same order. */
export const PRICE_COUNTS: readonly number[] = [4, 11, 27, 48, 29, 18, 14, 16]

export const PRICE_INTAKE = {
  rows: 232380,
  pairs: 22718,
  districts: 245,
  measured: 167,
  /** Had pairs, but fewer than the floor. */
  thin: 47,
} as const

export const PRICE_STATS = {
  median: 1.7,
  min: -7.4,
  max: 21.3,
  fell: 42,
  rose: 118,
} as const

export const PRICE_VALUES: readonly PriceChange[] = [
  { sido: '경기도', sgg: '성남시중원구', change: 21.3, pairs: 75 },
  { sido: '서울특별시', sgg: '동대문구', change: 19.5, pairs: 174 },
  { sido: '서울특별시', sgg: '성북구', change: 19.4, pairs: 194 },
  { sido: '경기도', sgg: '성남시수정구', change: 19.3, pairs: 59 },
  { sido: '경기도', sgg: '용인시수지구', change: 19.3, pairs: 337 },
  { sido: '경기도', sgg: '하남시', change: 19.1, pairs: 159 },
  { sido: '경기도', sgg: '광명시', change: 19, pairs: 151 },
  { sido: '경기도', sgg: '성남시분당구', change: 17.8, pairs: 311 },
  { sido: '경기도', sgg: '안양시동안구', change: 17.6, pairs: 220 },
  { sido: '서울특별시', sgg: '동작구', change: 17.3, pairs: 155 },
  { sido: '경기도', sgg: '구리시', change: 17.2, pairs: 142 },
  { sido: '서울특별시', sgg: '영등포구', change: 16.4, pairs: 184 },
  { sido: '서울특별시', sgg: '강서구', change: 15.8, pairs: 235 },
  { sido: '서울특별시', sgg: '서대문구', change: 15.6, pairs: 139 },
  { sido: '서울특별시', sgg: '중구', change: 15.2, pairs: 51 },
  { sido: '서울특별시', sgg: '성동구', change: 15, pairs: 103 },
  { sido: '서울특별시', sgg: '종로구', change: 14.7, pairs: 26 },
  { sido: '서울특별시', sgg: '강동구', change: 14.7, pairs: 189 },
  { sido: '서울특별시', sgg: '관악구', change: 14.7, pairs: 104 },
  { sido: '서울특별시', sgg: '송파구', change: 14.1, pairs: 217 },
  { sido: '서울특별시', sgg: '구로구', change: 12.5, pairs: 210 },
  { sido: '경기도', sgg: '수원시영통구', change: 12.1, pairs: 222 },
  { sido: '서울특별시', sgg: '광진구', change: 11.7, pairs: 73 },
  { sido: '서울특별시', sgg: '노원구', change: 11.4, pairs: 299 },
  { sido: '서울특별시', sgg: '양천구', change: 11.2, pairs: 154 },
  { sido: '강원특별자치도', sgg: '삼척시', change: 11.1, pairs: 33 },
  { sido: '서울특별시', sgg: '강북구', change: 10.6, pairs: 62 },
  { sido: '서울특별시', sgg: '중랑구', change: 10.6, pairs: 135 },
  { sido: '서울특별시', sgg: '마포구', change: 10.4, pairs: 142 },
  { sido: '서울특별시', sgg: '은평구', change: 10, pairs: 167 },
  { sido: '경기도', sgg: '의왕시', change: 9.7, pairs: 99 },
  { sido: '경기도', sgg: '용인시기흥구', change: 8.8, pairs: 318 },
  { sido: '경상남도', sgg: '창원시성산구', change: 8.7, pairs: 182 },
  { sido: '강원특별자치도', sgg: '동해시', change: 8.1, pairs: 58 },
  { sido: '서울특별시', sgg: '금천구', change: 8.1, pairs: 57 },
  { sido: '서울특별시', sgg: '도봉구', change: 7.9, pairs: 130 },
  { sido: '전북특별자치도', sgg: '남원시', change: 7.9, pairs: 31 },
  { sido: '경상남도', sgg: '진주시', change: 7.8, pairs: 192 },
  { sido: '경기도', sgg: '군포시', change: 7.1, pairs: 154 },
  { sido: '경기도', sgg: '수원시팔달구', change: 7, pairs: 90 },
  { sido: '서울특별시', sgg: '용산구', change: 6.9, pairs: 50 },
  { sido: '경기도', sgg: '안양시만안구', change: 6.9, pairs: 141 },
  { sido: '전북특별자치도', sgg: '전주시덕진구', change: 6.4, pairs: 226 },
  { sido: '경기도', sgg: '수원시장안구', change: 6.2, pairs: 118 },
  { sido: '대구광역시', sgg: '중구', change: 5.7, pairs: 74 },
  { sido: '전북특별자치도', sgg: '전주시완산구', change: 5.7, pairs: 232 },
  { sido: '경상남도', sgg: '거창군', change: 5.4, pairs: 24 },
  { sido: '경기도', sgg: '수원시권선구', change: 5.2, pairs: 203 },
  { sido: '전북특별자치도', sgg: '완주군', change: 4.7, pairs: 54 },
  { sido: '강원특별자치도', sgg: '태백시', change: 4.6, pairs: 20 },
  { sido: '경상북도', sgg: '안동시', change: 4.6, pairs: 88 },
  { sido: '경기도', sgg: '부천시원미구', change: 4.3, pairs: 222 },
  { sido: '울산광역시', sgg: '남구', change: 3.9, pairs: 256 },
  { sido: '경기도', sgg: '남양주시', change: 3.6, pairs: 423 },
  { sido: '경기도', sgg: '용인시처인구', change: 3.5, pairs: 120 },
  { sido: '경상북도', sgg: '경주시', change: 3.4, pairs: 135 },
  { sido: '경기도', sgg: '부천시소사구', change: 3.3, pairs: 108 },
  { sido: '충청남도', sgg: '서산시', change: 2.8, pairs: 106 },
  { sido: '대구광역시', sgg: '서구', change: 2.7, pairs: 42 },
  { sido: '울산광역시', sgg: '울주군', change: 2.6, pairs: 143 },
  { sido: '경기도', sgg: '가평군', change: 2.5, pairs: 22 },
  { sido: '울산광역시', sgg: '중구', change: 2.5, pairs: 115 },
  { sido: '부산광역시', sgg: '연제구', change: 2.5, pairs: 149 },
  { sido: '충청남도', sgg: '당진시', change: 2.4, pairs: 104 },
  { sido: '경상북도', sgg: '상주시', change: 2.4, pairs: 26 },
  { sido: '경상남도', sgg: '밀양시', change: 2.4, pairs: 41 },
  { sido: '경기도', sgg: '고양시덕양구', change: 2.3, pairs: 220 },
  { sido: '경기도', sgg: '광주시', change: 2.3, pairs: 189 },
  { sido: '경상남도', sgg: '창원시의창구', change: 2.3, pairs: 90 },
  { sido: '서울특별시', sgg: '서초구', change: 2.2, pairs: 128 },
  { sido: '경상북도', sgg: '영천시', change: 2.2, pairs: 44 },
  { sido: '부산광역시', sgg: '동래구', change: 2.2, pairs: 161 },
  { sido: '부산광역시', sgg: '수영구', change: 2.2, pairs: 104 },
  { sido: '경상남도', sgg: '창원시마산회원구', change: 2.2, pairs: 97 },
  { sido: '경기도', sgg: '과천시', change: 2, pairs: 20 },
  { sido: '인천광역시', sgg: '연수구', change: 2, pairs: 254 },
  { sido: '부산광역시', sgg: '해운대구', change: 2, pairs: 249 },
  { sido: '충청북도', sgg: '충주시', change: 1.9, pairs: 129 },
  { sido: '경상북도', sgg: '영주시', change: 1.9, pairs: 43 },
  { sido: '대구광역시', sgg: '수성구', change: 1.9, pairs: 273 },
  { sido: '대전광역시', sgg: '서구', change: 1.8, pairs: 251 },
  { sido: '경상남도', sgg: '양산시', change: 1.8, pairs: 229 },
  { sido: '부산광역시', sgg: '부산진구', change: 1.8, pairs: 230 },
  { sido: '충청남도', sgg: '계룡시', change: 1.7, pairs: 23 },
  { sido: '충청남도', sgg: '논산시', change: 1.7, pairs: 51 },
  { sido: '대구광역시', sgg: '남구', change: 1.6, pairs: 49 },
  { sido: '대구광역시', sgg: '동구', change: 1.5, pairs: 186 },
  { sido: '울산광역시', sgg: '북구', change: 1.5, pairs: 145 },
  { sido: '부산광역시', sgg: '동구', change: 1.4, pairs: 34 },
  { sido: '부산광역시', sgg: '북구', change: 1.3, pairs: 164 },
  { sido: '서울특별시', sgg: '강남구', change: 1.2, pairs: 162 },
  { sido: '전북특별자치도', sgg: '정읍시', change: 1.2, pairs: 52 },
  { sido: '경상남도', sgg: '창원시마산합포구', change: 1.2, pairs: 92 },
  { sido: '경기도', sgg: '의정부시', change: 1.1, pairs: 283 },
  { sido: '인천광역시', sgg: '부평구', change: 1.1, pairs: 243 },
  { sido: '경기도', sgg: '안산시단원구', change: 1.1, pairs: 135 },
  { sido: '충청북도', sgg: '청주시흥덕구', change: 1.1, pairs: 181 },
  { sido: '대전광역시', sgg: '동구', change: 0.9, pairs: 103 },
  { sido: '부산광역시', sgg: '사하구', change: 0.9, pairs: 133 },
  { sido: '경기도', sgg: '오산시', change: 0.8, pairs: 131 },
  { sido: '경상북도', sgg: '구미시', change: 0.8, pairs: 244 },
  { sido: '경상북도', sgg: '김천시', change: 0.8, pairs: 73 },
  { sido: '경기도', sgg: '안산시상록구', change: 0.7, pairs: 84 },
  { sido: '부산광역시', sgg: '남구', change: 0.7, pairs: 166 },
  { sido: '대구광역시', sgg: '북구', change: 0.6, pairs: 243 },
  { sido: '충청남도', sgg: '공주시', change: 0.6, pairs: 50 },
  { sido: '부산광역시', sgg: '금정구', change: 0.6, pairs: 97 },
  { sido: '경기도', sgg: '포천시', change: 0.5, pairs: 49 },
  { sido: '경상남도', sgg: '함안군', change: 0.5, pairs: 25 },
  { sido: '경기도', sgg: '양주시', change: 0.4, pairs: 145 },
  { sido: '경기도', sgg: '양평군', change: 0.4, pairs: 36 },
  { sido: '경기도', sgg: '시흥시', change: 0.4, pairs: 289 },
  { sido: '충청남도', sgg: '태안군', change: 0.4, pairs: 22 },
  { sido: '대전광역시', sgg: '대덕구', change: 0.3, pairs: 78 },
  { sido: '경상북도', sgg: '경산시', change: 0.3, pairs: 157 },
  { sido: '대전광역시', sgg: '유성구', change: 0.2, pairs: 216 },
  { sido: '충청남도', sgg: '보령시', change: 0.2, pairs: 46 },
  { sido: '인천광역시', sgg: '계양구', change: 0.1, pairs: 160 },
  { sido: '강원특별자치도', sgg: '춘천시', change: 0, pairs: 167 },
  { sido: '인천광역시', sgg: '남동구', change: 0, pairs: 211 },
  { sido: '충청북도', sgg: '제천시', change: 0, pairs: 80 },
  { sido: '충청남도', sgg: '천안시서북구', change: 0, pairs: 294 },
  { sido: '경상북도', sgg: '칠곡군', change: 0, pairs: 53 },
  { sido: '대구광역시', sgg: '달서구', change: 0, pairs: 297 },
  { sido: '울산광역시', sgg: '동구', change: 0, pairs: 79 },
  { sido: '부산광역시', sgg: '서구', change: -0.1, pairs: 45 },
  { sido: '제주특별자치도', sgg: '서귀포시', change: -0.1, pairs: 34 },
  { sido: '경기도', sgg: '부천시오정구', change: -0.2, pairs: 36 },
  { sido: '부산광역시', sgg: '기장군', change: -0.3, pairs: 83 },
  { sido: '대전광역시', sgg: '중구', change: -0.4, pairs: 114 },
  { sido: '경상남도', sgg: '통영시', change: -0.4, pairs: 52 },
  { sido: '충청남도', sgg: '예산군', change: -0.5, pairs: 36 },
  { sido: '제주특별자치도', sgg: '제주시', change: -0.5, pairs: 87 },
  { sido: '세종특별자치시', sgg: '세종시', change: -0.7, pairs: 271 },
  { sido: '전북특별자치도', sgg: '익산시', change: -0.7, pairs: 159 },
  { sido: '강원특별자치도', sgg: '강릉시', change: -0.8, pairs: 124 },
  { sido: '경기도', sgg: '김포시', change: -1, pairs: 206 },
  { sido: '충청북도', sgg: '청주시상당구', change: -1, pairs: 111 },
  { sido: '경기도', sgg: '안성시', change: -1.1, pairs: 93 },
  { sido: '충청남도', sgg: '천안시동남구', change: -1.1, pairs: 155 },
  { sido: '대구광역시', sgg: '달성군', change: -1.2, pairs: 161 },
  { sido: '경기도', sgg: '고양시일산동구', change: -1.4, pairs: 125 },
  { sido: '충청남도', sgg: '홍성군', change: -1.4, pairs: 44 },
  { sido: '경상남도', sgg: '사천시', change: -1.4, pairs: 63 },
  { sido: '강원특별자치도', sgg: '원주시', change: -1.5, pairs: 250 },
  { sido: '경상남도', sgg: '김해시', change: -1.5, pairs: 291 },
  { sido: '부산광역시', sgg: '사상구', change: -1.5, pairs: 107 },
  { sido: '경기도', sgg: '평택시', change: -1.6, pairs: 324 },
  { sido: '부산광역시', sgg: '영도구', change: -1.6, pairs: 46 },
  { sido: '충청북도', sgg: '진천군', change: -1.7, pairs: 59 },
  { sido: '경상남도', sgg: '창녕군', change: -1.7, pairs: 20 },
  { sido: '경기도', sgg: '파주시', change: -1.8, pairs: 197 },
  { sido: '전북특별자치도', sgg: '군산시', change: -2.1, pairs: 174 },
  { sido: '경상남도', sgg: '거제시', change: -2.1, pairs: 133 },
  { sido: '경기도', sgg: '동두천시', change: -2.3, pairs: 59 },
  { sido: '경상남도', sgg: '창원시진해구', change: -2.3, pairs: 85 },
  { sido: '경기도', sgg: '여주시', change: -2.5, pairs: 48 },
  { sido: '충청남도', sgg: '아산시', change: -2.7, pairs: 238 },
  { sido: '부산광역시', sgg: '강서구', change: -2.7, pairs: 57 },
  { sido: '충청북도', sgg: '증평군', change: -2.9, pairs: 23 },
  { sido: '경기도', sgg: '고양시일산서구', change: -3.2, pairs: 206 },
  { sido: '경상북도', sgg: '포항시북구', change: -5, pairs: 163 },
  { sido: '전북특별자치도', sgg: '김제시', change: -5, pairs: 28 },
  { sido: '충청북도', sgg: '음성군', change: -5.1, pairs: 56 },
  { sido: '강원특별자치도', sgg: '속초시', change: -5.2, pairs: 61 },
  { sido: '경상북도', sgg: '포항시남구', change: -5.3, pairs: 87 },
  { sido: '경기도', sgg: '이천시', change: -7.4, pairs: 109 },
]
