/**
 * 중개사무소 소재지와 매물 소재지, 같은지 다른지.
 *
 * GENERATED by scripts/build-reach.mjs — do not hand-edit.
 *
 * 511,444 개의 중개 다리 가운데 91.5% 가 매물과 같은
 * 시군구의 사무소에서 나왔습니다. 시군구별 중앙값은 92.5% 이고,
 * 경계를 넘은 8.5% 도 중앙값 9.3km — 대개 바로 옆
 * 시군구입니다.
 *
 * 그래서 이 데이터로 흐름 지도를 그리지 않습니다. 서로 다른 외부 짝이
 * 5,032개이고 그중 가장 굵은 10개가 외부 물량의 7.9% 입니다.
 * 5천 개의 선을 그려 8%를 보여주는 그림은, 흐름을 봤다는 인상만 남깁니다.
 *
 * 단위는 거래가 아니라 다리입니다. 소재지 필드는 시군구가 둘 이상
 * 걸리면 쉼표로 나뉘고, 항목 하나가 다리 하나입니다.
 */

export type ReachDistrict = {
  readonly sido: string
  readonly sgg: string
  /** Share of this district's legs handled from inside it. */
  readonly rate: number
  readonly legs: number
  /** The thickest external inflow, its size and how far it came. */
  readonly origin: string
  readonly originLegs: number
  readonly originShare: number
  readonly originKm: number
}

export const REACH_WINDOW = {
  from: '2025-09',
  to: '2026-08',
} as const

/** Legs below which a district is counted but not plotted. */
export const REACH_FLOOR = 200

export const REACH_INTAKE = {
  /** 중개거래 filings — 직거래 has no office and is not here. */
  records: 481694,
  legs: 513213,
  matched: 511444,
  /** Legs whose 시군구 name is not in the code table. */
  unmatched: 1769,
  districts: 245,
  measured: 186,
  belowFloor: 57,
  noLegs: 2,
  /** Legs that crossed a district line. */
  external: 43262,
  /** Distinct (destination, origin) pairs among those. */
  flows: 5032,
} as const

/** Share of all matched legs handled from inside the property's district. */
export const REACH_NATIONAL = 91.5

/** Share of external legs carried by the ten thickest pairs. */
export const REACH_TOP_TEN = 7.9

/** The distribution of `rate` across the 186 measured districts. */
export const REACH_QUANTILES = {
  min: 18.9,
  p5: 83,
  p25: 88.4,
  median: 92.5,
  p75: 96.1,
  p95: 99,
  max: 100,
} as const

/**
 * Every measured district's share, ascending. The figure is a dot per entry
 * on a full 0–100 axis: no binning, so the one district at 18.9% stays
 * visible instead of disappearing into an underflow bucket.
 */
export const REACH_RATES: readonly number[] = [18.9, 70.9, 71.9, 75.7, 78.7, 80.3, 81.1, 81.4, 82.2, 83, 83.1, 83.1, 83.2, 83.3, 83.6, 83.6, 84, 84.1, 84.6, 85, 85, 85.1, 85.7, 85.9, 86.6, 86.7, 86.9, 86.9, 86.9, 87, 87, 87.1, 87.3, 87.3, 87.3, 87.4, 87.4, 87.8, 87.9, 88, 88, 88.1, 88.1, 88.2, 88.2, 88.2, 88.4, 88.4, 88.4, 88.6, 88.6, 88.7, 89, 89.3, 89.3, 89.5, 89.5, 89.7, 89.8, 89.8, 89.8, 89.9, 89.9, 90, 90, 90, 90.1, 90.1, 90.1, 90.2, 90.2, 90.2, 90.4, 90.4, 90.5, 90.6, 90.6, 90.6, 90.8, 90.9, 91.3, 91.3, 91.3, 91.4, 91.5, 91.5, 91.6, 91.6, 92.1, 92.2, 92.2, 92.2, 92.4, 92.5, 92.6, 92.6, 92.6, 92.6, 92.7, 93, 93, 93.2, 93.2, 93.3, 93.3, 93.4, 93.5, 93.6, 93.7, 93.7, 93.7, 93.8, 93.8, 93.8, 93.9, 94.1, 94.1, 94.1, 94.2, 94.5, 94.5, 94.6, 94.6, 94.6, 94.7, 94.8, 94.8, 94.8, 94.8, 95.2, 95.2, 95.3, 95.4, 95.4, 95.4, 95.5, 95.8, 95.9, 96, 96.1, 96.2, 96.3, 96.5, 96.8, 96.8, 96.8, 97, 97.2, 97.3, 97.3, 97.4, 97.5, 97.6, 97.6, 97.7, 97.7, 97.9, 98.2, 98.2, 98.3, 98.4, 98.4, 98.4, 98.5, 98.5, 98.5, 98.5, 98.6, 98.6, 98.6, 98.6, 98.8, 98.8, 98.8, 99, 99, 99, 99, 99.1, 99.2, 99.2, 99.3, 99.4, 99.8, 99.9, 100]

/** How far the external legs went. */
export const REACH_DISTANCE = {
  median: 9.3,
  p75: 16.2,
  p90: 28,
  p99: 230,
  max: 522,
  bands: [{ to: 10, share: 54.5 }, { to: 20, share: 83.2 }, { to: 50, share: 94.9 }, { to: 100, share: 97.7 }, { to: 200, share: 98.8 }],
} as const

/**
 * 공동중개, as far as this field can see it.
 *
 * `cross` and `same` are COUNTS, not a share, because the share rounds to
 * 100.0% at one decimal place and a rounded 100 was once read as "not one of
 * them". 30,317 filings with two entries name two
 * different 시군구; 12 name the same one twice.
 *
 * That is not a finding about co-brokerage. It is what tells us the field
 * records districts rather than offices: co-brokerage between two offices in
 * one district is ordinary, so a field recording offices would show it in
 * bulk. `share` is therefore the rate at which co-brokerage CROSSES a
 * district line, not the co-brokerage rate, and the same-district kind cannot
 * be counted from this source.
 */
export const REACH_CO = {
  pairs: 30329,
  cross: 30317,
  same: 12,
  /** Share of all 중개거래 filings that name two districts. */
  share: 6.3,
} as const

/** The lowest 12, with the thickest inflow into each. */
export const REACH_LOW: readonly ReachDistrict[] = [
  { sido: '전남광주통합특별시', sgg: '강진군', rate: 18.9, legs: 243, origin: '여수시', originLegs: 195, originShare: 80.2, originKm: 85 },
  { sido: '전북특별자치도', sgg: '완주군', rate: 70.9, legs: 1355, origin: '전주시덕진구', originLegs: 304, originShare: 22.4, originKm: 11 },
  { sido: '전남광주통합특별시', sgg: '영암군', rate: 71.9, legs: 292, origin: '목포시', originLegs: 68, originShare: 23.3, originKm: 23 },
  { sido: '서울특별시', sgg: '중구', rate: 75.7, legs: 1220, origin: '성동구', originLegs: 122, originShare: 10, originKm: 4 },
  { sido: '대구광역시', sgg: '중구', rate: 78.7, legs: 2393, origin: '수성구', originLegs: 126, originShare: 5.3, originKm: 7 },
  { sido: '전남광주통합특별시', sgg: '동구', rate: 80.3, legs: 1307, origin: '북구', originLegs: 98, originShare: 7.5, originKm: 7 },
  { sido: '경기도', sgg: '의왕시', rate: 81.1, legs: 2622, origin: '안양시동안구', originLegs: 325, originShare: 12.4, originKm: 5 },
  { sido: '경기도', sgg: '성남시수정구', rate: 81.4, legs: 1831, origin: '성남시중원구', originLegs: 93, originShare: 5.1, originKm: 3 },
  { sido: '전남광주통합특별시', sgg: '목포시', rate: 82.2, legs: 2637, origin: '무안군', originLegs: 448, originShare: 17, originKm: 19 },
  { sido: '대구광역시', sgg: '남구', rate: 83, legs: 893, origin: '수성구', originLegs: 54, originShare: 6, originKm: 6 },
  { sido: '서울특별시', sgg: '용산구', rate: 83.1, legs: 1252, origin: '강남구', originLegs: 36, originShare: 2.9, originKm: 9 },
  { sido: '서울특별시', sgg: '동작구', rate: 83.1, legs: 3079, origin: '서초구', originLegs: 116, originShare: 3.8, originKm: 8 },
]
