/**
 * 계약갱신청구권을 쓴 갱신과 안 쓴 갱신, 보증금 인상률.
 *
 * GENERATED by scripts/build-renewal.mjs — do not hand-edit. It reads
 * 2940 cached responses from 국토교통부 아파트 전월세 실거래가
 * (2025-09 ~ 2026-08) and keeps only the renewals
 * that were 전세 before and 전세 after, because a deposit and a monthly rent
 * are not one number and converting between them would need a rate this file
 * would have to invent.
 *
 * WHAT THE NUMBERS SAY, and why the chart is a distribution rather than a
 * pair of bars: the medians are 4.9% and 3.9%. On an
 * average, invoking the right changes almost nothing. The difference is
 * entirely in the ceiling — p90 is 5% against 14.6%, and
 * 0.2% of invoked renewals exceeded 5% against 27.8%
 * of the rest. A bar chart of means would have shown two bars the same
 * height and been read as "the cap does nothing".
 *
 * Every share below is a percentage OF ITS OWN SERIES. The groups differ by
 * 3,386 contracts.
 */

export type RenewalSeries = {
  /** 갱신요구권 사용 여부. */
  readonly key: 'used' | 'notUsed'
  readonly n: number
  readonly median: number
  readonly p25: number
  readonly p75: number
  readonly p90: number
  /** Share that went DOWN, that stayed exactly flat, that landed in
      4.5–5.0%, and that passed 5%. Percentages of this series. */
  readonly cut: number
  readonly frozen: number
  readonly atCap: number
  readonly overCap: number
  /**
   * Share of the series per one-point bin. `bins[0]` is everything below
   * -5% and the last is everything above 20% — collected, not clipped,
   * because the tail is the finding.
   */
  readonly bins: readonly number[]
}

/** The first bin's lower edge and the last bin's upper edge. */
export const RENEWAL_BIN_FROM = -5
export const RENEWAL_BIN_TO = 20

/** 임대차 3법의 상한. The line the chart draws. */
export const RENEWAL_CAP = 5

export const RENEWAL_WINDOW = { from: '2025-09', to: '2026-08' } as const

/** What was read, and what was set aside doing it. */
export const RENEWAL_INTAKE = {
  rows: 988823,
  renewals: 333408,
  /** 갱신 rows where either side had a monthly rent. */
  mixed: 146440,
  /** 갱신 rows with no usable previous deposit. */
  unusable: 1012,
  kept: 185956,
} as const

export const RENEWAL_SERIES: readonly RenewalSeries[] = [
  {
    key: 'used',
    n: 94671,
    median: 4.9,
    p25: 2.9,
    p75: 5,
    p90: 5,
    cut: 2.7,
    frozen: 17.3,
    atCap: 62,
    overCap: 0.2,
    bins: [1.7, 0.3, 0.2, 0.2, 0.1, 0.1, 17.8, 1.1, 4.1, 6, 21.9, 46.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    key: 'notUsed',
    n: 91285,
    median: 3.9,
    p25: 0,
    p75: 5.9,
    p90: 14.6,
    cut: 5,
    frozen: 27.3,
    atCap: 18.8,
    overCap: 27.8,
    bins: [3.6, 0.4, 0.4, 0.2, 0.2, 0.3, 30.4, 6.2, 5.5, 3.3, 15.3, 9.4, 2.3, 2.1, 1.9, 1.6, 2.1, 1.6, 1.4, 1.1, 1.1, 1.1, 1, 0.7, 0.7, 0.5, 0.5, 5.3],
  },
]
