/**
 * 계약갱신청구권을 쓴 갱신과 안 쓴 갱신, 보증금 인상률.
 *
 * GENERATED by scripts/build-renewal.mjs — do not hand-edit. It reads
 * 2929 cached responses from 국토교통부 아파트 전월세 실거래가
 * (2025-09 ~ 2026-08) and keeps only the renewals
 * that were 전세 before and 전세 after, because a deposit and a monthly rent
 * are not one number and converting between them would need a rate this file
 * would have to invent.
 *
 * WHAT THE NUMBERS SAY, and why the chart is a distribution rather than a
 * pair of bars: the medians are 4.9% and 4.7%. On an
 * average, invoking the right changes almost nothing. The difference is
 * entirely in the ceiling — p90 is 5% against 15.5%, and
 * 0.2% of invoked renewals exceeded 5% against 30.7%
 * of the rest. A bar chart of means would have shown two bars the same
 * height and been read as "the cap does nothing".
 *
 * Every share below is a percentage OF ITS OWN SERIES. The groups differ by
 * 11,301 contracts.
 */

export type RenewalSeries = {
  /** 갱신요구권 사용 여부. */
  readonly key: 'used' | 'notUsed'
  readonly n: number
  readonly median: number
  readonly p25: number
  readonly p75: number
  readonly p90: number
  /** Share that went DOWN, that stayed exactly flat, that landed in
      4.5–5.0%, and that passed 5%. Percentages of this series. */
  readonly cut: number
  readonly frozen: number
  readonly atCap: number
  readonly overCap: number
  /**
   * Share of the series per one-point bin. `bins[0]` is everything below
   * -5% and the last is everything above 20% — collected, not clipped,
   * because the tail is the finding.
   */
  readonly bins: readonly number[]
}

/** The first bin's lower edge and the last bin's upper edge. */
export const RENEWAL_BIN_FROM = -5
export const RENEWAL_BIN_TO = 20

/** 임대차 3법의 상한. The line the chart draws. */
export const RENEWAL_CAP = 5

export const RENEWAL_WINDOW = { from: '2025-09', to: '2026-08' } as const

/** What was read, and what was set aside doing it. */
export const RENEWAL_INTAKE = {
  rows: 927209,
  renewals: 312963,
  /** 갱신 rows where either side had a monthly rent. */
  mixed: 139458,
  /** 갱신 rows with no usable previous deposit. */
  unusable: 928,
  kept: 172577,
} as const

export const RENEWAL_SERIES: readonly RenewalSeries[] = [
  {
    key: 'used',
    n: 91939,
    median: 4.9,
    p25: 3,
    p75: 5,
    p90: 5,
    cut: 2.6,
    frozen: 16.6,
    atCap: 62.8,
    overCap: 0.2,
    bins: [1.7, 0.3, 0.2, 0.2, 0.1, 0.1, 17, 1, 4.1, 6, 22.2, 47.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    key: 'notUsed',
    n: 80638,
    median: 4.7,
    p25: 0,
    p75: 6.9,
    p90: 15.5,
    cut: 5.2,
    frozen: 24.1,
    atCap: 20.8,
    overCap: 30.7,
    bins: [3.8, 0.5, 0.4, 0.2, 0.2, 0.3, 26.6, 5, 4.9, 3.6, 16.8, 10.3, 2.5, 2.3, 2.1, 1.7, 2.3, 1.8, 1.5, 1.2, 1.2, 1.2, 1.1, 0.8, 0.7, 0.5, 0.5, 5.9],
  },
]
