#!/usr/bin/env node
/**
 * Derive lib/renewal.data.ts from the rent cache.
 *
 * The question: 계약갱신청구권의 5% 상한이 실제로 구속력이 있는가.
 *
 * The comparison is INSIDE the renewals, not against new contracts. A new
 * contract has no previous contract, so it has no increase to measure — the
 * control group is the renewal that did NOT invoke the right, and it sits in
 * the same rows of the same file. `useRRRight` splits them.
 *
 * 전세→전세 ONLY. A deposit and a monthly rent are not one number, and
 * converting between them needs a 전월세전환율 this file would have to
 * invent. Dropping the mixed cases costs 140,386 of 312,963 renewals and
 * buys an increase rate that means exactly one thing. The counts of what was
 * dropped are published rather than quietly disappeared.
 *
 * Run after `node scripts/fetch-rtms.mjs rent <from> <to>`.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CACHE = join(ROOT, '.rtms-cache', 'rent')
const OUT = join(ROOT, 'lib', 'renewal.data.ts')

/* Bin edges. Below -5 and above 20 are collected rather than clipped: the
   tail is the finding, and a chart that cuts it off would answer its own
   question. */
const FROM = -5
const TO = 20

const money = (v) => {
  if (v === null || v === undefined) return null
  const s = String(v).replace(/,/g, '').trim()
  if (!s) return null
  const n = Number(s)
  return Number.isFinite(n) ? n : null
}

const files = readdirSync(CACHE).filter((f) => f.endsWith('.json'))
if (!files.length) {
  process.stderr.write('\n  ✗ .rtms-cache/rent 이 비어 있습니다 — fetch-rtms.mjs 를 먼저 도세요\n\n')
  process.exit(1)
}

let rows = 0
let renewals = 0
let mixed = 0
let unusable = 0
const months = new Set()
const series = { used: [], notUsed: [] }

for (const f of files) {
  for (const r of JSON.parse(readFileSync(join(CACHE, f), 'utf8'))) {
    rows++
    if (r.dealYear && r.dealMonth) {
      months.add(`${r.dealYear}-${String(r.dealMonth).padStart(2, '0')}`)
    }
    if (String(r.contractType ?? '').trim() !== '갱신') continue
    renewals++

    const now = money(r.deposit)
    const before = money(r.preDeposit)
    const rentNow = money(r.monthlyRent) ?? 0
    const rentBefore = money(r.preMonthlyRent) ?? 0
    if (!now || !before || before <= 0) { unusable++; continue }
    if (rentNow !== 0 || rentBefore !== 0) { mixed++; continue }

    const pct = ((now - before) / before) * 100
    series[String(r.useRRRight ?? '').trim() === '사용' ? 'used' : 'notUsed'].push(pct)
  }
}

const pct = (n, of) => Math.round((n / of) * 1000) / 10
const at = (sorted, p) => sorted[Math.min(sorted.length - 1, Math.round((p / 100) * (sorted.length - 1)))]

function summarise(key, values) {
  const v = [...values].sort((a, b) => a - b)
  const n = v.length
  /* One bin per point of increase, plus one at each end for everything
     beyond. `bins[0]` is < FROM, `bins[last]` is > TO. */
  const bins = new Array(TO - FROM + 3).fill(0)
  for (const x of v) {
    const i = x < FROM ? 0 : x > TO ? bins.length - 1 : Math.floor(x - FROM) + 1
    bins[i]++
  }
  return {
    key,
    n,
    median: Math.round(at(v, 50) * 10) / 10,
    p25: Math.round(at(v, 25) * 10) / 10,
    p75: Math.round(at(v, 75) * 10) / 10,
    p90: Math.round(at(v, 90) * 10) / 10,
    cut: pct(v.filter((x) => x < -0.01).length, n),
    frozen: pct(v.filter((x) => Math.abs(x) < 0.01).length, n),
    atCap: pct(v.filter((x) => x >= 4.5 && x <= 5.0).length, n),
    overCap: pct(v.filter((x) => x > 5.0).length, n),
    /* Share of the series, not a count: the two groups differ by 11,000
       contracts and a raw count would make the bigger one look taller
       everywhere. */
    bins: bins.map((c) => Math.round((c / n) * 1000) / 10),
  }
}

const used = summarise('used', series.used)
const notUsed = summarise('notUsed', series.notUsed)
const sorted = [...months].sort()

const ts = `/**
 * 계약갱신청구권을 쓴 갱신과 안 쓴 갱신, 보증금 인상률.
 *
 * GENERATED by scripts/build-renewal.mjs — do not hand-edit. It reads
 * ${files.length} cached responses from 국토교통부 아파트 전월세 실거래가
 * (${sorted[0]} ~ ${sorted[sorted.length - 1]}) and keeps only the renewals
 * that were 전세 before and 전세 after, because a deposit and a monthly rent
 * are not one number and converting between them would need a rate this file
 * would have to invent.
 *
 * WHAT THE NUMBERS SAY, and why the chart is a distribution rather than a
 * pair of bars: the medians are ${used.median}% and ${notUsed.median}%. On an
 * average, invoking the right changes almost nothing. The difference is
 * entirely in the ceiling — p90 is ${used.p90}% against ${notUsed.p90}%, and
 * ${used.overCap}% of invoked renewals exceeded 5% against ${notUsed.overCap}%
 * of the rest. A bar chart of means would have shown two bars the same
 * height and been read as "the cap does nothing".
 *
 * Every share below is a percentage OF ITS OWN SERIES. The groups differ by
 * ${Math.abs(used.n - notUsed.n).toLocaleString('en-US')} contracts.
 */

export type RenewalSeries = {
  /** 갱신요구권 사용 여부. */
  readonly key: 'used' | 'notUsed'
  readonly n: number
  readonly median: number
  readonly p25: number
  readonly p75: number
  readonly p90: number
  /** Share that went DOWN, that stayed exactly flat, that landed in
      4.5–5.0%, and that passed 5%. Percentages of this series. */
  readonly cut: number
  readonly frozen: number
  readonly atCap: number
  readonly overCap: number
  /**
   * Share of the series per one-point bin. \`bins[0]\` is everything below
   * ${FROM}% and the last is everything above ${TO}% — collected, not clipped,
   * because the tail is the finding.
   */
  readonly bins: readonly number[]
}

/** The first bin's lower edge and the last bin's upper edge. */
export const RENEWAL_BIN_FROM = ${FROM}
export const RENEWAL_BIN_TO = ${TO}

/** 임대차 3법의 상한. The line the chart draws. */
export const RENEWAL_CAP = 5

export const RENEWAL_WINDOW = { from: '${sorted[0]}', to: '${sorted[sorted.length - 1]}' } as const

/** What was read, and what was set aside doing it. */
export const RENEWAL_INTAKE = {
  rows: ${rows},
  renewals: ${renewals},
  /** 갱신 rows where either side had a monthly rent. */
  mixed: ${mixed},
  /** 갱신 rows with no usable previous deposit. */
  unusable: ${unusable},
  kept: ${used.n + notUsed.n},
} as const

export const RENEWAL_SERIES: readonly RenewalSeries[] = [
${[used, notUsed]
  .map(
    (s) => `  {
    key: '${s.key}',
    n: ${s.n},
    median: ${s.median},
    p25: ${s.p25},
    p75: ${s.p75},
    p90: ${s.p90},
    cut: ${s.cut},
    frozen: ${s.frozen},
    atCap: ${s.atCap},
    overCap: ${s.overCap},
    bins: [${s.bins.join(', ')}],
  },`,
  )
  .join('\n')}
]
`

writeFileSync(OUT, ts, 'utf8')
process.stdout.write(`
  RENEWAL
  ${'-'.repeat(70)}
  ${files.length} 응답 · ${rows.toLocaleString('ko-KR')} 행 · ${sorted[0]} ~ ${sorted[sorted.length - 1]} (${sorted.length}개월)
  갱신 ${renewals.toLocaleString('ko-KR')} → 전세→전세 ${(used.n + notUsed.n).toLocaleString('ko-KR')} (월세 섞임 ${mixed.toLocaleString('ko-KR')} · 종전값 없음 ${unusable.toLocaleString('ko-KR')})
  ${'-'.repeat(70)}
  사용     n=${used.n.toLocaleString('ko-KR').padStart(7)}  중앙 ${used.median}%  p90 ${used.p90}%  5%초과 ${used.overCap}%
  미사용   n=${notUsed.n.toLocaleString('ko-KR').padStart(7)}  중앙 ${notUsed.median}%  p90 ${notUsed.p90}%  5%초과 ${notUsed.overCap}%
  ${'-'.repeat(70)}
  wrote lib/renewal.data.ts
`)
