#!/usr/bin/env node
/**
 * The real complex roster, from the trade and rent caches.
 *
 * This is the only layer of the revenue dashboard that is NOT invented. Every
 * name, province, district, 법정동 and completion year below was filed with
 * 국토교통부; what the dashboard puts on top of them — contracts, prices,
 * revenue, churn, a sales org — is generated by scripts/build-bi.mjs and is
 * not real. The split is the whole point: a management app's per-complex
 * revenue cannot be public data, but the market it sells into can be, and a
 * penetration rate is worthless if its DENOMINATOR is invented too.
 *
 * HOUSEHOLD COUNT IS NOT IN THE FILINGS. A transaction record carries the
 * complex name, the 법정동, the completion year, one unit's floor, one unit's
 * area and sometimes a building number. It never carries how many households
 * the complex has, which is the one number every per-household price on the
 * dashboard needs. So it is estimated, and the estimate is split in two so
 * that neither half claims what it cannot:
 *
 *   ORDER IS OBSERVED. A complex seen with 14 buildings and a 27th floor
 *   really is bigger than one seen with 2 buildings and a 5th floor. Three
 *   signals present for every complex — corrected top floor, filing volume,
 *   distinct area bands — are combined into one score, and the roster is
 *   ranked by it.
 *
 *   SCALE IS DECLARED. The rank is then mapped onto a log-normal this file
 *   CHOOSES (median 640, sigma 0.889, clamped to 60..6000). That is a
 *   decision, not a measurement, and it is written here rather than buried
 *   in a constant because a reader has to be able to reject it.
 *
 * WHY THE BUILDING COUNT IS A HOLDOUT RATHER THAN AN INPUT. `aptDong` is
 * populated on 42% of complexes and blank on the rest. Scoring the two
 * subsets with different formulas would rank them on different scales and
 * the join would be meaningless — a "big" complex in the observed half and
 * one in the unobserved half would not be the same claim. So the score uses
 * only what everything has, and the building count is spent CHECKING it: the
 * weights are fitted against observed building counts by least squares, and
 * the fit's R^2 and Spearman rho are printed and published. A score nobody
 * validated is a guess with arithmetic on it.
 *
 * TWO ORDER-STATISTIC CORRECTIONS, because both raw signals are downward
 * biased by construction. The tallest floor ever FILED is not the building's
 * top floor — it is the maximum of n draws, so the true top is about
 * n+1 over n times it. The number of DISTINCT buildings filed is the coupon
 * collector's problem run backwards: seeing k of them in n draws implies
 * k = D(1-(1-1/D)^n), which is solved for D by bisection. Neither correction
 * touches the published scale; they only stop a thinly traded complex from
 * ranking below an identical one that traded more.
 *
 * NOTHING HERE IS RANDOM. Household count is a deterministic function of
 * rank, so this script needs no seed and a rerun reproduces its output
 * byte for byte. The seed belongs to build-bi.mjs, which invents things.
 *
 * Run after `node scripts/fetch-rtms.mjs`. The cache is gitignored and
 * refetchable; the roster it derives is committed, exactly as
 * lib/prices.data.ts is.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CACHES = ['trade', 'rent'].map((k) => join(ROOT, '.rtms-cache', k))
const OUT_DIR = join(ROOT, 'public', 'data', 'bi', 'roster')
const OUT_TS = join(ROOT, 'lib', 'bi.roster.data.ts')

/* ---- the declared scale, and what pins it -------------------------- */

/**
 * Household count is pinned by two anchors, not by a shape.
 *
 * THE FIRST DRAFT OF THIS FILE ASSUMED A LOG-NORMAL — median 640, sigma
 * 0.889 — and it was wrong in a way worth leaving on the record, because
 * nothing in the estimator itself could have caught it. Those parameters
 * implied 33.8 million households across 36,040 complexes, which at 2.3
 * people each is 164% of the registered population of the districts they
 * sit in. The arithmetic was fine. The distribution was simply invented, and
 * an invented distribution can be internally consistent and still describe
 * more people than exist.
 *
 * So the shape is no longer assumed. Households are `exp(a + b * score)` on
 * the score the previous section built, and the two free parameters are
 * pinned by two statements that can each be argued with:
 *
 *   TOTAL — the roster's households, at HH_PERSONS people each, come to
 *   HH_SHARE of the registered residents of the districts it covers.
 *   Registered population is not a guess: it is already in this repository,
 *   measured, in lib/cartogram.districts.data.ts (행정안전부 주민등록인구).
 *   That fixes `a` for any `b`.
 *
 *   CEILING — the largest complex in the roster has HH_MAX households.
 *   That fixes `b`, by bisection.
 *
 * HH_SHARE IS DELIBERATELY BELOW the share of Koreans who live in
 * apartments. This roster holds only complexes that FILED a sale or a lease
 * in the window; a complex where nobody moved for twelve months is not in
 * it, and its residents are in the population denominator anyway. A share
 * set at the true apartment share would therefore be too high, and every
 * per-household price on the dashboard would be too low.
 *
 * ALL THREE ARE DECISIONS. They are at the top of the file, with their
 * consequences written out, because they are the numbers a reader should
 * reject first. `pnpm check:bi` asserts the realised share stays inside a
 * band around HH_SHARE, so changing one of these and not the others fails
 * the build instead of quietly rescaling the dashboard.
 */
const HH_SHARE = 0.42
const HH_PERSONS = 2.3
const HH_MAX = 6000
const HH_MIN = 24

/**
 * Households below which a complex has nothing to sell to.
 *
 * An apartment management app is bought by a 관리사무소, and the smallest
 * buildings in the filings do not have one. The roster keeps them — they are
 * real and dropping them would overstate market coverage — but penetration
 * is reported against the addressable subset as well as the whole, because a
 * denominator that includes complexes nobody could ever sign is a
 * denominator that makes the sales team look worse than it is.
 */
const ADDRESSABLE = 150

/**
 * Tier edges, in households. The dashboard's size axis.
 *
 * `sub` is not a size, it is a market boundary — below ADDRESSABLE a complex
 * has no management office and cannot be sold to at all. It gets its own
 * class rather than being folded into `small` because half the roster sits
 * there, and a `small` tier that mixed a 90-household walk-up with a
 * 380-household estate would report an average that describes neither.
 *
 * The four real tiers are cut on round numbers rather than the roster's own
 * quantiles. Quantile cuts would move every time the cache is refetched,
 * which would silently rewrite the dashboard's segments between builds.
 */
const TIERS = [
  { id: 'sub', to: 150 },
  { id: 'small', to: 400 },
  { id: 'mid', to: 900 },
  { id: 'large', to: 2000 },
  { id: 'xlarge', to: Infinity },
]

const tierOf = (hh) => TIERS.find((t) => hh < t.to).id

/* One number, two names. `sub` is defined as "below ADDRESSABLE", so if the
   two ever drift the roster would call a complex addressable and tier it as
   sub in the same row. */
if (ADDRESSABLE !== TIERS[0].to) {
  process.stderr.write('\n  x ADDRESSABLE and the sub tier edge must be the same number\n\n')
  process.exit(1)
}

/* ---- small numerics ------------------------------------------------ */

const nfc = (v) => String(v ?? '').normalize('NFC').trim()
const num = (v) => {
  const n = Number(v)
  return Number.isFinite(n) ? n : null
}
const round = (v, d = 2) => Math.round(v * 10 ** d) / 10 ** d

/**
 * Inverse normal CDF, Acklam's rational approximation.
 *
 * Needed because the household scale is a quantile transform of the rank and
 * there is no erfinv in the standard library. Absolute error is below
 * 1.15e-9 across the open interval — four orders of magnitude tighter than
 * the nearest household, so it contributes nothing to the estimate's error
 * next to the two declared anchors.
 */
function probit(pr) {
  const a = [-3.969683028665376e1, 2.209460984245205e2, -2.759285104469687e2,
    1.38357751867269e2, -3.066479806614716e1, 2.506628277459239]
  const b = [-5.447609879822406e1, 1.615858368580409e2, -1.556989798598866e2,
    6.680131188771972e1, -1.328068155288572e1]
  const c = [-7.784894002430293e-3, -3.223964580411365e-1, -2.400758277161838,
    -2.549732539343734, 4.374664141464968, 2.938163982698783]
  const d = [7.784695709041462e-3, 3.224671290700398e-1, 2.445134137142996,
    3.754408661907416]
  const low = 0.02425
  if (pr < low) {
    const q = Math.sqrt(-2 * Math.log(pr))
    return (((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) /
      ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1)
  }
  if (pr > 1 - low) return -probit(1 - pr)
  const q = pr - 0.5
  const r = q * q
  return ((((((a[0] * r + a[1]) * r + a[2]) * r + a[3]) * r + a[4]) * r + a[5]) * q) /
    (((((b[0] * r + b[1]) * r + b[2]) * r + b[3]) * r + b[4]) * r + 1)
}

/**
 * The coupon collector, inverted.
 *
 * Seeing `k` distinct buildings across `n` filings that carry a building
 * number does not mean the complex has `k` buildings — it means
 * k = D(1-(1-1/D)^n) for the D it does have. Bisection rather than a closed
 * form because there isn't one. Bounded at 120: past that the equation is
 * flat in D and the answer would be noise dressed as a measurement.
 */
function couponInverse(k, n) {
  if (!(k > 0) || !(n > 0)) return null
  if (k >= n) return k
  const seen = (D) => D * (1 - Math.pow(1 - 1 / D, n))
  let lo = k
  let hi = Math.min(120, Math.max(k * 4, k + 1))
  if (seen(hi) < k) return hi
  for (let i = 0; i < 60; i++) {
    const mid = (lo + hi) / 2
    if (seen(mid) < k) lo = mid
    else hi = mid
  }
  return (lo + hi) / 2
}

/** Least squares with an intercept, by Gaussian elimination on X'X. */
function ols(X, y) {
  const p = X[0].length + 1
  const A = Array.from({ length: p }, () => new Array(p + 1).fill(0))
  for (let r = 0; r < X.length; r++) {
    const row = [1, ...X[r]]
    for (let i = 0; i < p; i++) {
      for (let j = 0; j < p; j++) A[i][j] += row[i] * row[j]
      A[i][p] += row[i] * y[r]
    }
  }
  for (let i = 0; i < p; i++) {
    let piv = i
    for (let r = i + 1; r < p; r++) if (Math.abs(A[r][i]) > Math.abs(A[piv][i])) piv = r
    ;[A[i], A[piv]] = [A[piv], A[i]]
    const d = A[i][i]
    if (!d) continue
    for (let j = i; j <= p; j++) A[i][j] /= d
    for (let r = 0; r < p; r++) {
      if (r === i) continue
      const f = A[r][i]
      if (!f) continue
      for (let j = i; j <= p; j++) A[r][j] -= f * A[i][j]
    }
  }
  return A.map((r) => r[p])
}

/** Spearman rho — rank correlation, ties averaged. */
function spearman(a, b) {
  const rank = (xs) => {
    const idx = xs.map((v, i) => [v, i]).sort((x, y) => x[0] - y[0])
    const out = new Array(xs.length)
    let i = 0
    while (i < idx.length) {
      let j = i
      while (j + 1 < idx.length && idx[j + 1][0] === idx[i][0]) j++
      const r = (i + j) / 2 + 1
      for (let k = i; k <= j; k++) out[idx[k][1]] = r
      i = j + 1
    }
    return out
  }
  const ra = rank(a)
  const rb = rank(b)
  const n = ra.length
  const ma = ra.reduce((s, v) => s + v, 0) / n
  const mb = rb.reduce((s, v) => s + v, 0) / n
  let num = 0, da = 0, db = 0
  for (let i = 0; i < n; i++) {
    const x = ra[i] - ma
    const y = rb[i] - mb
    num += x * y
    da += x * x
    db += y * y
  }
  return num / Math.sqrt(da * db)
}

/* ---- 1. read the caches -------------------------------------------- */

const lawd = JSON.parse(readFileSync(join(ROOT, 'scripts', 'rtms', 'lawd.json'), 'utf8'))
const byCode = new Map(lawd.map((r) => [String(r.lawd), { sido: nfc(r.sido), sgg: nfc(r.sgg) }]))

/* Only districts the cartogram can draw. The grid is the same 245 cells the
   brokerage and price maps use — a complex in a district with no hexagon
   would be in the roster and absent from every map on the page.

   POPULATION COMES WITH IT, and that is what makes the household scale
   checkable rather than merely stated. `pop` here is 행정안전부 주민등록인구
   as of 2026-07-31, already measured and already in this repository; the
   roster's household total is pinned against it below. Reading it from the
   same file as the grid means the two can never be out of step. */
const dsrc = readFileSync(join(ROOT, 'lib', 'cartogram.districts.data.ts'), 'utf8')
const grid = [
  ...dsrc.matchAll(/sido: '([^']+)', sgg: '([^']+)', row: \d+, col: \d+, brokers: \d+, pop: (\d+)/g),
].map((m) => ({ sido: nfc(m[1]), sgg: nfc(m[2]), pop: +m[3] }))
if (grid.length < 200) {
  process.stderr.write(`\n  x read ${grid.length} districts from cartogram.districts.data.ts\n\n`)
  process.exit(1)
}
const onGrid = new Set(grid.map((g) => `${g.sido}\t${g.sgg}`))
const popOf = new Map(grid.map((g) => [`${g.sido}\t${g.sgg}`, g.pop]))

const complexes = new Map()
const intake = { files: 0, rows: 0, skippedNoCode: 0, skippedOffGrid: 0, skippedBlank: 0 }

for (const dir of CACHES) {
  if (!existsSync(dir)) {
    process.stderr.write(`\n  x ${dir} is missing — run node scripts/fetch-rtms.mjs\n\n`)
    process.exit(1)
  }
  for (const f of readdirSync(dir).filter((n) => n.endsWith('.json'))) {
    let arr
    try { arr = JSON.parse(readFileSync(join(dir, f), 'utf8')) } catch { continue }
    if (!Array.isArray(arr)) continue
    intake.files++
    for (const r of arr) {
      intake.rows++
      const code = String(r.sggCd ?? '').trim()
      const place = byCode.get(code)
      if (!place) { intake.skippedNoCode++; continue }
      if (!onGrid.has(`${place.sido}\t${place.sgg}`)) { intake.skippedOffGrid++; continue }
      const name = nfc(r.aptNm)
      const umd = nfc(r.umdNm)
      if (!name || !umd) { intake.skippedBlank++; continue }

      const key = `${code}\t${umd}\t${name}`
      let c = complexes.get(key)
      if (!c) {
        c = {
          code, sido: place.sido, sgg: place.sgg, umd, name,
          year: null, n: 0, floorN: 0, maxFloor: 0,
          dongN: 0, dongs: new Set(), bands: new Set(),
        }
        complexes.set(key, c)
      }
      c.n++
      const y = num(r.buildYear)
      if (y && y > 1900 && y < 2100) c.year = c.year === null ? y : Math.min(c.year, y)
      const fl = num(r.floor)
      if (fl && fl > 0) { c.floorN++; if (fl > c.maxFloor) c.maxFloor = fl }
      const dg = num(r.aptDong)
      if (dg && dg > 0) { c.dongN++; c.dongs.add(dg) }
      const ar = num(r.excluUseAr)
      if (ar && ar > 0) c.bands.add(Math.round(ar / 5) * 5)
    }
  }
}

const all = [...complexes.values()]
if (all.length < 1000) {
  process.stderr.write(`\n  x only ${all.length} complexes — the cache looks empty\n\n`)
  process.exit(1)
}

/* ---- 2. correct the two biased signals ----------------------------- */

for (const c of all) {
  /* Max of n draws underestimates the top floor by about n/(n+1). Capped at
     1.4x: with one filing the raw correction would double the building. */
  const lift = c.floorN > 0 ? Math.min(1.4, (c.floorN + 1) / c.floorN) : 1
  c.floorHat = c.maxFloor > 0 ? c.maxFloor * lift : null
  c.dongHat = couponInverse(c.dongs.size, c.dongN)
}

/* ---- 3. fit the score on the observed half, apply to all ----------- */

/* Predictors present for every complex. `bands` is distinct 5 m2 area bands
   filed — a proxy for how many unit types the complex has, which tracks size
   independently of how often it trades. */
const feat = (c) => [
  Math.log(c.floorHat ?? 1),
  Math.log(c.n),
  Math.log(c.bands.size + 1),
]

/* The holdout: complexes whose building count is filed often enough for the
   coupon inverse to mean something. */
const fitSet = all.filter((c) => c.dongHat !== null && c.dongN >= 3 && c.floorHat !== null)
const W = ols(fitSet.map(feat), fitSet.map((c) => Math.log(c.dongHat)))

const predict = (c) => W[0] + W[1] * feat(c)[0] + W[2] * feat(c)[1] + W[3] * feat(c)[2]

/* R^2 and rho on the holdout, both reported. R^2 says how much of the
   building count these three signals explain; rho says whether the ORDER
   survives, which is the only thing the roster uses. */
const yObs = fitSet.map((c) => Math.log(c.dongHat))
const yHat = fitSet.map(predict)
const ybar = yObs.reduce((s, v) => s + v, 0) / yObs.length
let ssRes = 0, ssTot = 0
for (let i = 0; i < yObs.length; i++) {
  ssRes += (yObs[i] - yHat[i]) ** 2
  ssTot += (yObs[i] - ybar) ** 2
}
const R2 = 1 - ssRes / ssTot
const RHO = spearman(yObs, yHat)

/* The score: estimated log of buildings times floors. Floors enter twice on
   purpose — once as a predictor of the building count and once as itself,
   because the thing being ranked is the product. */
for (const c of all) c.score = predict(c) + Math.log(c.floorHat ?? 1)

/* ---- 4. pin the scale against the population ----------------------- */

/* Sorted by score, then by a stable key so that two complexes with an
   identical score do not swap places between runs on different platforms. */
all.sort((a, b) => a.score - b.score || (a.code + a.umd + a.name < b.code + b.umd + b.name ? -1 : 1))

/* The denominator. Only districts the roster actually reaches: pinning
   against all 245 would charge the estimate for the population of districts
   where it found no complexes at all, and push every household count down. */
const coveredKeys = new Set(all.map((c) => `${c.sido}\t${c.sgg}`))
const coveredPop = [...coveredKeys].reduce((sum, k) => sum + (popOf.get(k) ?? 0), 0)
const target = (coveredPop * HH_SHARE) / HH_PERSONS

/**
 * The scale is a quantile transform of the RANK, not of the score.
 *
 * This is the one place the distinction is load-bearing, so it is worth
 * being explicit about. The score was validated one way and one way only:
 * Spearman ${round1(RHO, 3)} against filed building counts, which is a statement about
 * ORDER. Its magnitude was never validated and could not be — it is a
 * least-squares prediction of log building count with a log floor count
 * added to it, a quantity in no unit anybody could name. Exponentiating it
 * would have treated its spread as evidence, and its spread is an artefact
 * of the fit.
 *
 * So the score is spent entirely on sorting, and the shape comes from a
 * log-normal — the usual shape for building stock, and stated as an
 * assumption rather than smuggled in as arithmetic. Its two parameters are
 * not assumed: they are solved from the two anchors at the top of this file.
 *
 *   mu + sigma * z(top)          = log(HH_MAX)          the ceiling
 *   sum of exp(mu + sigma * z_i) = target               the total
 *
 * The second gives mu in closed form for any sigma, and the composition is
 * monotone increasing in sigma — a heavier tail puts more of a fixed total
 * into the top complex — so bisection finds the sigma that satisfies both.
 */
const N = all.length
const Z = all.map((_, i) => probit((i + 0.5) / N))
const zTop = Z[N - 1]

/* Shifted by zTop before exponentiating: raw exp(sigma * z) overflows for
   large sigma and the bisection would then compare NaN. After the shift the
   sum is bounded by N and the top value falls out as target / sum. */
const topFor = (sigma) => target / Z.reduce((acc, z) => acc + Math.exp(sigma * (z - zTop)), 0)

let lo = 0
let hi = 4
if (topFor(hi) < HH_MAX) {
  process.stderr.write(`\n  x cannot reach ${HH_MAX} households even at sigma ${hi}\n\n`)
  process.exit(1)
}
for (let i = 0; i < 60; i++) {
  const mid = (lo + hi) / 2
  if (topFor(mid) < HH_MAX) lo = mid
  else hi = mid
}
const SIGMA = (lo + hi) / 2
const MU = Math.log(topFor(SIGMA)) - SIGMA * zTop

all.forEach((c, i) => {
  const hh = Math.exp(MU + SIGMA * Z[i])
  /* Rounded to even households, because a complex with an odd household
     count is not a fact this estimate is entitled to assert. */
  c.hh = Math.max(HH_MIN, Math.min(HH_MAX, Math.round(hh / 2) * 2))
  c.tier = tierOf(c.hh)
  c.basis = c.dongHat !== null && c.dongN >= 3 ? 'checked' : 'scored'
  c.addressable = c.hh >= ADDRESSABLE
})

/* What the clamps and the rounding actually produced, as opposed to what the
   solve aimed at. The gate reads this, not `target`. */
const hhTotal = all.reduce((s, c) => s + c.hh, 0)
const realisedShare = (hhTotal * HH_PERSONS) / coveredPop

/* ---- 5. emit one file per district, plus the aggregate ------------- */

const byDistrict = new Map()
for (const c of all) {
  const list = byDistrict.get(c.code)
  if (list) list.push(c)
  else byDistrict.set(c.code, [c])
}

for (const f of readdirSync(OUT_DIR).filter((n) => n.endsWith('.json'))) {
  if (!byDistrict.has(f.replace('.json', ''))) {
    writeFileSync(join(OUT_DIR, f), '[]', 'utf8')
  }
}

let bytes = 0
for (const [code, list] of byDistrict) {
  /* Short keys and a fixed order, matching public/data/umd. `i` is the id the
     contract layer joins on; it is the district code plus a per-district
     index rather than a global counter, so adding a district cannot renumber
     every complex in the country. */
  list.sort((a, b) => (a.umd + a.name < b.umd + b.name ? -1 : 1))
  /* No tier field. It is `ROSTER_TIERS.find(t => h < t.to)` and storing it
     beside `h` would be the same fact twice — 500 KB of it across the roster,
     and two places for it to disagree. Same reason lib/tokens.data.ts records
     what a colour promises and leaves the hex in the stylesheet. */
  const json = JSON.stringify(
    list.map((c, k) => ({
      i: `${code}-${String(k).padStart(4, '0')}`,
      u: c.umd, n: c.name, y: c.year, h: c.hh, b: c.basis,
    })),
  )
  bytes += Buffer.byteLength(json)
  writeFileSync(join(OUT_DIR, `${code}.json`), json, 'utf8')
  for (let k = 0; k < list.length; k++) list[k].id = `${code}-${String(k).padStart(4, '0')}`
}

const tierCounts = Object.fromEntries(TIERS.map((t) => [t.id, all.filter((c) => c.tier === t.id).length]))
const checked = all.filter((c) => c.basis === 'checked').length
const years = all.map((c) => c.year).filter((y) => y !== null).sort((a, b) => a - b)
const hhs = all.map((c) => c.hh).sort((a, b) => a - b)
const at = (p) => hhs[Math.min(hhs.length - 1, Math.floor(hhs.length * p))]

/* Per-district totals — this is what the page inlines. The market's
   denominator, one row per hexagon on the cartogram. Districts the roster
   never reached keep a zero row rather than being dropped: the cartogram has
   a hexagon for all 245, and a missing row would draw as a hole that reads
   like an error instead of like an absence. */
const codeOf = new Map([...byCode.entries()].map(([code, pl]) => [`${pl.sido}\t${pl.sgg}`, code]))
const districtRows = grid.map((g) => {
  const code = codeOf.get(`${g.sido}\t${g.sgg}`) ?? ''
  const list = byDistrict.get(code) ?? []
  return {
    code, sido: g.sido, sgg: g.sgg, pop: g.pop,
    complexes: list.length,
    addressable: list.filter((c) => c.addressable).length,
    households: list.reduce((s, c) => s + c.hh, 0),
  }
})
const covered = districtRows.filter((d) => d.complexes > 0).length
const addressable = all.filter((c) => c.addressable).length
const nf = (v) => v.toLocaleString('en-US')
const round1 = (v, d) => (Math.round(v * 10 ** d) / 10 ** d).toFixed(d)

const ts = `/**
 * The market this dashboard sells into. Real, and the only real layer.
 *
 * GENERATED by scripts/build-roster.mjs — do not hand-edit.
 *
 * ${nf(all.length)} apartment complexes filed with 국토교통부, across ${covered} of
 * ${grid.length} districts and ${nf(new Set(all.map((c) => c.code + c.umd)).size)} 법정동. Name, province, district,
 * 법정동 and completion year are as filed. Everything the revenue dashboard
 * puts on top of them — contracts, unit prices, revenue, churn and the sales
 * organisation — is generated by scripts/build-bi.mjs and is NOT real. This
 * file exists so that the one figure a synthetic dataset cannot fake has a
 * true denominator: penetration is contracted complexes over ${nf(all.length)},
 * and that ${nf(all.length)} was counted, not chosen.
 *
 * HOUSEHOLD COUNT IS NOT FILED and is therefore estimated in two halves that
 * are labelled differently because they claim different things.
 *
 * THE ORDER IS OBSERVED. Corrected top floor, filing volume and distinct
 * area bands combine into one score, whose weights are fitted by least
 * squares against the building counts that ARE filed — ${nf(fitSet.length)}
 * complexes, R^2 ${round1(R2, 3)}, Spearman ${round1(RHO, 3)}. Spearman is the number
 * that matters and R^2 is published beside it on purpose: only the RANKING
 * reaches this file, so how much variance the fit explains is less
 * interesting than whether it puts the complexes in the right order. At
 * ${round1(RHO, 3)} it mostly does, and it does not pretend to more.
 *
 * THE SCALE IS PINNED, not shaped. Households are exp(a + b * score) with
 * the two parameters solved from two anchors rather than assumed: the total
 * comes to ${round1(realisedShare * 100, 1)}% of the registered residents of the covered
 * districts at ${HH_PERSONS} people per household, and the largest complex has
 * ${nf(HH_MAX)}. Registered population is measured, not guessed — it is
 * lib/cartogram.districts.data.ts, 행정안전부 주민등록인구 2026-07-31, the same
 * ${nf(coveredPop)} people the brokerage map divides by.
 *
 * AN EARLIER DRAFT ASSUMED A LOG-NORMAL and got this wrong by a factor of
 * four: median 640 with sigma 0.889 implied 33.8 million households, which is
 * 164% of the population of the districts holding them. It is recorded here
 * because the failure is instructive — the estimator was internally
 * consistent and nothing inside it could have noticed. Only a number from
 * outside could, which is why one is now load-bearing and why
 * \`pnpm check:bi\` asserts the realised share every build.
 *
 * ${nf(checked)} complexes carry \`basis: 'checked'\` — their building count was
 * filed often enough to validate the score against. The other
 * ${nf(all.length - checked)} are \`'scored'\`. Both are ranked by the same formula,
 * so the two are comparable; the flag records which ones the formula was
 * answerable to.
 *
 * ${nf(addressable)} of ${nf(all.length)} are ADDRESSABLE — at least ${ADDRESSABLE}
 * estimated households, the size below which a complex has no management
 * office to sell to. Penetration is reported against both, because a
 * denominator including complexes nobody could ever sign makes the sales
 * team look worse than it is, and one excluding them hides how much of the
 * country the product cannot reach.
 *
 * Per-complex rows are not here. ${nf(all.length)} of them are ${nf(Math.round(bytes / 1024))} KB
 * of JSON under public/data/bi/roster/, one file per district, fetched when a
 * district is opened — the same arrangement public/data/umd uses and for the
 * same reason.
 */

export type RosterDistrict = {
  /** 법정동코드 5자리, the key the roster files are named by. */
  readonly code: string
  readonly sido: string
  readonly sgg: string
  /** 행정안전부 주민등록인구. Measured, and what the scale is pinned against. */
  readonly pop: number
  /** Complexes filed in this district. The market's denominator. */
  readonly complexes: number
  /** Of those, at or above ROSTER_ADDRESSABLE households. */
  readonly addressable: number
  /** Sum of estimated households. Estimated — see the note above. */
  readonly households: number
}

/** Household tiers, in households. The dashboard's size axis. */
export const ROSTER_TIERS = [
${TIERS.map((t) => `  { id: '${t.id}', to: ${t.to === Infinity ? 'Infinity' : t.to} },`).join('\n')}
] as const

export type RosterTier = (typeof ROSTER_TIERS)[number]['id']

/** Households below which a complex has no management office to sell to. */
export const ROSTER_ADDRESSABLE = ${ADDRESSABLE}

/**
 * The declared half of the household estimate, published so it can be
 * rejected. \`share\` and \`persons\` pin the total against measured
 * population; \`max\` pins the ceiling. Nothing here was fitted — the filings
 * carry no household counts to fit against.
 */
export const ROSTER_SCALE = {
  /** Target share of covered registered residents. A decision. */
  share: ${HH_SHARE},
  /** Persons per apartment household. A decision. */
  persons: ${HH_PERSONS},
  /** Households in the largest complex. A decision. */
  max: ${HH_MAX},
  /** Floor, below which the estimate is not published as a count. */
  min: ${HH_MIN},
  /** What the solve actually produced, after clamping and rounding. */
  realisedShare: ${round1(realisedShare, 4)},
  /** Registered residents of the ${covered} covered districts. Measured. */
  coveredPop: ${coveredPop},
} as const

/** The observed half: how well three universal signals track filed buildings. */
export const ROSTER_FIT = {
  /** Complexes with enough filed building numbers to fit against. */
  holdout: ${fitSet.length},
  r2: ${round1(R2, 3)},
  spearman: ${round1(RHO, 3)},
} as const

/** What was read, and what was set aside doing it. */
export const ROSTER_INTAKE = {
  files: ${intake.files},
  rows: ${intake.rows},
  complexes: ${all.length},
  addressable: ${addressable},
  umd: ${new Set(all.map((c) => c.code + c.umd)).size},
  districts: ${grid.length},
  covered: ${covered},
  /** Filings whose 법정동코드 is not one of the ${grid.length}. */
  offGrid: ${intake.skippedOffGrid},
  /** Filings with no complex name or no 법정동. */
  blank: ${intake.skippedBlank},
  /** Complexes whose score was validated against filed building counts. */
  checked: ${checked},
  bytes: ${bytes},
} as const

/** Estimated households across the roster, at five points. */
export const ROSTER_HOUSEHOLDS = {
  total: ${hhTotal},
  p10: ${at(0.1)},
  median: ${at(0.5)},
  p90: ${at(0.9)},
  max: ${hhs[hhs.length - 1]},
} as const

/** Completion years, as filed. */
export const ROSTER_YEARS = {
  known: ${years.length},
  min: ${years[0]},
  median: ${years[years.length >> 1]},
  max: ${years[years.length - 1]},
} as const

/** Complexes per tier. */
export const ROSTER_TIER_COUNTS: Readonly<Record<RosterTier, number>> = {
${TIERS.map((t) => `  ${t.id}: ${tierCounts[t.id]},`).join('\n')}
} as const

/** One row per hexagon. Districts with no filed complexes keep their zero. */
export const ROSTER_DISTRICTS: readonly RosterDistrict[] = [
${districtRows
  .map(
    (d) =>
      `  { code: '${d.code}', sido: '${d.sido}', sgg: '${d.sgg}', pop: ${d.pop},` +
      ` complexes: ${d.complexes}, addressable: ${d.addressable}, households: ${d.households} },`,
  )
  .join('\n')}
]
`

writeFileSync(OUT_TS, ts, 'utf8')

const pct = (a, b) => `${((a / b) * 100).toFixed(1)}%`
process.stdout.write(`
  COMPLEX ROSTER — real, and the only real layer
  ${'-'.repeat(70)}
  read        ${nf(intake.files)} files, ${nf(intake.rows)} filings
  set aside   off-grid ${nf(intake.skippedOffGrid)} - blank ${nf(intake.skippedBlank)}
  complexes   ${nf(all.length)} in ${covered}/${grid.length} districts, ${nf(new Set(all.map((c) => c.code + c.umd)).size)} 법정동
  addressable ${nf(addressable)} (${pct(addressable, all.length)}) at >= ${ADDRESSABLE} households
  years       ${years[0]} .. ${years[years.length - 1]} (median ${years[years.length >> 1]}), known ${pct(years.length, all.length)}
  ${'-'.repeat(70)}
  score fit   holdout ${nf(fitSet.length)} (${pct(fitSet.length, all.length)}) - R2 ${round1(R2, 3)} - rho ${round1(RHO, 3)}
  weights     const ${round1(W[0], 3)} - logFloor ${round1(W[1], 3)} - logVolume ${round1(W[2], 3)} - logBands ${round1(W[3], 3)}
  ${'-'.repeat(70)}
  scale       PINNED, not assumed - log-normal on rank, mu ${round1(MU, 4)} sigma ${round1(SIGMA, 4)}
              (median ${nf(Math.round(Math.exp(MU)))} implied by the two anchors, not chosen)
  anchor 1    total = ${HH_SHARE} of covered pop at ${HH_PERSONS}/household
              covered pop ${nf(coveredPop)} - target ${nf(Math.round(target))} households
              realised    ${nf(hhTotal)} = ${pct(hhTotal * HH_PERSONS, coveredPop)} of covered pop
  anchor 2    largest complex = ${nf(HH_MAX)} households
  households  p10 ${nf(at(0.1))} - median ${nf(at(0.5))} - p90 ${nf(at(0.9))} - max ${nf(hhs[hhs.length - 1])}
  tiers       ${TIERS.map((t) => `${t.id} ${nf(tierCounts[t.id])}`).join(' - ')}
  basis       checked ${nf(checked)} (${pct(checked, all.length)}) - scored ${nf(all.length - checked)}
  ${'-'.repeat(70)}
  wrote lib/bi.roster.data.ts and ${byDistrict.size} files in public/data/bi/roster/ (${nf(Math.round(bytes / 1024))} KB)
`)
