#!/usr/bin/env node
/**
 * Write the committed weight snapshot.
 *
 * The site publishes what it costs. Every page states its own gzip transfer
 * size against the budget this repository sets for itself, and /build states
 * the whole table — which is only an honest claim if the numbers come from the
 * same measurement the gate fails builds over. They do: both import
 * lib/perf/measure.mjs.
 *
 * Run by the author after `pnpm build`, not by the build. A build cannot
 * measure itself: the number would have to be written into the HTML that is
 * being measured, and writing it changes it. So this is a snapshot of the
 * PREVIOUS build, exactly like lib/git.data.json is a snapshot that cannot
 * contain the commit that adds it. The page says so rather than pretending.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

import { measureBuild } from '../lib/perf/measure.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'lib', 'perf.data.json')
const BUDGET = join(ROOT, 'perf.budget.json')

const line = (s) => process.stdout.write(s + '\n')
const die = (msg) => {
  line(`  ✗ ${msg}`)
  line('')
  process.exit(1)
}

line('')
line('  WEIGHT SNAPSHOT')
line('  ' + '-'.repeat(70))

if (!existsSync(join(ROOT, '.next', 'server', 'app'))) {
  die('no production build to measure — run `pnpm build` first')
}

const build = measureBuild()
if (build.ok.length === 0) die('the build contains no prerendered routes')

const budget = JSON.parse(readFileSync(BUDGET, 'utf8'))

let head = ''
try {
  head = execFileSync('git', ['rev-parse', '--short=7', 'HEAD'], {
    cwd: ROOT,
    encoding: 'utf8',
  }).trim()
} catch {
  head = ''
}

/* Routes as an object keyed by path, not an array: every reader wants one
   route by name and none of them want to scan. */
const routes = {}
for (const r of build.ok) {
  routes[r.route] = {
    html: r.used.html,
    css: r.used.css,
    js: r.used.js,
    font: r.used.font,
    total: r.used.total,
  }
}

const snapshot = {
  $comment: [
    'GENERATED by `pnpm sync:perf`. Do not hand-edit.',
    '',
    'Gzip transfer size per prerendered route, from the same measurement',
    '`pnpm check:budget` fails builds over — lib/perf/measure.mjs.',
    '',
    'It measures the PREVIOUS build. A build cannot state its own weight:',
    'the number would go into the HTML being weighed, and writing it changes',
    'the weight. The pages that show it say which build it came from.',
  ],
  unit: 'gzip-bytes',
  generatedAt: new Date().toISOString().slice(0, 10),
  head,
  budgets: budget.budgets,
  shared: build.sharedBytes,
  deferred: build.deferred.bytes,
  routes,
}

const json = JSON.stringify(snapshot, null, 2) + '\n'
writeFileSync(OUT, json, 'utf8')

const kb = (n) => (n / 1024).toFixed(1)
const worst = build.ok.reduce((a, b) => (b.used.total > a.used.total ? b : a))
const pct = ((worst.used.total / budget.budgets.total) * 100).toFixed(0)

line(`  ${build.ok.length} routes · head ${head || '(no git)'}`)
line(`  heaviest   ${worst.route} — ${kb(worst.used.total)} KB (${pct}% of budget)`)
line(`  shared js  ${kb(build.sharedBytes)} KB · deferred ${kb(build.deferred.bytes)} KB`)
line(`  written    lib/perf.data.json (${kb(Buffer.byteLength(json))} KB)`)
line('  ' + '-'.repeat(70))
line('  OK — commit this file alongside the build it measures')
line('')
