#!/usr/bin/env node
/**
 * Write the committed build-record snapshot.
 *
 * Run by the author, not by the build. `next build` prefers the live
 * repository and only falls back to this file when the history it can see is
 * unusable — which is the normal case on Vercel, where the clone is shallow.
 *
 * Two refusals, both deliberate:
 *
 *   shallow repository   Would write a truncated record that looks complete.
 *   truncated history    Would silently drop the beginning of the record. A
 *                        shorter result is fine when the oldest commit on
 *                        file is still reachable — that is a local rewind,
 *                        not a bad clone. See the guard below.
 *
 * And one assertion: no email address may reach the file. The parser does not
 * collect authors, so a match here means the projection regressed.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

import { GIT_LOG_ARGS, parseGitLog, toCommitRecord } from '../lib/git/parse.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'lib', 'git.data.json')

const line = (s) => process.stdout.write(s + '\n')
const die = (msg) => {
  line(`  ✗ ${msg}`)
  line('')
  process.exit(1)
}

const git = (args) =>
  execFileSync('git', args, {
    cwd: ROOT,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })

line('')
line('  GIT SNAPSHOT')
line('  ' + '-'.repeat(70))

if (git(['rev-parse', '--is-shallow-repository']).trim() !== 'false') {
  die('shallow repository — a truncated record must not be committed')
}

const commits = parseGitLog(git(GIT_LOG_ARGS)).map(toCommitRecord)
if (commits.length === 0) die('no commits found')

/* The snapshot cannot contain the commit that updates it, so it is always
   at least one commit behind. Stated here and on the page rather than
   pretended away. */
const head = commits[0].sha

if (existsSync(OUT)) {
  const prev = JSON.parse(readFileSync(OUT, 'utf8'))
  /*
   * A shorter record than the one on disk has two causes and they are not
   * remotely the same thing.
   *
   *   TRUNCATED AT THE ROOT — a partial or filtered clone, a graft, the wrong
   *     repository. The record would silently lose its beginning and the
   *     build would publish a history that starts in the middle.
   *   REWOUND AT THE TIP — a local reset, squashing commits before they are
   *     pushed. Ordinary, and the record should follow.
   *
   * This used to compare COUNTS, which cannot tell them apart: both make the
   * number smaller. It refused a legitimate squash twice before this was
   * fixed, and the workaround was to delete the file — which disables the
   * check entirely rather than for one run.
   *
   * The OLDEST commit tells them apart. Root truncation loses it; a tip
   * rewind keeps it reachable from HEAD. Commits are stored newest-first, so
   * the oldest is the last element.
   */
  const prevCommits = Array.isArray(prev.commits) ? prev.commits : []
  const prevOldest = prevCommits[prevCommits.length - 1]?.sha

  if (typeof prevOldest === 'string' && commits.length < prevCommits.length) {
    let rootReachable = false
    try {
      execFileSync('git', ['merge-base', '--is-ancestor', prevOldest, 'HEAD'], {
        cwd: ROOT,
        stdio: 'ignore',
      })
      rootReachable = true
    } catch {
      rootReachable = false
    }

    if (!rootReachable) {
      die(
        `the record's oldest commit ${prevOldest} is not reachable from HEAD — ` +
          `this history is truncated, not rewound`,
      )
    }

    line(
      `  · rewound ${prevCommits.length} -> ${commits.length} commits ` +
        `(oldest ${prevOldest} still reachable)`,
    )
  }
  if (prev.head === head) {
    line(`  · already at ${head} — nothing to write`)
    line('')
    process.exit(0)
  }
}

const snapshot = {
  $comment: [
    'GENERATED by `pnpm sync:git`. Do not hand-edit.',
    '',
    'The build record for /build and for per-entry history. `next build`',
    'prefers the live repository and reads this only when the history it can',
    'see is unusable — a shallow CI clone, or a deploy with no .git at all.',
    '',
    'It cannot contain the commit that writes it, so it is always at least',
    'one commit behind HEAD. `pnpm check:release` reports the distance.',
    '',
    'Author names and email addresses are deliberately absent: this is a',
    'single-author repository, so the field carries no information, and it',
    'would publish a personal address into static HTML.',
  ],
  generatedAt: new Date().toISOString().slice(0, 10),
  head,
  commits,
}

const json = JSON.stringify(snapshot, null, 2) + '\n'

const email = /[\w.+-]+@[\w-]+\.[\w.-]+/.exec(json)
if (email) die(`an email address reached the snapshot: ${email[0]}`)

writeFileSync(OUT, json, 'utf8')

const sum = (k) => commits.reduce((n, c) => n + c[k], 0)
const kb = (Buffer.byteLength(json) / 1024).toFixed(1)

line(`  ${commits.length} commits · ${commits[commits.length - 1].date} — ${commits[0].date}`)
line(`  authored  +${sum('insertions')} / -${sum('deletions')}`)
line(`  generated  ${sum('generated')} lines (lockfiles, binaries)`)
line(`  head       ${head}`)
line(`  written    lib/git.data.json (${kb} KB)`)
line('  ' + '-'.repeat(70))
line('  OK — commit this file alongside the work it records')
line('')
