#!/usr/bin/env node
/**
 * Generate `public/_headers` from the one CSP definition.
 *
 * WHY THIS FILE EXISTS AT ALL.
 *
 * `output: 'export'` does not support `headers()` in next.config.ts, and it
 * does not fail the build over it — it prints a warning and drops them:
 *
 *   ⚠ Specified "headers" will not automatically work with "output: export".
 *
 * A build that succeeds while silently shipping no Content-Security-Policy is
 * exactly the failure mode this repository writes about, so the headers move
 * to the host. Cloudflare reads a `_headers` file out of the asset directory;
 * `public/` is copied into `out/` verbatim, so that is where it goes.
 *
 * WHY GENERATED RATHER THAN WRITTEN BY HAND.
 *
 * `scripts/check-release.mjs` imports `contentSecurityPolicy` and asserts
 * that the production policy has no 'unsafe-eval' and does have
 * frame-ancestors, object-src, base-uri and upgrade-insecure-requests. A
 * hand-copied CSP in `_headers` would leave that gate checking a string
 * nothing serves — the gate would keep passing while the deployed policy
 * drifted. Both sides read the same function, so they cannot disagree.
 *
 * `pnpm build` runs this first, so the file cannot be stale in any build.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

import { contentSecurityPolicy } from '../lib/csp.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const PUBLIC = join(ROOT, 'public')
const OUT = join(PUBLIC, '_headers')

/**
 * The security headers, verbatim from what next.config.ts served before the
 * static export. Kept in this order so a diff against the git history of
 * next.config.ts is readable.
 */
const SECURITY = [
  ['Content-Security-Policy', contentSecurityPolicy({ dev: false })],
  ['Referrer-Policy', 'strict-origin-when-cross-origin'],
  ['X-Content-Type-Options', 'nosniff'],
  ['X-Frame-Options', 'DENY'],
  [
    'Permissions-Policy',
    'camera=(), microphone=(), geolocation=(), interest-cohort=()',
  ],
  ['Strict-Transport-Security', 'max-age=63072000; includeSubDomains; preload'],
]

/**
 * Content-Type for the two routes that emit an image under a name with no
 * extension.
 *
 * `next/og` writes `out/icon` and `out/<lang>/opengraph-image` — real PNGs
 * with no suffix, confirmed with `file --mime-type` on a real export. A
 * static host types a response from its extension, so without these the
 * favicon and every social card would be served as an octet-stream and
 * silently not render. Nothing in the build warns about it.
 */
const IMAGE_TYPES = [
  ['/icon', 'image/png'],
  ['/*/opengraph-image', 'image/png'],
]

/* Cloudflare allows 100 header rules and 2,000 characters per line. The CSP
   is the only line that could approach either, so it is measured rather than
   assumed. */
const MAX_RULES = 100
const MAX_LINE = 2000

const lines = []
const rule = (pattern, headers) => {
  lines.push(pattern)
  for (const [k, v] of headers) lines.push(`  ${k}: ${v}`)
  lines.push('')
}

lines.push('# Generated by scripts/sync-headers.mjs — do not edit.')
lines.push('# The Content-Security-Policy comes from lib/csp.mjs, which is the')
lines.push('# same function pnpm check:release asserts against.')
lines.push('')

rule('/*', SECURITY)
rule('/_next/static/*', [
  ['Cache-Control', 'public, max-age=31536000, immutable'],
])
for (const [pattern, type] of IMAGE_TYPES) {
  rule(pattern, [['Content-Type', type]])
}

const body = lines.join('\n')

/* ------------------------------------------------------------------ */
/* Limits                                                              */
/* ------------------------------------------------------------------ */

const problems = []
const ruleCount = lines.filter((l) => l.startsWith('/')).length
if (ruleCount > MAX_RULES) {
  problems.push(`${ruleCount} header rules — Cloudflare allows ${MAX_RULES}`)
}
for (const l of lines) {
  if (l.length > MAX_LINE) {
    /* The header NAME is printed, never the value: a CSP is long and the
       point of the message is which line to shorten. */
    problems.push(`a header line is ${l.length} chars — the limit is ${MAX_LINE} (${l.slice(0, 40).trim()}…)`)
  }
}

const out = []
const line = (s) => out.push(s)

line('')
line('  HEADERS')
line('  ' + '-'.repeat(70))

if (!existsSync(PUBLIC)) mkdirSync(PUBLIC, { recursive: true })

const previous = existsSync(OUT) ? readFileSync(OUT, 'utf8') : null
if (previous !== body) writeFileSync(OUT, body + '\n', 'utf8')

const csp = SECURITY[0][1]
line(`  ${ruleCount} rules · CSP ${csp.length} chars · longest line ${Math.max(...lines.map((l) => l.length))}`)
line(`  ${previous === null ? 'created' : previous === body ? 'unchanged' : 'updated'}  public/_headers`)

for (const p of problems) line(`  ✗ ${p}`)
line('  ' + '-'.repeat(70))
if (problems.length) {
  line(`  FAIL — ${problems.length} header problem${problems.length === 1 ? '' : 's'}`)
  line('')
  process.stdout.write(out.join('\n') + '\n')
  process.exit(1)
}
line('  OK — the deployed policy is the one check:release asserts.')
line('')
process.stdout.write(out.join('\n') + '\n')
